Microsoft (R) Direct3D Shader Compiler 10.1
Copyright (C) 2013 Microsoft. All rights reserved.

//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer cPSScene
// {
//
//   struct PSScene
//   {
//       
//       float4x4 m_projectionView;     // Offset:    0
//       float4x4 m_projection;         // Offset:   64
//       float4x4 m_view;               // Offset:  128
//       float4x4 m_shadowProjection;   // Offset:  192
//       float4x4 m_shadowProjection2;  // Offset:  256
//       float4 m_eyepos;               // Offset:  320
//       float4 m_projectionParam;      // Offset:  336
//       float4 m_viewportSize;         // Offset:  352
//       float4 m_exposure;             // Offset:  368
//       float4 m_fogParam[3];          // Offset:  384
//       float4 m_fogColor;             // Offset:  432
//       float4 m_cameraCenterOffset;   // Offset:  448
//       float4 m_shadowMapResolutions; // Offset:  464
//
//   } g_psScene;                       // Offset:    0 Size:   480
//
// }
//
// cbuffer cPSMaterial
// {
//
//   struct PSMaterial
//   {
//       
//       float4 m_materials[8];         // Offset:    0
//
//   } g_psMaterial;                    // Offset:    0 Size:   128
//
// }
//
// cbuffer cPSSystem
// {
//
//   struct PSSystem
//   {
//       
//       float4 m_param;                // Offset:    0
//       float4 m_renderInfo;           // Offset:   16
//       float4 m_renderBuffer;         // Offset:   32
//       float4 m_dominantLightDir;     // Offset:   48
//
//   } g_psSystem;                      // Offset:    0 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// g_samplerPoint_Wrap               sampler      NA          NA             s8      1 
// g_samplerLinear_Clamp             sampler      NA          NA            s11      1 
// inMesh                            texture  float4          2d             t8      1 
// g_tex_fog                         texture  float4          2d            t12      1 
// cPSSystem                         cbuffer      NA          NA            cb0      1 
// cPSScene                          cbuffer      NA          NA            cb2      1 
// cPSMaterial                       cbuffer      NA          NA            cb4      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xy  
// TEXCOORD                 0   xyz         1     NONE   float   xyz 
// TEXCOORD                 1   xyzw        2     NONE   float       
// TEXCOORD                 2   xyzw        3     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB2[26], immediateIndexed
dcl_constantbuffer CB4[7], immediateIndexed
dcl_constantbuffer CB0[2], immediateIndexed
dcl_sampler s8, mode_default
dcl_sampler s11, mode_default
dcl_resource_texture2d (float,float,float,float) t8
dcl_resource_texture2d (float,float,float,float) t12
dcl_input_ps_siv linear noperspective v0.xy, position
dcl_input_ps linear v1.xyz
dcl_output o0.xyzw
dcl_temps 5

#line 445 "d:\work\master\git_clone\_intermediate\win64\TppShaders_dx11_win64\Release\Sky_Draw_TppNoSky_ps.hlsl"
add r0.xy, v0.xyxx, l(-0.500000, -0.500000, 0.000000, 0.000000)  // inVPos<0,1>

#line 471
mov r0.xy, r0.xyxx  // NCalculateTextureCordinate_calculateTexcoord_inVPos<0,1>

#line 472
nop 
mov r0.xy, r0.xyxx  // inVPos<0,1>

#line 356
mul r0.zw, r0.xxxy, l(0.000000, 0.000000, 0.125000, 0.125000)
frc r0.zw, r0.zzzw  // outDitherTexcoord<0:[0f,1f],1:[0f,1f]>

#line 472
mov r0.zw, r0.zzzw  // NCalculateTextureCordinate_calculateTexcoord_outDitherTexcoord<0:[0f,1f],1:[0f,1f]>

#line 502
nop 

#line 72
div r0.xy, r0.xyxx, cb0[1].xyxx  // outClipPosition<0:NaN:Inf,1:NaN:Inf>

#line 73
mul r0.xy, r0.xyxx, l(2.000000, -2.000000, 0.000000, 0.000000)
add r0.xy, r0.xyxx, l(-1.000000, 1.000000, 0.000000, 0.000000)  // outClipPosition<0:NaN:Inf,1:NaN:Inf>

#line 502
mov r0.xy, r0.xyxx  // NScreenToClipCoordinate_screenToClipcoord_outClipPosition<0:NaN:Inf,1:NaN:Inf>

#line 475
mov r1.xyz, v1.xyzx  // NViewRay_viewRay_inRay<0,1,2>

#line 476
nop 
mov r1.xyz, r1.xyzx  // inRay<0,1,2>

#line 394
mov r1.w, cb4[2].y  // dist<0>

#line 395
mov r2.x, cb4[2].w  // isNotFollowCam<0>

#line 396
mov r2.y, cb4[6].z  // offsetPosY<0>

#line 397
dp3 r2.z, r1.xyzx, r1.xyzx
rsq r2.z, r2.z
mul r1.xyz, r1.xyzx, r2.zzzz
div r1.w, l(1.000000), r1.w
mul r2.x, r2.x, cb2[20].y
mov r2.y, -r2.y
add r2.y, r2.y, r2.x
mov r2.xz, l(0,0,0,0)
mul r2.xyz, r1.wwww, r2.xyzx
add r1.xyz, r1.xyzx, r2.xyzx
dp3 r1.x, r1.xyzx, r1.xyzx
rsq r1.x, r1.x
mul r1.x, r1.x, r1.y  // outViewRay<1:NaN:Inf>

#line 399
max r1.x, r1.x, l(0.000000)  // outViewRay<1:Inf:[-0f,1.#INFf]>

#line 476
mov r1.x, r1.x  // NViewRay_viewRay_outViewRay<1:NaN:Inf>

#line 490
nop 

#line 496
nop 

#line 501
nop 

#line 482
nop 

#line 261
nop 

#line 228
nop 

#line 229
nop 

#line 230
nop 

#line 170
nop 

#line 171
nop 

#line 234
nop 

#line 485
nop 

#line 496
nop 

#line 498
nop 

#line 502
mov r1.x, r1.x  // NApplyFurthestFog2_applyFog_inViewZenith<0:NaN:Inf>

#line 504
mov r0.xy, r0.xyxx  // NApplyFurthestFog2_applyFog_inClipCoord<0:NaN:Inf,1:NaN:Inf>

#line 505
nop 
mov r1.x, r1.x  // inViewZenith<0:NaN:Inf>
mov r0.xy, r0.xyxx  // inClipCoord<0:NaN:Inf,1:NaN:Inf>

#line 317
nop 
mov r0.xy, r0.xyxx  // inClipPos<0:NaN:Inf,1:NaN:Inf>

#line 156
nop 
mov r0.xy, r0.xyxx  // inClipPos<0:NaN:Inf,1:NaN:Inf>

#line 79
mul r0.xy, r0.xyxx, l(0.014648, 0.123047, 0.000000, 0.000000)
add r0.xy, r0.xyxx, l(0.015625, 0.125000, 0.000000, 0.000000)  // uv<0:NaN:Inf,1:NaN:Inf>

#line 84
add r0.xy, r0.xyxx, l(0.968750, 0.750000, 0.000000, 0.000000)  // uv_lerp<0:NaN:Inf,1:NaN:Inf>

#line 85
sample_indexable(texture2d)(float,float,float,float) r1.yzw, r0.xyxx, t12.wxyz, s11
mov r1.yzw, r1.yyzw  // fogColor<0:Inf,1:Inf,2:Inf>

#line 90
mov r0.x, cb2[25].y  // normalizeFactor<0>

#line 91
mul r1.yzw, r0.xxxx, r1.yyzw  // fogColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 92
mov r1.yzw, r1.yyzw  // GetFurthestVolumetricFog2D<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 156
mov r1.yzw, r1.yyzw  // GetFurthestVolumetricFog<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 317
mov r1.yzw, r1.yyzw  // fogColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 320
mov r0.x, cb4[1].w  // influenceOfFogFix<0>

#line 321
mov r0.y, cb4[5].w  // influenceOfFogVar<0>

#line 322
mov r2.x, cb4[6].x  // falloff<0>

#line 323
mov r2.y, cb4[6].y  // invFalloffStart<0>

#line 324
nop 
add r1.x, r1.x, l(-1.000000)  // elevationAngle<0:NaN:Inf>
mov r0.x, r0.x  // influenceOfFogFix<0>
mov r0.y, r0.y  // influenceOfFogVar<0>
mov r2.x, r2.x  // falloff<0>
mov r2.y, r2.y  // invFalloffStart<0>

#line 26
mul r1.x, r1.x, r2.y
max r1.x, r1.x, l(0.000000)
min r1.x, r1.x, l(1.000000)  // t<0:[0f,1f]>

#line 27
mul r2.x, r1.x, r2.x
add r1.x, r1.x, r2.x
add r2.x, r2.x, l(1.000000)
div r1.x, r1.x, r2.x
mul r0.y, r0.y, r1.x
add r0.x, r0.y, r0.x  // influenceOfFog<0:NaN:Inf>

#line 28
mov r0.x, r0.x  // CalcInfluenceOfFog<0:NaN:Inf>

#line 324
mov r0.x, r0.x  // influenceOfFog<0:NaN:Inf>

#line 327
mul r1.xyz, r0.xxxx, r1.yzwy  // fogColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 329
add r1.xyz, r1.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 505
mov r1.xyz, r1.xyzx  // NApplyFurthestFog2_applyFog_outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 507
mov r1.xyz, r1.xyzx  // NDithering2_dithering_inColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 508
mov r0.zw, r0.zzzw  // NDithering2_dithering_inTexcoord<0:[0f,1f],1:[0f,1f]>

#line 509
nop 
mov r1.xyz, r1.xyzx  // inColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
mov r0.zw, r0.zzzw  // inTexcoord<0:[0f,1f],1:[0f,1f]>

#line 328
sample_indexable(texture2d)(float,float,float,float) r0.x, r0.zwzz, t8.xyzw, s8
add r0.x, r0.x, l(-0.500000)
div r0.x, r0.x, l(128.000000)
add r0.xyz, r0.xxxx, r1.xyzx  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 509
mov r0.xyz, r0.xyzx  // NDithering2_dithering_outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 511
mov r0.xyz, r0.xyzx  // NCalcurateOutputColor_calcOutputColor_inColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 512
nop 
mov r0.xyz, r0.xyzx  // inColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 419
mov r0.xyz, r0.xyzx  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 422
mov r1.xyz, cb4[1].xyzx  // tonemapParam<0,1,2>

#line 423
nop 
mov r1.xyz, r1.xyzx  // params<0,1,2>
mov r0.xyz, r0.xyzx  // x<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 11
mov r2.xyz, r1.yyyy
ge r2.xzw, r2.xxyz, r0.xxyz
movc r2.xzw, r2.xxzw, l(1.000000,0,1.000000,1.000000), l(0,0,0,0)  // mask<0:NaN,1:NaN,2:NaN>

#line 12
mul r3.xyz, r0.xyzx, r2.xzwx
mov r2.xzw, -r2.xxzw
add r2.xzw, r2.xxzw, l(1.000000, 0.000000, 1.000000, 1.000000)
add r0.xyz, r1.zzzz, r0.xyzx
mov r4.xyz, -r2.yyyy
add r0.xyz, r0.xyzx, r4.xyzx
mul r0.xyz, r0.xyzx, r1.xxxx
div r0.xyz, l(-1.000000, -1.000000, -1.000000, 0.000000), r0.xyzx
add r0.xyz, r1.zzzz, r0.xyzx
add r0.xyz, r2.yyyy, r0.xyzx
mul r0.xyz, r0.xyzx, r2.xzwx
add r0.xyz, r0.xyzx, r3.xyzx  // TppTonemap<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 423
mov r0.xyz, r0.xyzx  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 424
max r0.xyz, r0.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
min r0.xyz, r0.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)  // outColor<0:[0f,1f],1:[0f,1f],2:[0f,1f]>

#line 427
nop 
mov r0.xyz, r0.xyzx  // linearRGB<0:[0f,1f],1:[0f,1f],2:[0f,1f]>

#line 24
ge r1.xyz, l(0.003131, 0.003131, 0.003131, 0.000000), r0.xyzx
movc r1.xyz, r1.xyzx, l(1.000000,1.000000,1.000000,0), l(0,0,0,0)  // mask<0:NaN,1:NaN,2:NaN>

#line 25
mul r2.xyz, r0.xyzx, l(12.920000, 12.920000, 12.920000, 0.000000)
mul r2.xyz, r1.xyzx, r2.xyzx
mov r1.xyz, -r1.xyzx
add r1.xyz, r1.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
max r0.xyz, r0.xyzx, l(0.000010, 0.000010, 0.000010, 0.000000)
log r0.xyz, r0.xyzx
mul r0.xyz, r0.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
exp r0.xyz, r0.xyzx
mul r0.xyz, r0.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000)
add r0.xyz, r0.xyzx, l(-0.055000, -0.055000, -0.055000, 0.000000)
mul r0.xyz, r0.xyzx, r1.xyzx
add r0.xyz, r0.xyzx, r2.xyzx  // GammaCorrection<0:NaN,1:NaN,2:NaN>

#line 427
mov r0.xyz, r0.xyzx  // outColor<0:NaN,1:NaN,2:NaN>

#line 512
mov r0.xyz, r0.xyzx  // NCalcurateOutputColor_calcOutputColor_outColor<0:NaN,1:NaN,2:NaN>
mov r0.w, l(0)  // NCalcurateOutputColor_calcOutputColor_outColor<3: 0f>
mov o0.xyzw, r0.xyzw  // outColor<0:NaN,1:NaN,2:NaN,3: 0f>

#line 436
ret 
// Approximately 147 instruction slots used
