Microsoft (R) Direct3D Shader Compiler 10.1
Copyright (C) 2013 Microsoft. All rights reserved.

//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer cPSScene
// {
//
//   struct PSScene
//   {
//       
//       float4x4 m_projectionView;     // Offset:    0
//       float4x4 m_projection;         // Offset:   64
//       float4x4 m_view;               // Offset:  128
//       float4x4 m_shadowProjection;   // Offset:  192
//       float4x4 m_shadowProjection2;  // Offset:  256
//       float4 m_eyepos;               // Offset:  320
//       float4 m_projectionParam;      // Offset:  336
//       float4 m_viewportSize;         // Offset:  352
//       float4 m_exposure;             // Offset:  368
//       float4 m_fogParam[3];          // Offset:  384
//       float4 m_fogColor;             // Offset:  432
//       float4 m_cameraCenterOffset;   // Offset:  448
//       float4 m_shadowMapResolutions; // Offset:  464
//
//   } g_psScene;                       // Offset:    0 Size:   480
//
// }
//
// cbuffer cPSObject
// {
//
//   struct PSObject
//   {
//       
//       float4x4 m_viewWorld;          // Offset:    0
//       float4x4 m_world;              // Offset:   64
//       float4 m_useWeightCount;       // Offset:  128
//       float4 m_localParam[4];        // Offset:  144
//
//   } g_psObject;                      // Offset:    0 Size:   208
//
// }
//
// cbuffer cPSMaterial
// {
//
//   struct PSMaterial
//   {
//       
//       float4 m_materials[8];         // Offset:    0
//
//   } g_psMaterial;                    // Offset:    0 Size:   128
//
// }
//
// cbuffer cPSSystem
// {
//
//   struct PSSystem
//   {
//       
//       float4 m_param;                // Offset:    0
//       float4 m_renderInfo;           // Offset:   16
//       float4 m_renderBuffer;         // Offset:   32
//       float4 m_dominantLightDir;     // Offset:   48
//
//   } g_psSystem;                      // Offset:    0 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// inTextureSampler                  sampler      NA          NA             s0      1 
// g_samplerLinear_Clamp             sampler      NA          NA            s11      1 
// inTexture                         texture  float4          2d             t0      1 
// g_tex_fog                         texture  float4          2d            t12      1 
// cPSSystem                         cbuffer      NA          NA            cb0      1 
// cPSScene                          cbuffer      NA          NA            cb2      1 
// cPSMaterial                       cbuffer      NA          NA            cb4      1 
// cPSObject                         cbuffer      NA          NA            cb5      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xy          0     NONE   float   xy  
// TEXCOORD                 3     z         0     NONE   float     z 
// TEXCOORD                 1   xyzw        1     NONE   float   xyz 
// TEXCOORD                 2   xyzw        2     NONE   float   xyz 
// SV_Position              0   xyzw        3      POS   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xyzw        1   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB2[26], immediateIndexed
dcl_constantbuffer CB5[13], immediateIndexed
dcl_constantbuffer CB4[1], immediateIndexed
dcl_constantbuffer CB0[2], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s11, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t12
dcl_input_ps linear v0.xy
dcl_input_ps linear v0.z
dcl_input_ps linear v1.xyz
dcl_input_ps linear v2.xyz
dcl_input_ps_siv linear noperspective v3.xy, position
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_temps 6

#line 214 "d:\work\master\git_clone\_intermediate\win64\TppShaders_dx11_win64\Release\Prim_Poly_FastDraw_SSky_VF_ps.hlsl"
add r0.xyzw, v3.xyxy, l(-0.500000, -0.500000, -0.500000, -0.500000)  // inVPos<0,1,0,1>

#line 227
mov r1.xyz, v1.xyzx  // NComputePrimitiveColorFastDraw_computePrimitiveColor_inColor<0,1,2>

#line 230
mov r2.xy, v2.xyxx  // NComputePrimitiveColorFastDraw_computePrimitiveColor_inParams<0,1>

#line 231
nop 
mov r1.xyz, r1.xyzx  // inColor<0,1,2>
mov r2.xy, r2.xyxx  // inParams<0,1>

#line 167
sample_indexable(texture2d)(float,float,float,float) r3.xyzw, v0.xyxx, t0.xyzw, s0  // c0<0:Inf,1:Inf,2:Inf,3:Inf>

#line 174
div r3.xyz, r3.xyzx, r3.wwww  // c0<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 175
mul r1.xyz, r1.xyzx, r3.xyzx  // c0<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 176
nop 
mov r2.xy, r2.xyxx  // params<0,1>

#line 441
mul r1.w, r2.y, r2.x  // GetPrecalculatedLuminance<0:Inf>

#line 176
mul r1.xyz, r1.wwww, r1.xyzx  // c0<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 179
max r1.xyz, r1.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
min r1.xyz, r1.xyzx, l(154.600006, 154.600006, 154.600006, 0.000000)  // c0<0:[-0f,154.6f],1:[-0f,154.6f],2:[-0f,154.6f]>

#line 180
log r1.xyz, r1.xyzx
mul r1.xyz, r1.xyzx, l(2.200000, 2.200000, 2.200000, 0.000000)
exp r1.xyz, r1.xyzx  // outColor<0:[0f,65503f],1:[0f,65503f],2:[0f,65503f]>

#line 231
mov r1.xyz, r1.xyzx  // NComputePrimitiveColorFastDraw_computePrimitiveColor_outColor<0:[0f,65503f],1:[0f,65503f],2:[0f,65503f]>

#line 237
mov r1.xyz, r1.xyzx  // NCalcVolumeFogColorSSky_calcFogColor_inColor<0:[0f,65503f],1:[0f,65503f],2:[0f,65503f]>

#line 234
mov r0.xyzw, r0.xyzw  // NCalcVolumeFogColorSSky_calcFogColor_inVPos<0,1,0,1>

#line 235
mov r1.w, v2.z  // NCalcVolumeFogColorSSky_calcFogColor_inClipViewZPos<0>

#line 236
mov r2.x, v0.z  // NCalcVolumeFogColorSSky_calcFogColor_inFogGain<0>

#line 237
nop 
mov r1.xyz, r1.xyzx  // inColor<0:[0f,65503f],1:[0f,65503f],2:[0f,65503f]>
mov r0.xyzw, r0.xyzw  // inVPos<0,1,0,1>
mov r1.w, r1.w  // inClipViewZPos<0>
mov r2.x, r2.x  // inFogGain<0>

#line 125
nop 
mov r0.xyzw, r0.xyzw  // inVPos<0,1,0,1>
mov r1.w, r1.w  // inViewZPos<0>

#line 765
mov r3.xyzw, cb0[1].xyxy
div r0.xyzw, r0.xyzw, r3.xyzw  // clipTexcoord<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>

#line 766
mul r0.xyzw, r0.xyzw, l(2.000000, -2.000000, 2.000000, -2.000000)
add r0.xyzw, r0.xyzw, l(-1.000000, 1.000000, -1.000000, 1.000000)  // clipTexcoord<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>

#line 767
nop 
mov r0.xyzw, r0.xyzw  // inClipPos<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>
mov r1.w, r1.w  // inViewZ<0>

#line 142
nop 
mov r0.xyzw, r0.xyzw  // inClipPos<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>
mov r1.w, r1.w  // inViewZ<0>

#line 50
nop 
mov r1.w, r1.w  // inViewZ<0>

#line 27
mov r2.y, cb2[25].x  // invLogFarDistance<0>

#line 30
log r1.w, r1.w
mul r1.w, r1.w, r2.y  // EncodeFogCameraZ<0:NaN:Inf>

#line 50
mov r1.w, r1.w  // zEncoded<0:NaN:Inf>

#line 51
max r1.w, r1.w, l(0.000000)
min r1.w, r1.w, l(1.000000)  // zEncoded<0:[0f,1f]>

#line 52
mul r1.w, r1.w, l(127.000000)  // zEncoded<0:[0f,127f]>

#line 56
mul r0.xyzw, r0.xyzw, l(0.014648, 0.123047, 0.014648, 0.123047)
add r0.xyzw, r0.xyzw, l(0.015625, 0.125000, 0.015625, 0.125000)  // uv<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>

#line 57
add r2.y, r1.w, l(1.000000)
max r2.y, r2.y, l(0.000000)
min r2.w, r2.y, l(127.000000)
mov r2.y, r1.w
round_ni r2.yz, r2.yywy  // zInt<0:[0f,127f],1:[1f,127f]>

#line 59
div r2.yz, r2.yyzy, l(0.000000, 32.000000, 32.000000, 0.000000)
frc r3.xy, r2.yzyy
mul r3.xz, r3.xxyx, l(32.000000, 0.000000, 32.000000, 0.000000)  // layerOffset<0:[0f,32f],2:[0f,32f]>

#line 60
round_ni r3.yw, r2.yyyz  // layerOffset<1:[0f,3f],3:[0f,3f]>

#line 61
mul r3.xyzw, r3.xyzw, l(0.031250, 0.250000, 0.031250, 0.250000)
add r0.xyzw, r0.xyzw, r3.xyzw  // uv_lerp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 62
frc r3.xyzw, r1.wwww  // zBlend<0:[0f,1f],1:[0f,1f],2:[0f,1f],3:[0f,1f]>

#line 63
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r0.xyxx, t12.xyzw, s11  // c0<0:Inf,1:Inf,2:Inf,3:Inf>

#line 64
sample_indexable(texture2d)(float,float,float,float) r0.xyzw, r0.zwzz, t12.xyzw, s11  // c1<0:Inf,1:Inf,2:Inf,3:Inf>

#line 65
mov r5.xyzw, -r3.xyzw
add r5.xyzw, r5.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
mul r4.xyzw, r4.xyzw, r5.xyzw
mul r0.xyzw, r0.xyzw, r3.xyzw
add r0.xyzw, r0.xyzw, r4.xyzw  // fogColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 69
mov r1.w, cb2[25].y  // normalizeFactor<0>

#line 70
mul r0.xyz, r0.xyzx, r1.wwww  // fogColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 71
mov r0.xyz, r0.xyzx  // GetVolumetricFog2D<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
mov r0.w, r0.w  // GetVolumetricFog2D<3:NaN:Inf>

#line 142
mov r0.xyzw, r0.xyzw  // GetVolumetricFog<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 767
mov r0.xyzw, r0.xyzw  // fogColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 768
mov r0.xyzw, r0.xyzw  // CalculateVolumeFogCommon<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 125
mov r0.xyzw, r0.xyzw  // fogColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 129
mul r0.xyz, r2.xxxx, r0.xyzx  // fogColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 130
mov r0.w, -r0.w
add r0.w, r0.w, l(1.000000)
mul r0.w, r2.x, r0.w
mov r0.w, -r0.w
add r0.w, r0.w, l(1.000000)  // fogColor<3:NaN:Inf>

#line 132
nop 
mov r1.xyz, r1.xyzx  // inColor<0:[0f,65503f],1:[0f,65503f],2:[0f,65503f]>
mov r0.xyz, r0.xyzx  // fogColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
mov r0.w, r0.w  // fogColor<3:NaN:Inf>

#line 779
nop 

#line 111
nop 

#line 148
mov r1.w, cb5[12].y  // GetBaseColor<1>

#line 111
mov r1.w, r1.w  // param<0>

#line 112
lt r1.w, r1.w, l(0.000000)
movc r2.xyz, r1.wwww, l(1.000000,1.000000,1.000000,0), l(0,0,0,0)  // GetBlendMode<0:[-0f,1f],0:[-0f,1f],0:[-0f,1f]>

#line 779
mov r2.xyz, r2.xyzx  // blendModeMask<0:[-0f,1f],0:[-0f,1f],0:[-0f,1f]>

#line 785
mov r1.w, -r0.w
add r1.w, r1.w, l(1.000000)
mul r1.w, r1.w, r2.z
mov r1.w, -r1.w
add r1.w, r1.w, l(1.000000)  // fogAlpha<0:NaN:Inf>

#line 794
mul r3.xyz, r0.wwww, r1.xyzx
add r0.xyz, r0.xyzx, r3.xyzx
mov r3.xyz, -r0.xyzx
add r1.xyz, r1.xyzx, r3.xyzx
mul r1.xyz, r1.xyzx, r2.xyzx
add r0.xyz, r0.xyzx, r1.xyzx  // inColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 799
mul r0.w, r1.w, l(1.000000)  // inColor<3:NaN:Inf>

#line 801
mov r0.xyz, r0.xyzx  // CalculateVolumeFogBlend<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
mov r0.w, r0.w  // CalculateVolumeFogBlend<3:NaN:Inf>

#line 132
mov r0.xyzw, r0.xyzw  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 237
mov r0.xyzw, r0.xyzw  // NCalcVolumeFogColorSSky_calcFogColor_outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 246
mov r0.w, r0.w  // NPrimitiveAlphaTest_alphaTest_inAlpha<0:NaN:Inf>

#line 247
nop 
mov r0.w, r0.w  // inAlpha<0:NaN:Inf>

#line 510
nop 

#line 128
nop 

#line 148
mov r1.x, cb5[12].z  // GetBaseColor<2>

#line 128
mov r1.x, r1.x  // param<0>

#line 129
lt r1.x, r1.x, l(0.000000)
movc r1.x, r1.x, l(1.000000), l(0)  // GetOpaqueMode<0:[-0f,1f]>

#line 510
eq r1.x, r1.x, l(1.000000)
if_nz r1.x

#line 511
  add r1.x, r0.w, l(-0.496078)  // alphaResult<0:NaN:Inf>

#line 512
  lt r1.x, r1.x, l(0.000000)
  and r1.x, r1.x, l(-1)
  discard_nz r1.x

#line 510
endif 

#line 521
mov r0.w, r0.w  // outAlpha<0:NaN:Inf>

#line 247
mov r0.w, r0.w  // NPrimitiveAlphaTest_alphaTest_outAlpha<0:NaN:Inf>

#line 240
mov r0.xyz, r0.xyzx  // NTppTonemap_tonemap_inColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 241
nop 
mov r0.xyz, r0.xyzx  // inColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 193
nop 
mov r1.xyz, cb4[0].xyzx  // params<0,1,2>
mov r0.xyz, r0.xyzx  // x<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 11
mov r2.xyz, r1.yyyy
ge r2.xzw, r2.xxyz, r0.xxyz
movc r2.xzw, r2.xxzw, l(1.000000,0,1.000000,1.000000), l(0,0,0,0)  // mask<0:[-0f,1f],1:[-0f,1f],2:[-0f,1f]>

#line 12
mul r3.xyz, r0.xyzx, r2.xzwx
mov r2.xzw, -r2.xxzw
add r2.xzw, r2.xxzw, l(1.000000, 0.000000, 1.000000, 1.000000)
add r4.xyz, r1.zzzz, r0.xyzx
mov r5.xyz, -r2.yyyy
add r4.xyz, r4.xyzx, r5.xyzx
mul r1.xyw, r1.xxxx, r4.xyxz
div r1.xyw, l(-1.000000, -1.000000, 0.000000, -1.000000), r1.xyxw
add r1.xyz, r1.zzzz, r1.xywx
add r1.xyz, r2.yyyy, r1.xyzx
mul r1.xyz, r1.xyzx, r2.xzwx
add r1.xyz, r1.xyzx, r3.xyzx  // TppTonemap<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 193
mov r1.xyz, r1.xyzx  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 241
mov r1.xyz, r1.xyzx  // NTppTonemap_tonemap_outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 243
mov r1.xyz, r1.xyzx  // NGammaEncodeF3_gammaEncode_inColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 244
nop 
mov r1.xyz, r1.xyzx  // inColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 17
nop 
mov r1.xyz, r1.xyzx  // linearRGB<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 24
ge r2.xyz, l(0.003131, 0.003131, 0.003131, 0.000000), r1.xyzx
movc r2.xyz, r2.xyzx, l(1.000000,1.000000,1.000000,0), l(0,0,0,0)  // mask<0:[-0f,1f],1:[-0f,1f],2:[-0f,1f]>

#line 25
mul r3.xyz, r1.xyzx, l(12.920000, 12.920000, 12.920000, 0.000000)
mul r3.xyz, r2.xyzx, r3.xyzx
mov r2.xyz, -r2.xyzx
add r2.xyz, r2.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
max r1.xyz, r1.xyzx, l(0.000010, 0.000010, 0.000010, 0.000000)
log r1.xyz, r1.xyzx
mul r1.xyz, r1.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
exp r1.xyz, r1.xyzx
mul r1.xyz, r1.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000)
add r1.xyz, r1.xyzx, l(-0.055000, -0.055000, -0.055000, 0.000000)
mul r1.xyz, r1.xyzx, r2.xyzx
add r0.xyz, r1.xyzx, r3.xyzx  // GammaCorrection<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 17
mov r0.xyz, r0.xyzx  // outColorSRGB<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 244
mov r0.xyz, r0.xyzx  // NGammaEncodeF3_gammaEncode_outColorSRGB<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 248
mov r0.xyz, r0.xyzx  // NCalcPremultipliedAlpha_calcPremultipliedAlpha_inColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 249
mov r0.w, r0.w  // NCalcPremultipliedAlpha_calcPremultipliedAlpha_inColor<3:NaN:Inf>

#line 250
nop 
mov r0.xyz, r0.xyzx  // inColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
mov r0.w, r0.w  // inColor<3:NaN:Inf>

#line 311
mov r0.xyzw, r0.xyzw  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 316
mul r0.xyz, r0.wwww, r0.xyzx  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 250
mov r0.xyz, r0.xyzx  // NCalcPremultipliedAlpha_calcPremultipliedAlpha_outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
mov r0.w, r0.w  // NCalcPremultipliedAlpha_calcPremultipliedAlpha_outColor<3:NaN:Inf>

#line 251
mov o0.xyzw, r0.xyzw  // outColor0<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 255
mov o1.xyzw, r0.xyzw  // outColor1<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 203
ret 
// Approximately 186 instruction slots used
