Microsoft (R) Direct3D Shader Compiler 10.1
Copyright (C) 2013 Microsoft. All rights reserved.

//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer cPSScene
// {
//
//   struct PSScene
//   {
//       
//       float4x4 m_projectionView;     // Offset:    0
//       float4x4 m_projection;         // Offset:   64
//       float4x4 m_view;               // Offset:  128
//       float4x4 m_shadowProjection;   // Offset:  192
//       float4x4 m_shadowProjection2;  // Offset:  256
//       float4 m_eyepos;               // Offset:  320
//       float4 m_projectionParam;      // Offset:  336
//       float4 m_viewportSize;         // Offset:  352
//       float4 m_exposure;             // Offset:  368
//       float4 m_fogParam[3];          // Offset:  384
//       float4 m_fogColor;             // Offset:  432
//       float4 m_cameraCenterOffset;   // Offset:  448
//       float4 m_shadowMapResolutions; // Offset:  464
//
//   } g_psScene;                       // Offset:    0 Size:   480
//
// }
//
// cbuffer cPSObject
// {
//
//   struct PSObject
//   {
//       
//       float4x4 m_viewWorld;          // Offset:    0
//       float4x4 m_world;              // Offset:   64
//       float4 m_useWeightCount;       // Offset:  128
//       float4 m_localParam[4];        // Offset:  144
//
//   } g_psObject;                      // Offset:    0 Size:   208
//
// }
//
// cbuffer cPSMaterial
// {
//
//   struct PSMaterial
//   {
//       
//       float4 m_materials[8];         // Offset:    0
//
//   } g_psMaterial;                    // Offset:    0 Size:   128
//
// }
//
// cbuffer cPSSystem
// {
//
//   struct PSSystem
//   {
//       
//       float4 m_param;                // Offset:    0
//       float4 m_renderInfo;           // Offset:   16
//       float4 m_renderBuffer;         // Offset:   32
//       float4 m_dominantLightDir;     // Offset:   48
//
//   } g_psSystem;                      // Offset:    0 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// g_samplerLinear_Wrap              sampler      NA          NA            s10      1 
// g_samplerLinear_Clamp             sampler      NA          NA            s11      1 
// g_samplerAnisotropic_Wrap         sampler      NA          NA            s12      1 
// inGradientTexture                 texture  float4          2d             t1      1 
// inWhitecapTexture1                texture  float4          2d             t2      1 
// inFoamTexture                     texture  float4          2d             t3      1 
// inNormalDetailTexture             texture  float4          2d             t4      1 
// inFoamTexture2                    texture  float4          2d             t5      1 
// g_tex_fog                         texture  float4          2d            t12      1 
// cPSSystem                         cbuffer      NA          NA            cb0      1 
// cPSScene                          cbuffer      NA          NA            cb2      1 
// cPSMaterial                       cbuffer      NA          NA            cb4      1 
// cPSObject                         cbuffer      NA          NA            cb5      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xy  
// TEXCOORD                 0   xyz         1     NONE   float   xyz 
// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xyzw        1   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB2[26], immediateIndexed
dcl_constantbuffer CB5[10], immediateIndexed
dcl_constantbuffer CB4[8], immediateIndexed
dcl_constantbuffer CB0[2], immediateIndexed
dcl_sampler s10, mode_default
dcl_sampler s11, mode_default
dcl_sampler s12, mode_default
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t4
dcl_resource_texture2d (float,float,float,float) t5
dcl_resource_texture2d (float,float,float,float) t12
dcl_input_ps_siv linear noperspective v0.xy, position
dcl_input_ps linear v1.xyz
dcl_input_ps linear v2.xyzw
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_temps 17

#line 536 "d:\work\master\git_clone\_intermediate\win64\TppShaders_dx11_win64\Release\Primitive_TppFourierOceanFill_ps.hlsl"
add r0.xyzw, v0.xyxy, l(-0.500000, -0.500000, -0.500000, -0.500000)  // inVPos<0,1,0,1>

#line 575
mov r0.xyzw, r0.xyzw  // NScreenToClipCoordinate_screenToClipcoord_inPixelPosition<0,1,0,1>

#line 576
nop 
mov r0.xyzw, r0.xyzw  // inPixelPosition<0,1,0,1>

#line 72
div r0.xyzw, r0.xyzw, cb0[1].xyxy  // outClipPosition<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>

#line 73
mul r0.xyzw, r0.xyzw, l(2.000000, -2.000000, 2.000000, -2.000000)
add r0.xyzw, r0.xyzw, l(-1.000000, 1.000000, -1.000000, 1.000000)  // outClipPosition<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>

#line 576
mov r0.xyzw, r0.xyzw  // NScreenToClipCoordinate_screenToClipcoord_outClipPosition<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>
mov r0.xyzw, r0.xyzw  // NFetchVolFog_fetchFog_inClipPos<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>

#line 577
mov r1.x, v1.z  // NFetchVolFog_fetchFog_inViewZ<0>

#line 578
nop 
mov r0.xyzw, r0.xyzw  // inClipPos<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>
mov r1.x, r1.x  // inViewZ<0>

#line 18
nop 
mov r0.xyzw, r0.xyzw  // inClipPos<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>
mov r1.x, r1.x  // inViewZ<0>

#line 142
nop 
mov r0.xyzw, r0.xyzw  // inClipPos<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>
mov r1.y, r1.x  // inViewZ<0>

#line 50
nop 
mov r1.y, r1.y  // inViewZ<0>

#line 27
mov r1.z, cb2[25].x  // invLogFarDistance<0>

#line 30
log r1.y, r1.y
mul r1.y, r1.y, r1.z  // EncodeFogCameraZ<0:NaN:Inf>

#line 50
mov r1.y, r1.y  // zEncoded<0:NaN:Inf>

#line 51
max r1.y, r1.y, l(0.000000)
min r1.y, r1.y, l(1.000000)  // zEncoded<0:[0f,1f]>

#line 52
mul r1.y, r1.y, l(127.000000)  // zEncoded<0:[0f,127f]>

#line 56
mul r0.xyzw, r0.xyzw, l(0.014648, 0.123047, 0.014648, 0.123047)
add r0.xyzw, r0.xyzw, l(0.015625, 0.125000, 0.015625, 0.125000)  // uv<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>

#line 57
add r1.z, r1.y, l(1.000000)
max r1.z, r1.z, l(0.000000)
min r2.w, r1.z, l(127.000000)
mov r2.y, r1.y
round_ni r1.zw, r2.yyyw  // zInt<0:[0f,127f],1:[1f,127f]>

#line 59
div r1.zw, r1.zzzw, l(0.000000, 0.000000, 32.000000, 32.000000)
frc r2.xy, r1.zwzz
mul r2.xz, r2.xxyx, l(32.000000, 0.000000, 32.000000, 0.000000)  // layerOffset<0:[0f,32f],2:[0f,32f]>

#line 60
round_ni r2.yw, r1.zzzw  // layerOffset<1:[0f,3f],3:[0f,3f]>

#line 61
mul r2.xyzw, r2.xyzw, l(0.031250, 0.250000, 0.031250, 0.250000)
add r0.xyzw, r0.xyzw, r2.xyzw  // uv_lerp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 62
frc r2.xyzw, r1.yyyy  // zBlend<0:[0f,1f],1:[0f,1f],2:[0f,1f],3:[0f,1f]>

#line 63
sample_indexable(texture2d)(float,float,float,float) r3.xyzw, r0.xyxx, t12.xyzw, s11  // c0<0:Inf,1:Inf,2:Inf,3:Inf>

#line 64
sample_indexable(texture2d)(float,float,float,float) r0.xyzw, r0.zwzz, t12.xyzw, s11  // c1<0:Inf,1:Inf,2:Inf,3:Inf>

#line 65
mov r4.xyzw, -r2.xyzw
add r4.xyzw, r4.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
mul r3.xyzw, r3.xyzw, r4.xyzw
mul r0.xyzw, r0.xyzw, r2.xyzw
add r0.xyzw, r0.xyzw, r3.xyzw  // fogColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 69
mov r1.y, cb2[25].y  // normalizeFactor<0>

#line 70
mul r0.xyz, r0.xyzx, r1.yyyy  // fogColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 71
mov r0.xyz, r0.xyzx  // GetVolumetricFog2D<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
mov r0.w, r0.w  // GetVolumetricFog2D<3:NaN:Inf>

#line 142
mov r0.xyzw, r0.xyzw  // GetVolumetricFog<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 18
mov r0.xyzw, r0.xyzw  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 578
mov r0.xyzw, r0.xyzw  // NFetchVolFog_fetchFog_outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 15
nop 

#line 19
nop 

#line 155
mov r1.yzw, cb5[9].xxzy  // GetSunLightDirection<0,2,1>

#line 19
mov r1.yzw, r1.yyzw  // outLightDir<0,2,1>

#line 20
nop 

#line 173
nop 

#line 15
mov r1.yzw, r1.yyzw  // NGetSunLightParam_sun_outLightDir<0,2,1>

#line 565
nop 

#line 573
nop 

#line 273
nop 

#line 472
nop 

#line 480
nop 

#line 582
mov r2.xy, v1.xyxx  // NCalculate_computePrimitiveColor_inUv<0,1>

#line 580
mov r3.xyz, v2.xyzx  // NCalculate_computePrimitiveColor_inWorldPosition<0,1,2>

#line 581
mov r2.z, v2.w  // NCalculate_computePrimitiveColor_inWindDirectionAttenuation<0>

#line 587
mov r1.yzw, r1.yyzw  // NCalculate_computePrimitiveColor_inSunDirection<0,2,1>

#line 588
mov r0.xyzw, r0.xyzw  // NCalculate_computePrimitiveColor_inFogColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 600
nop 
mov r2.xy, r2.xyxx  // inUv<0,1>
mov r3.xyz, r3.xyzx  // inWorldPosition<0,1,2>
mov r2.z, r2.z  // inWindDirectionAttenuation<0>
mov r1.yzw, r1.yyzw  // inSunDirection<0,2,1>
mov r0.xyzw, r0.xyzw  // inFogColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 264
mov r4.w, l(78.125000)  // texelLength_x2<0: 78.125f>

#line 266
mov r5.xy, cb4[0].xyxx  // perlinMovement<0,1>

#line 268
mov r2.w, cb4[1].z  // foamVelocity<0>

#line 269
mul r5.zw, cb4[2].yyyy, l(0.000000, 0.000000, 0.620000, 0.890000)  // farProjectionScale<0:[-2.10975e+038f,2.10975e+038f],1:[-3.02851e+038f,3.02851e+038f]>

#line 270
mov r6.xyz, cb4[3].xyzx  // inSunDirectionFromAtmosphere<0,1,2>

#line 271
mov r7.xyz, cb4[4].xyzx  // tonemapParam<0,1,2>

#line 272
mov r3.w, cb4[4].w  // foamAmount<0>

#line 273
mov r6.w, cb4[5].x  // patchBlendBegin<0>

#line 274
mov r7.w, cb4[5].y  // patchBlendEnd<0>

#line 275
mov r8.x, cb4[5].z  // reflectionPower<0>

#line 276
mov r8.w, cb4[5].w  // specularIntensityModifier<0>

#line 277
mov r9.x, cb4[6].x  // sunsetSunriseStrenght<0>

#line 278
mov r8.y, cb4[6].y  // normalizationFactor<0>

#line 279
mov r8.z, cb4[6].z  // normalizationFactor2<0>

#line 280
mov r9.y, cb4[6].w  // cameraVelocity<0>

#line 281
mul r10.xyz, cb2[23].zzzz, cb4[7].xyzx  // inSunColor<0:Inf,1:Inf,2:Inf>

#line 284
nop 

#line 78
mov r11.xyz, cb2[20].xyzx  // GetEyePosition<0,1,2>

#line 284
mov r11.xyz, -r11.xyzx
add r3.xyz, r3.xyzx, r11.xyzx  // inEyeDirection<0:Inf,1:Inf,2:Inf>

#line 285
dp3 r9.z, r3.xyzx, r3.xyzx
rsq r9.z, r9.z
mul r3.xyz, r3.xyzx, r9.zzzz  // inEyeDirection<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 288
mov r6.w, -r6.w
add r6.w, r1.x, r6.w
div r6.w, r6.w, r7.w  // blendFactor<0:NaN:Inf>

#line 289
mov r6.w, -r6.w
add r6.w, r6.w, l(1.000000)
max r6.w, r6.w, l(0.000000)
min r6.w, r6.w, l(1.000000)  // blendFactor<0:[0f,1f]>

#line 291
mul r2.z, r2.z, l(0.650000)
add r2.z, r2.z, l(0.350000)
mul r2.z, r2.z, r6.w  // blendFactor<0:[-2.21184e+038f,2.21184e+038f]>

#line 293
div r6.w, r1.x, l(5000.000000)
mov r6.w, -r6.w
add r6.w, r6.w, l(1.000000)  // invertedCompletRange<0:[-6.80565e+034f,6.80565e+034f]>

#line 296
mul r9.zw, r2.xxxy, r5.zzzz  // uv0<0:Inf,1:Inf>

#line 297
mul r5.zw, r2.yyyx, r5.wwww  // uv1<0:Inf,1:Inf>

#line 298
sample_indexable(texture2d)(float,float,float,float) r11.xy, r9.zwzz, t1.xyzw, s10
mov r11.xy, r11.xyxx  // grad0<0:Inf,1:Inf>

#line 299
sample_indexable(texture2d)(float,float,float,float) r5.zw, r5.zwzz, t1.zwxy, s10
mov r5.zw, r5.zzzw  // grad1<0:Inf,1:Inf>

#line 300
mul r11.xy, r11.xyxx, l(0.650000, 0.650000, 0.000000, 0.000000)
mul r5.zw, r5.zzzw, l(0.000000, 0.000000, 0.350000, 0.350000)
add r5.zw, r5.zzzw, r11.xxxy  // gradFar<0:NaN:Inf,1:NaN:Inf>

#line 303
sample_indexable(texture2d)(float,float,float,float) r11.xyzw, v1.xyxx, t1.wxyz, s10  // grad<3:Inf,0:Inf,1:Inf,2:Inf>

#line 307
mul r12.xy, r5.zwzz, cb4[2].zzzz
mov r12.zw, -r12.xxxy
add r12.zw, r11.yyyz, r12.zzzw
mul r12.zw, r2.zzzz, r12.zzzw
add r12.xz, r12.zzwz, r12.xxyx  // specularGrad<0:NaN:Inf,1:NaN:Inf>

#line 308
mul r5.zw, r5.zzzw, l(0.000000, 0.000000, 0.100000, 0.100000)
mul r13.xy, r6.wwww, r5.zwzz
mov r13.z, l(0)
mov r14.xyz, -r13.xyzx
add r11.yzw, r11.yyzw, r14.xxyz
mul r11.yzw, r2.zzzz, r11.yyzw
add r4.xyz, r11.yzwy, r13.xyzx  // grad<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 318
dp3 r2.z, r4.xywx, r4.xywx
rsq r2.z, r2.z
mul r4.xyw, r2.zzzz, r4.xwxy  // normal<0:NaN:Inf,1:NaN,2:NaN:Inf>

#line 320
mov r12.y, l(78.125000)
dp3 r2.z, r12.xyzx, r12.xyzx
rsq r2.z, r2.z
mul r11.yzw, r2.zzzz, r12.xxyz  // specularNormal<0:NaN:Inf,1:NaN,2:NaN:Inf>

#line 325
nop 
add r5.zw, r5.xxxy, r9.zzzw
mul r5.zw, r5.zzzw, l(0.000000, 0.000000, 0.400000, 0.400000)
sample_indexable(texture2d)(float,float,float,float) r5.zw, r5.zwzz, t4.xzyw, s12
mov r5.zw, r5.zzzw  // color<1:Inf,3:Inf>

#line 201
mul r5.zw, r5.zzzw, l(0.000000, 0.000000, 2.000000, 2.000000)
add r12.xz, r5.zzwz, l(-1.000000, 0.000000, -1.000000, 0.000000)  // normal<1:Inf,0:Inf>

#line 207
mul r2.z, r12.z, r12.z
mov r2.z, -r2.z
add r2.z, r2.z, l(1.000000)
mul r5.z, r12.x, r12.x
mov r5.z, -r5.z
add r2.z, r2.z, r5.z
max r2.z, r2.z, l(0.000000)
min r2.z, r2.z, l(1.000000)
add r2.z, r2.z, l(0.000100)  // tmp<0:[0.0001f,1.0001f]>

#line 213
rsq r5.z, r2.z
mul r12.y, r2.z, r5.z  // normal<2:[9.9995e-005f,100.01f]>

#line 216
mov r12.xz, r12.xxzx  // DecodeNormalTexture<1:Inf,0:Inf>
mov r12.y, r12.y  // DecodeNormalTexture<2:[9.9995e-005f,100.01f]>

#line 325
mov r12.xyz, r12.xyzx  // normalFar<0:Inf,1:[9.9995e-005f,100.01f],2:Inf>

#line 326
mul r2.z, r6.w, l(0.650000)
max r2.z, r2.z, l(0.000000)
min r2.z, r2.z, l(1.000000)
mov r13.xyz, -r12.xyzx
add r11.yzw, r11.yyzw, r13.xxyz
mul r11.yzw, r2.zzzz, r11.yyzw
add r11.yzw, r11.yyzw, r12.xxyz  // specularNormal<0:NaN:Inf,1:NaN,2:NaN:Inf>

#line 337
add r2.z, r1.x, l(-100.000000)
div r5.z, r2.z, l(100.000000)
max r5.z, r5.z, l(0.000000)
min r12.w, r5.z, l(1.000000)  // closeRange<0:[0f,1f]>

#line 339
mov r13.xyz, -r3.xyzx
dp3 r5.z, r4.xywx, r13.xyzx  // NV<0:NaN:Inf>

#line 340
dp3 r5.w, r3.xyzx, r11.yzwy
add r5.w, r5.w, r5.w
mov r5.w, -r5.w
mul r14.xyz, r5.wwww, r11.yzwy
add r14.xyz, r3.xyzx, r14.xyzx  // R<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 343
mul r9.zw, r2.xxxy, l(0.000000, 0.000000, 0.200000, 0.200000)
add r9.zw, r5.xxxy, r9.zzzw
sample_indexable(texture2d)(float,float,float,float) r15.xyz, r9.zwzz, t3.xyzw, s12
mov r15.xyz, r15.xyzx  // noise<0:Inf,1:Inf,2:Inf>

#line 347
mov r5.w, -r5.z
max r5.z, r5.w, r5.z
mul r5.z, r5.z, r6.w  // fNdotE<0:NaN:Inf>

#line 348
mov r5.z, -r5.z
add r5.z, r5.z, l(1.000100)  // facing<0:NaN:Inf>

#line 350
mul r5.w, r6.w, l(8.000000)  // fresnelPower<0:[-5.44452e+035f,5.44452e+035f]>

#line 351
log r5.z, r5.z
mul r5.z, r5.z, r5.w
exp r5.z, r5.z
mul r5.z, r5.z, l(0.950000)
add r5.z, r5.z, l(0.050000)
max r5.z, r5.z, l(0.000000)
min r16.xyz, r5.zzzz, l(1.000000, 1.000000, 1.000000, 0.000000)  // fresnel<0:[0f,1f],0:[0f,1f],0:[0f,1f]>

#line 354
dp3 r5.z, r1.ywzy, r14.xyzx
max r5.z, r5.z, l(0.000000)
min r5.z, r5.z, l(1.000000)  // LdotR<0:[0f,1f]>

#line 357
mul r5.w, r8.x, l(2.000000)  // glossinessK<1:Inf>
mov r8.xyz, r8.xyzx  // glossinessK<0,2,3>

#line 358
log r5.z, r5.z
mul r7.w, r5.z, r8.x
exp r14.x, r7.w
mul r5.z, r5.z, r5.w
exp r14.y, r5.z
dp2 r5.z, r8.yzyy, r14.xyxx  // specularIntensity<0:NaN:Inf>

#line 359
div r5.w, r2.z, l(500.000000)
max r5.w, r5.w, l(0.000000)
min r5.w, r5.w, l(1.000000)  // depthLessThanMiddleDistanceBlend<0:[0f,1f]>

#line 360
mov r7.w, -r9.y
max r7.w, r7.w, r9.y
mul r7.w, r7.w, l(1000.000000)
mov r7.w, -r7.w
add r7.w, r7.w, l(1.000000)
max r7.w, r7.w, l(0.500000)  // cameraVelocity<0:[0.5f,1f]>

#line 361
mul r8.x, r15.z, l(0.500000)
mul r5.w, r5.w, r8.x
mul r5.w, r7.w, r5.w
mul r5.z, r5.w, r5.z  // specularIntensity<0:NaN:Inf>

#line 364
div r5.w, r1.x, l(2500.000000)
mov r5.w, -r5.w
add r5.w, r5.w, l(1.000000)
max r5.w, r5.w, l(0.000000)
min r5.w, r5.w, l(1.000000)  // depthMiddleDistanceInvertedBlend<0:[0f,1f]>

#line 365
mul r7.w, r5.w, l(0.200000)
mov r8.xyz, -r6.xyzx
add r8.xyz, r1.ywzy, r8.xyzx
mul r8.xyz, r7.wwww, r8.xyzx
add r8.xyz, r6.xyzx, r8.xyzx
dp3 r6.x, r8.xyzx, r8.xyzx
rsq r6.x, r6.x
mul r8.xyz, r6.xxxx, r8.xyzx  // sunDirectionExtendedToHorizon<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 367
mul r6.x, r6.w, l(0.150000)
add r6.x, r6.x, l(0.025000)
add r9.yzw, r11.yyzw, l(0.000000, -0.000000, -1.000000, -0.000000)
mul r6.xzw, r6.xxxx, r9.yyzw
add r6.xzw, r6.xxzw, l(0.000000, 0.000000, 1.000000, 0.000000)
dp3 r7.w, r6.xzwx, r6.xzwx
rsq r7.w, r7.w
mul r6.xzw, r6.xxzw, r7.wwww
dp3 r7.w, r3.xyzx, r6.xzwx
add r7.w, r7.w, r7.w
mov r7.w, -r7.w
mul r6.xzw, r6.xxzw, r7.wwww
add r6.xzw, r3.xxyz, r6.xxzw  // R<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 368
dp3 r6.z, r8.xyzx, r6.xzwx
max r6.z, r6.z, l(0.000000)
min r6.z, r6.z, l(1.000000)  // LdotR<0:[0f,1f]>

#line 370
mul r7.w, r6.z, r6.z
mul r8.x, r7.w, l(1.000000)
mul r7.w, r7.w, r7.w
mul r7.w, r7.w, r8.x
mul r7.w, r7.w, l(1.273240)
mul r7.w, r9.x, r7.w
add r5.z, r5.z, r7.w  // specularIntensity<0:NaN:Inf>

#line 372
log r6.z, r6.z
mul r6.z, r6.z, l(5000.000000)
exp r6.z, r6.z
mul r6.z, r6.z, l(796.093323)
mul r6.z, r9.x, r6.z
mul r6.z, r6.z, l(0.250000)
add r5.z, r5.z, r6.z  // specularIntensity<0:NaN:Inf>

#line 374
mul r8.xyz, r5.zzzz, r10.xyzx  // specularContribution<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 377
dp3 r5.z, r8.xyzx, l(0.333000, 0.333000, 0.333000, 0.000000)  // temp<0:NaN:Inf>

#line 378
mul r5.z, r5.z, r5.z
max r5.z, r5.z, l(0.000000)
min r5.z, r5.z, l(1.000000)
mul r8.xyz, r5.zzzz, r8.xyzx  // specularContribution<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 381
mov r9.xyz, r16.zzzz
mul r8.xyz, r8.xyzx, r9.xyzx  // specularContribution<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 383
mul r8.xyz, r8.wwww, r8.xyzx  // specularContribution<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 385
mul r8.xyz, r8.xyzx, l(1.050000, 1.050000, 1.050000, 0.000000)  // specularContribution<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 389
add r5.z, r6.y, l(-0.040000)
mul r5.z, r5.z, l(14.000000)
add r5.z, r5.z, l(1.000000)
max r5.z, r5.z, l(0.000000)
min r5.z, r5.z, l(1.000000)
add r6.y, r6.y, l(0.240000)
mul r6.y, r6.y, l(14.000000)
mov r6.y, -r6.y
add r6.y, r6.y, l(1.000000)
max r6.y, r6.y, l(0.000000)
min r6.y, r6.y, l(1.000000)
mul r6.y, r6.y, l(0.500000)
add r5.z, r5.z, r6.y  // dayAndNightTransition<0:[0f,1.5f]>

#line 390
mul r5.z, r5.z, r5.z  // dayAndNightTransition<0:[0f,2.25f]>

#line 391
mul r8.xyz, r5.zzzz, r8.xyzx  // specularContribution<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 397
mul r5.z, r15.x, l(0.500000)
max r5.z, r5.z, l(0.000000)
min r5.z, r5.z, l(1.000000)  // rate<0:[0f,1f]>

#line 398
mul r9.xyz, r5.zzzz, l(-0.075000, -0.090000, -0.060000, 0.000000)
add r9.xyz, r9.xyzx, l(0.135000, 0.195000, 0.255000, 0.000000)  // compositedColor<0:[0.06f,0.135f],1:[0.105f,0.195f],2:[0.195f,0.255f]>

#line 401
div r5.z, l(0.000100), cb2[23].z
max r5.z, r5.z, l(0.000000)
min r5.z, r5.z, l(1.000000)
max r5.z, r5.z, l(0.350000)  // exposureAdaptation<0:[0.35f,1f]>

#line 402
mul r9.xyz, r5.zzzz, r9.xyzx  // compositedColor<0:[0.021f,0.135f],1:[0.03675f,0.195f],2:[0.06825f,0.255f]>

#line 404
mov r3.y, r1.w
dp3 r6.y, r3.xyzx, r3.xyzx
rsq r6.y, r6.y
mul r3.xyz, r3.xyzx, r6.yyyy  // eyeDir<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 405
dp3 r3.x, r3.xzyx, r1.yzwy
max r3.x, r3.x, l(0.000000)
min r3.xyz, r3.xxxx, l(1.000000, 1.000000, 1.000000, 0.000000)  // colorBlendRate<0:[0f,1f],0:[0f,1f],0:[0f,1f]>

#line 406
dp3 r6.y, r10.xyzx, r10.xyzx
rsq r6.y, r6.y
mul r11.yzw, r6.yyyy, r10.xxyz
add r11.yzw, r11.yyzw, l(0.000000, -0.350000, -0.350000, -0.350000)
mul r3.xyz, r3.xyzx, r11.yzwy
add r3.xyz, r3.xyzx, l(0.350000, 0.350000, 0.350000, 0.000000)  // sunFactor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 407
mul r9.xyz, r3.xyzx, r9.xyzx  // compositedColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 409
mul r9.xyz, r9.xyzx, l(0.096000, 0.200000, 0.380000, 0.000000)  // ambientColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 412
mul r11.yzw, r12.wwww, l(0.000000, -0.075000, 0.025000, 0.025000)
add r11.yzw, r11.yyzw, l(0.000000, 0.135000, 0.195000, 0.255000)  // skyReflectionColor1<0:[0.06f,0.135f],1:[0.195f,0.22f],2:[0.255f,0.28f]>

#line 413
div r6.yz, r2.xxyx, l(0.000000, 10.000000, 10.000000, 0.000000)
mul r14.xy, r1.xxxx, r4.xwxx
div r14.xy, r14.xyxx, l(75.000000, 75.000000, 0.000000, 0.000000)
add r6.yz, r6.yyzy, r14.xxyx  // waterDepthUv<0:NaN:Inf,1:NaN:Inf>

#line 414
sample_indexable(texture2d)(float,float,float,float) r1.x, r6.yzyy, t2.zxyw, s10
mul r1.x, r5.w, r1.x  // waterDepthTexColor<2:NaN:Inf>

#line 415
mul r1.x, r1.x, r1.x
mul r1.x, r1.x, l(400.000000)
max r1.x, r1.x, l(0.000000)
min r1.x, r1.x, l(1.000000)  // rate<0:[0f,1f]>

#line 416
add r11.yzw, r11.yyzw, l(0.000000, -0.060000, -0.105000, -0.195000)
mul r11.yzw, r1.xxxx, r11.yyzw
add r11.yzw, r11.yyzw, l(0.000000, 0.060000, 0.105000, 0.195000)  // skyReflectionColor<0:[0.06f,0.135f],1:[0.105f,0.22f],2:[0.195f,0.28f]>

#line 417
mul r11.yzw, r5.zzzz, r11.yyzw  // skyReflectionColor<0:[0.021f,0.135f],1:[0.03675f,0.22f],2:[0.06825f,0.28f]>

#line 418
mul r3.xyz, r3.xyzx, r11.yzwy  // skyReflectionColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 419
dp3 r1.x, l(0.000000, 1.000000, 0.000000, 0.000000), r13.xyzx
mul r1.x, r1.x, l(5.000000)
add r1.x, r1.x, l(3.000000)  // skyReflectionIntensity<0:NaN:Inf>

#line 443
mov r5.z, -r3.w
add r5.z, r5.z, l(1.000000)
max r5.z, r5.z, l(0.000000)
min r5.z, r5.z, l(1.000000)
mul r5.z, r5.z, l(10.000000)
add r5.z, r5.z, l(1.000000)  // foamIntensity<0:[1f,11f]>

#line 445
mul r5.xy, r2.wwww, r5.xyxx
mul r5.xy, r5.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000)
add r2.xy, r2.xyxx, r5.xyxx
sample_indexable(texture2d)(float,float,float,float) r2.x, r2.xyxx, t5.yxzw, s10
mov r2.x, r2.x  // foamSample<1:Inf>

#line 447
div r2.y, r2.z, l(1500.000000)
max r2.y, r2.y, l(0.000000)
min r2.y, r2.y, l(1.000000)  // depthLessThanMiddleDistanceBlend<0:[0f,1f]>

#line 448
add r2.z, r2.y, r3.w
add r2.z, r2.z, l(0.100000)
max r2.z, r2.z, l(0.000000)
min r2.z, r2.z, l(1.000000)
add r2.w, r15.y, l(-1.000000)
mul r2.z, r2.w, r2.z
add r2.z, r2.z, l(1.000000)  // foamAmount<0:NaN:Inf>

#line 450
mov r11.x, r11.x  // foamXMask<0:Inf>

#line 451
mul r2.w, r4.z, r4.z  // gradzPowered<0:NaN:Inf>

#line 452
mul r2.w, r2.w, r2.w  // gradzPowered<0:NaN:Inf>

#line 454
mul r2.z, r15.x, r2.z
mul r2.x, r2.x, r2.z
mul r2.x, r11.x, r2.x
mul r2.x, r2.x, l(2.000000)  // farFoamIntensity<0:NaN:Inf>

#line 455
mul r2.y, r2.y, r2.x
mov r2.y, -r2.y
add r2.x, r2.y, r2.x  // farFoamIntensity<0:NaN:Inf>

#line 468
mul r2.x, r2.x, r5.z  // foamIntensity<0:NaN:Inf>

#line 470
mul r2.x, r2.x, l(0.500000)  // foamIntensity<0:NaN:Inf>

#line 471
mul r5.xyz, r10.xyzx, l(0.150000, 0.150000, 0.150000, 0.000000)
add r5.xyz, r9.xyzx, r5.xyzx
add r5.xyz, r5.xyzx, l(0.050000, 0.050000, 0.050000, 0.000000)  // foamColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 475
dp3 r1.w, r4.xwyx, r1.yzwy  // NL<0:NaN:Inf>

#line 476
mov r2.y, -r1.w
max r1.w, r1.w, r2.y  // sssIntensity<0:NaN:Inf>

#line 477
dp2 r1.y, r1.yzyy, r6.xwxx
mov r1.z, -r1.y
max r1.y, r1.z, r1.y
add r1.y, r1.y, r1.w  // sssIntensity<0:NaN:Inf>

#line 478
mul r1.y, r1.y, l(0.500000)  // sssIntensity<0:NaN:Inf>

#line 482
mul r1.z, r2.w, l(0.250000)
mul r1.y, r1.z, r1.y  // sssIntensity<0:NaN:Inf>

#line 487
mul r1.yzw, r10.xxyz, r1.yyyy
mul r1.yzw, r1.yyzw, l(0.000000, 0.008750, 0.031500, 0.015750)  // sssContribution<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 501
mul r2.y, r2.x, l(12.000000)
mov r2.y, -r2.y
add r2.y, r2.y, l(1.000000)
max r2.y, r2.y, l(0.000000)
min r2.y, r2.y, l(1.000000)
mul r2.yzw, r2.yyyy, r8.xxyz
mul r4.xyz, r9.xyzx, l(1.850000, 1.850000, 1.850000, 0.000000)
mul r3.xyz, r1.xxxx, r3.xyzx
mov r6.xyz, -r4.xyzx
add r3.xyz, r3.xyzx, r6.xyzx
mul r3.xyz, r3.xyzx, r16.xyzx
add r3.xyz, r3.xyzx, r4.xyzx
add r3.xyz, r3.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
add r1.xyz, r1.yzwy, r3.xyzx
mul r3.xyz, r2.xxxx, r5.xyzx
add r1.xyz, r1.xyzx, r3.xyzx
mul r1.xyz, r1.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
add r1.xyz, r1.xyzx, r2.yzwy  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 505
mul r1.xyz, r0.wwww, r1.xyzx
add r0.xyz, r0.xyzx, r1.xyzx  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 508
nop 
mov r7.xyz, r7.xyzx  // params<0,1,2>
mov r0.xyz, r0.xyzx  // x<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 11
mov r1.xyz, r7.yyyy
ge r1.xzw, r1.xxyz, r0.xxyz
movc r1.xzw, r1.xxzw, l(1.000000,0,1.000000,1.000000), l(0,0,0,0)  // mask<0:[-0f,1f],1:[-0f,1f],2:[-0f,1f]>

#line 12
mul r2.xyz, r0.xyzx, r1.xzwx
mov r1.xzw, -r1.xxzw
add r1.xzw, r1.xxzw, l(1.000000, 0.000000, 1.000000, 1.000000)
add r0.xyz, r7.zzzz, r0.xyzx
mov r3.xyz, -r1.yyyy
add r0.xyz, r0.xyzx, r3.xyzx
mul r0.xyz, r0.xyzx, r7.xxxx
div r0.xyz, l(-1.000000, -1.000000, -1.000000, 0.000000), r0.xyzx
add r0.xyz, r7.zzzz, r0.xyzx
add r0.xyz, r1.yyyy, r0.xyzx
mul r0.xyz, r0.xyzx, r1.xzwx
add r0.xyz, r0.xyzx, r2.xyzx  // TppTonemap<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 508
mov r0.xyz, r0.xyzx  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 511
nop 
mov r0.xyz, r0.xyzx  // linearRGB<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 24
ge r1.xyz, l(0.003131, 0.003131, 0.003131, 0.000000), r0.xyzx
movc r1.xyz, r1.xyzx, l(1.000000,1.000000,1.000000,0), l(0,0,0,0)  // mask<0:[-0f,1f],1:[-0f,1f],2:[-0f,1f]>

#line 25
mul r2.xyz, r0.xyzx, l(12.920000, 12.920000, 12.920000, 0.000000)
mul r2.xyz, r1.xyzx, r2.xyzx
mov r1.xyz, -r1.xyzx
add r1.xyz, r1.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
max r0.xyz, r0.xyzx, l(0.000010, 0.000010, 0.000010, 0.000000)
log r0.xyz, r0.xyzx
mul r0.xyz, r0.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
exp r0.xyz, r0.xyzx
mul r0.xyz, r0.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000)
add r0.xyz, r0.xyzx, l(-0.055000, -0.055000, -0.055000, 0.000000)
mul r0.xyz, r0.xyzx, r1.xyzx
add r0.xyz, r0.xyzx, r2.xyzx  // GammaCorrection<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 511
mov r0.xyz, r0.xyzx  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 517
mov r12.w, r12.w  // outColor<3:[0f,1f]>

#line 521
mul r12.xyz, r0.xyzx, r12.wwww  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 600
mov r12.xyz, r12.xyzx  // NCalculate_computePrimitiveColor_outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
mov r12.w, r12.w  // NCalculate_computePrimitiveColor_outColor<3:[0f,1f]>

#line 602
mov o0.xyzw, r12.xyzw  // outColor0<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:[0f,1f]>

#line 604
mov o1.xyzw, r12.xyzw  // outColor1<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:[0f,1f]>

#line 527
ret 
// Approximately 448 instruction slots used
