Microsoft (R) Direct3D Shader Compiler 10.1
Copyright (C) 2013 Microsoft. All rights reserved.

//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer cPSMaterial
// {
//
//   struct PSMaterial
//   {
//       
//       float4 m_materials[8];         // Offset:    0
//
//   } g_psMaterial;                    // Offset:    0 Size:   128
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// inTextureSampler                  sampler      NA          NA             s0      1 
// inTexture                         texture  float4          2d             t0      1 
// cPSMaterial                       cbuffer      NA          NA            cb4      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xy          0     NONE   float   xy  
// TEXCOORD                 3     z         0     NONE   float       
// TEXCOORD                 1   xyzw        1     NONE   float   xyz 
// TEXCOORD                 2   xyzw        2     NONE   float   xy  
// SV_Position              0   xyzw        3      POS   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xyzw        1   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB4[1], immediateIndexed
dcl_sampler s0, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_input_ps linear v0.xy
dcl_input_ps linear v1.xyz
dcl_input_ps linear v2.xy
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_temps 5

#line 227 "d:\work\master\git_clone\_intermediate\win64\TppShaders_dx11_win64\Release\Prim_Poly_FastDraw_SSky_ps.hlsl"
mov r0.xyz, v1.xyzx  // NComputePrimitiveColorFastDraw_computePrimitiveColor_inColor<0,1,2>

#line 230
mov r1.xy, v2.xyxx  // NComputePrimitiveColorFastDraw_computePrimitiveColor_inParams<0,1>

#line 231
nop 
mov r0.xyz, r0.xyzx  // inColor<0,1,2>
mov r1.xy, r1.xyxx  // inParams<0,1>

#line 167
sample_indexable(texture2d)(float,float,float,float) r2.xyzw, v0.xyxx, t0.xyzw, s0  // c0<0:Inf,1:Inf,2:Inf,3:Inf>

#line 174
div r2.xyz, r2.xyzx, r2.wwww  // c0<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 175
mul r0.xyz, r0.xyzx, r2.xyzx  // c0<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 176
nop 
mov r1.xy, r1.xyxx  // params<0,1>

#line 441
mul r0.w, r1.y, r1.x  // GetPrecalculatedLuminance<0:Inf>

#line 176
mul r0.xyz, r0.wwww, r0.xyzx  // c0<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 179
max r0.xyz, r0.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
min r0.xyz, r0.xyzx, l(154.600006, 154.600006, 154.600006, 0.000000)  // c0<0:[-0f,154.6f],1:[-0f,154.6f],2:[-0f,154.6f]>

#line 180
log r0.xyz, r0.xyzx
mul r0.xyz, r0.xyzx, l(2.200000, 2.200000, 2.200000, 0.000000)
exp r0.xyz, r0.xyzx  // outColor<0:[0f,65503f],1:[0f,65503f],2:[0f,65503f]>

#line 231
mov r0.xyz, r0.xyzx  // NComputePrimitiveColorFastDraw_computePrimitiveColor_outColor<0:[0f,65503f],1:[0f,65503f],2:[0f,65503f]>

#line 237
mov r0.xyz, r0.xyzx  // NCalcVolumeFogColorSSky_calcFogColor_inColor<0:[0f,65503f],1:[0f,65503f],2:[0f,65503f]>
nop 
mov r0.xyz, r0.xyzx  // inColor<0:[0f,65503f],1:[0f,65503f],2:[0f,65503f]>

#line 149
mov r0.xyz, r0.xyzx  // outColor<0:[0f,65503f],1:[0f,65503f],2:[0f,65503f]>

#line 237
mov r0.xyz, r0.xyzx  // NCalcVolumeFogColorSSky_calcFogColor_outColor<0:[0f,65503f],1:[0f,65503f],2:[0f,65503f]>

#line 247
nop 

#line 510
nop 

#line 128
nop 

#line 240
mov r0.xyz, r0.xyzx  // NTppTonemap_tonemap_inColor<0:[0f,65503f],1:[0f,65503f],2:[0f,65503f]>

#line 241
nop 
mov r0.xyz, r0.xyzx  // inColor<0:[0f,65503f],1:[0f,65503f],2:[0f,65503f]>

#line 193
nop 
mov r1.xyz, cb4[0].xyzx  // params<0,1,2>
mov r0.xyz, r0.xyzx  // x<0:[0f,65503f],1:[0f,65503f],2:[0f,65503f]>

#line 11
mov r2.xyz, r1.yyyy
ge r2.xzw, r2.xxyz, r0.xxyz
movc r2.xzw, r2.xxzw, l(1.000000,0,1.000000,1.000000), l(0,0,0,0)  // mask<0:[-0f,1f],1:[-0f,1f],2:[-0f,1f]>

#line 12
mul r3.xyz, r0.xyzx, r2.xzwx
mov r2.xzw, -r2.xxzw
add r2.xzw, r2.xxzw, l(1.000000, 0.000000, 1.000000, 1.000000)
add r0.xyz, r1.zzzz, r0.xyzx
mov r4.xyz, -r2.yyyy
add r0.xyz, r0.xyzx, r4.xyzx
mul r0.xyz, r0.xyzx, r1.xxxx
div r0.xyz, l(-1.000000, -1.000000, -1.000000, 0.000000), r0.xyzx
add r0.xyz, r1.zzzz, r0.xyzx
add r0.xyz, r2.yyyy, r0.xyzx
mul r0.xyz, r0.xyzx, r2.xzwx
add r0.xyz, r0.xyzx, r3.xyzx  // TppTonemap<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 193
mov r0.xyz, r0.xyzx  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 241
mov r0.xyz, r0.xyzx  // NTppTonemap_tonemap_outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 243
mov r0.xyz, r0.xyzx  // NGammaEncodeF3_gammaEncode_inColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 244
nop 
mov r0.xyz, r0.xyzx  // inColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 17
nop 
mov r0.xyz, r0.xyzx  // linearRGB<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 24
ge r1.xyz, l(0.003131, 0.003131, 0.003131, 0.000000), r0.xyzx
movc r1.xyz, r1.xyzx, l(1.000000,1.000000,1.000000,0), l(0,0,0,0)  // mask<0:[-0f,1f],1:[-0f,1f],2:[-0f,1f]>

#line 25
mul r2.xyz, r0.xyzx, l(12.920000, 12.920000, 12.920000, 0.000000)
mul r2.xyz, r1.xyzx, r2.xyzx
mov r1.xyz, -r1.xyzx
add r1.xyz, r1.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
max r0.xyz, r0.xyzx, l(0.000010, 0.000010, 0.000010, 0.000000)
log r0.xyz, r0.xyzx
mul r0.xyz, r0.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
exp r0.xyz, r0.xyzx
mul r0.xyz, r0.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000)
add r0.xyz, r0.xyzx, l(-0.055000, -0.055000, -0.055000, 0.000000)
mul r0.xyz, r0.xyzx, r1.xyzx
add r0.xyz, r0.xyzx, r2.xyzx  // GammaCorrection<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 17
mov r0.xyz, r0.xyzx  // outColorSRGB<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 244
mov r0.xyz, r0.xyzx  // NGammaEncodeF3_gammaEncode_outColorSRGB<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 248
mov r0.xyz, r0.xyzx  // NCalcPremultipliedAlpha_calcPremultipliedAlpha_inColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 250
nop 
mov r0.xyz, r0.xyzx  // inColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 311
mov r0.xyz, r0.xyzx  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 316
mul r0.xyz, r0.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 250
mov r0.xyz, r0.xyzx  // NCalcPremultipliedAlpha_calcPremultipliedAlpha_outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
mov r0.w, l(1.000000)  // NCalcPremultipliedAlpha_calcPremultipliedAlpha_outColor<3: 1f>

#line 251
mov o0.xyzw, r0.xyzw  // outColor0<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3: 1f>

#line 255
mov o1.xyzw, r0.xyzw  // outColor1<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3: 1f>

#line 203
ret 
// Approximately 80 instruction slots used
