Microsoft (R) Direct3D Shader Compiler 10.1
Copyright (C) 2013 Microsoft. All rights reserved.

//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer cPSScene
// {
//
//   struct PSScene
//   {
//       
//       float4x4 m_projectionView;     // Offset:    0
//       float4x4 m_projection;         // Offset:   64
//       float4x4 m_view;               // Offset:  128
//       float4x4 m_shadowProjection;   // Offset:  192
//       float4x4 m_shadowProjection2;  // Offset:  256
//       float4 m_eyepos;               // Offset:  320
//       float4 m_projectionParam;      // Offset:  336
//       float4 m_viewportSize;         // Offset:  352
//       float4 m_exposure;             // Offset:  368
//       float4 m_fogParam[3];          // Offset:  384
//       float4 m_fogColor;             // Offset:  432
//       float4 m_cameraCenterOffset;   // Offset:  448
//       float4 m_shadowMapResolutions; // Offset:  464
//
//   } g_psScene;                       // Offset:    0 Size:   480
//
// }
//
// cbuffer cPSMaterial
// {
//
//   struct PSMaterial
//   {
//       
//       float4 m_materials[8];         // Offset:    0
//
//   } g_psMaterial;                    // Offset:    0 Size:   128
//
// }
//
// cbuffer cPSSystem
// {
//
//   struct PSSystem
//   {
//       
//       float4 m_param;                // Offset:    0
//       float4 m_renderInfo;           // Offset:   16
//       float4 m_renderBuffer;         // Offset:   32
//       float4 m_dominantLightDir;     // Offset:   48
//
//   } g_psSystem;                      // Offset:    0 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// g_samplerPoint_Clamp              sampler      NA          NA             s9      1 
// g_samplerLinear_Wrap              sampler      NA          NA            s10      1 
// g_samplerLinear_Clamp             sampler      NA          NA            s11      1 
// inWhitecapTexture1                texture  float4          2d             t2      1 
// g_tex_fog                         texture  float4          2d            t12      1 
// inDepthTexture                    texture  float4          2d            t13      1 
// cPSSystem                         cbuffer      NA          NA            cb0      1 
// cPSScene                          cbuffer      NA          NA            cb2      1 
// cPSMaterial                       cbuffer      NA          NA            cb4      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xy  
// TEXCOORD                 0   xyz         1     NONE   float   xyz 
// TEXCOORD                 1      w        1     NONE   float      w
// TEXCOORD                 3   xyz         2     NONE   float     z 
// TEXCOORD                 4   xyzw        3     NONE   float       
// TEXCOORD                 6   xyzw        4     NONE   float       
// TEXCOORD                 7   xyzw        5     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xyzw        1   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB2[26], immediateIndexed
dcl_constantbuffer CB4[5], immediateIndexed
dcl_constantbuffer CB0[3], immediateIndexed
dcl_sampler s9, mode_default
dcl_sampler s10, mode_default
dcl_sampler s11, mode_default
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t12
dcl_resource_texture2d (float,float,float,float) t13
dcl_input_ps_siv linear noperspective v0.xy, position
dcl_input_ps linear v1.xyz
dcl_input_ps linear v1.w
dcl_input_ps linear v2.z
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_temps 7

#line 46 "d:\work\master\git_clone\_intermediate\win64\TppShaders_dx11_win64\Release\Primitive_TppBaseOcean_ps.hlsl"
add r0.xyzw, v0.xyxy, l(-0.500000, -0.500000, -0.500000, -0.500000)  // inVPos<0,1,0,1>

#line 91
mov r1.xy, r0.zwzz  // NScreenToTextureCoordinate_screenToTexcoord_inPixelPosition<0,1>

#line 92
nop 
mov r1.xy, r1.xyxx  // inPixelPosition<0,1>

#line 56
add r1.xy, r1.xyxx, l(0.496094, 0.496094, 0.000000, 0.000000)
mul r1.xy, r1.xyxx, cb0[2].zwzz  // outTexcoord<0:Inf,1:Inf>

#line 92
mov r1.xy, r1.xyxx  // NScreenToTextureCoordinate_screenToTexcoord_outTexcoord<0:Inf,1:Inf>
mov r1.xy, r1.xyxx  // NGetPrimitiveDepthFactor_fetchViewZ_inBaseUV<0:Inf,1:Inf>

#line 93
nop 
mov r1.xy, r1.xyxx  // inBaseUV<0:Inf,1:Inf>

#line 273
nop 
mov r1.xy, r1.xyxx  // inTexCoord<0:Inf,1:Inf>
mov r1.zw, cb2[21].zzzw  // projectionParameter<2,3>

#line 467
sample_indexable(texture2d)(float,float,float,float) r1.x, r1.xyxx, t13.yxzw, s9
mov r1.x, r1.x  // fetchDepth<1:Inf>

#line 472
nop 

#line 480
nop 
mov r1.x, r1.x  // zOverW<0:Inf>
mov r1.zw, r1.zzzw  // proj<2,3>

#line 397
mov r1.y, -r1.w
add r1.x, r1.y, r1.x
div r1.x, r1.z, r1.x  // ReconstructViewZ<0:NaN:Inf>

#line 480
mov r1.x, r1.x  // depth<1:NaN:Inf>

#line 273
mov r1.x, r1.x  // outDepth<1:NaN:Inf>

#line 93
mov r1.x, r1.x  // NGetPrimitiveDepthFactor_fetchViewZ_outDepth<1:NaN:Inf>

#line 83
mov r1.yzw, v1.xxyz  // NGetEyeDir_getEyeDir_inWorldPosition<0,1,2>

#line 84
nop 
mov r1.yzw, r1.yyzw  // inWorldPosition<0,1,2>

#line 201
mov r2.xyz, -cb2[20].xyzx
add r1.yzw, r1.yyzw, r2.xxyz  // diff<0:Inf,1:Inf,2:Inf>

#line 202
dp3 r1.z, r1.yzwy, r1.yzwy
rsq r1.z, r1.z
mul r2.xz, r1.zzzz, r1.yywy  // outEyeDir<0:NaN:Inf,2:NaN:Inf>

#line 84
mov r2.xz, r2.xxzx  // NGetEyeDir_getEyeDir_outEyeDir<0:NaN:Inf,2:NaN:Inf>

#line 124
nop 

#line 71
nop 

#line 76
nop 

#line 77
nop 
nop 

#line 78
nop 

#line 116
nop 

#line 56
nop 

#line 61
nop 

#line 62
nop 
nop 

#line 63
nop 

#line 111
nop 

#line 41
nop 

#line 46
nop 

#line 47
nop 
nop 

#line 48
nop 

#line 106
nop 

#line 126
nop 

#line 33
nop 

#line 363
nop 

#line 364
nop 

#line 33
nop 

#line 15
nop 

#line 19
nop 

#line 20
nop 

#line 173
nop 

#line 98
mov r0.xyzw, r0.xyzw  // NScreenToClipCoordinate_screenToClipcoord_inPixelPosition<0,1,0,1>

#line 99
nop 
mov r0.xyzw, r0.xyzw  // inPixelPosition<0,1,0,1>

#line 72
div r0.xyzw, r0.xyzw, cb0[1].xyxy  // outClipPosition<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>

#line 73
mul r0.xyzw, r0.xyzw, l(2.000000, -2.000000, 2.000000, -2.000000)
add r0.xyzw, r0.xyzw, l(-1.000000, 1.000000, -1.000000, 1.000000)  // outClipPosition<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>

#line 99
mov r0.xyzw, r0.xyzw  // NScreenToClipCoordinate_screenToClipcoord_outClipPosition<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>
mov r0.xyzw, r0.xyzw  // NFetchVolFog_fetchFog_inClipPos<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>

#line 100
mov r1.y, v1.w  // NFetchVolFog_fetchFog_inViewZ<0>

#line 101
nop 
mov r0.xyzw, r0.xyzw  // inClipPos<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>
mov r1.y, r1.y  // inViewZ<0>

#line 18
nop 
mov r0.xyzw, r0.xyzw  // inClipPos<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>
mov r1.y, r1.y  // inViewZ<0>

#line 142
nop 
mov r0.xyzw, r0.xyzw  // inClipPos<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>
mov r1.y, r1.y  // inViewZ<0>

#line 50
nop 
mov r1.y, r1.y  // inViewZ<0>

#line 27
mov r1.z, cb2[25].x  // invLogFarDistance<0>

#line 30
log r1.y, r1.y
mul r1.y, r1.y, r1.z  // EncodeFogCameraZ<0:NaN:Inf>

#line 50
mov r1.y, r1.y  // zEncoded<0:NaN:Inf>

#line 51
max r1.y, r1.y, l(0.000000)
min r1.y, r1.y, l(1.000000)  // zEncoded<0:[0f,1f]>

#line 52
mul r1.y, r1.y, l(127.000000)  // zEncoded<0:[0f,127f]>

#line 56
mul r0.xyzw, r0.xyzw, l(0.014648, 0.123047, 0.014648, 0.123047)
add r0.xyzw, r0.xyzw, l(0.015625, 0.125000, 0.015625, 0.125000)  // uv<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>

#line 57
add r1.z, r1.y, l(1.000000)
max r1.z, r1.z, l(0.000000)
min r3.w, r1.z, l(127.000000)
mov r3.y, r1.y
round_ni r1.zw, r3.yyyw  // zInt<0:[0f,127f],1:[1f,127f]>

#line 59
div r1.zw, r1.zzzw, l(0.000000, 0.000000, 32.000000, 32.000000)
frc r3.xy, r1.zwzz
mul r3.xz, r3.xxyx, l(32.000000, 0.000000, 32.000000, 0.000000)  // layerOffset<0:[0f,32f],2:[0f,32f]>

#line 60
round_ni r3.yw, r1.zzzw  // layerOffset<1:[0f,3f],3:[0f,3f]>

#line 61
mul r3.xyzw, r3.xyzw, l(0.031250, 0.250000, 0.031250, 0.250000)
add r0.xyzw, r0.xyzw, r3.xyzw  // uv_lerp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 62
frc r3.xyzw, r1.yyyy  // zBlend<0:[0f,1f],1:[0f,1f],2:[0f,1f],3:[0f,1f]>

#line 63
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r0.xyxx, t12.xyzw, s11  // c0<0:Inf,1:Inf,2:Inf,3:Inf>

#line 64
sample_indexable(texture2d)(float,float,float,float) r0.xyzw, r0.zwzz, t12.xyzw, s11  // c1<0:Inf,1:Inf,2:Inf,3:Inf>

#line 65
mov r5.xyzw, -r3.xyzw
add r5.xyzw, r5.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
mul r4.xyzw, r4.xyzw, r5.xyzw
mul r0.xyzw, r0.xyzw, r3.xyzw
add r0.xyzw, r0.xyzw, r4.xyzw  // fogColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 69
mov r1.y, cb2[25].y  // normalizeFactor<0>

#line 70
mul r0.xyz, r0.xyzx, r1.yyyy  // fogColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 71
mov r0.xyz, r0.xyzx  // GetVolumetricFog2D<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
mov r0.w, r0.w  // GetVolumetricFog2D<3:NaN:Inf>

#line 142
mov r0.xyzw, r0.xyzw  // GetVolumetricFog<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 18
mov r0.xyzw, r0.xyzw  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 101
mov r0.xyzw, r0.xyzw  // NFetchVolFog_fetchFog_outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 127
mov r0.xyzw, r0.xyzw  // NComputeColor_computeColor_inFogColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 138
mov r2.xz, r2.xxzx  // NComputeColor_computeColor_inEyeDirection<0:NaN:Inf,2:NaN:Inf>

#line 151
mov r1.yz, v1.xxzx  // NComputeColor_computeColor_inWorldPos<0,2>

#line 146
nop 
mov r0.xyzw, r0.xyzw  // inFogColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mov r2.xz, r2.xxzx  // inEyeDirection<0:NaN:Inf,2:NaN:Inf>
mov r1.yz, r1.yyzy  // inWorldPos<0,2>

#line 389
mov r3.xyz, cb4[3].xyzx  // inSunDirection<0,1,2>

#line 391
mov r4.xyz, cb4[2].xyzx  // inSunColor<0,1,2>

#line 392
mov r5.xyz, cb4[4].xyzx  // tonemapParam<0,1,2>

#line 416
add r1.yz, r1.yyzy, l(0.000000, 0.000000, 0.000000, 0.000000)
div r1.yz, r1.yyzy, l(0.000000, 300.000000, 300.000000, 0.000000)  // waterDepthUv<0:[-1.13427e+036f,1.13427e+036f],1:[-1.13427e+036f,1.13427e+036f]>

#line 417
sample_indexable(texture2d)(float,float,float,float) r1.y, r1.yzyy, t2.xyzw, s10
mov r1.y, r1.y  // waterDepthTexColor<1:Inf>

#line 433
div r1.z, l(0.000100), cb2[23].z
max r1.z, r1.z, l(0.000000)
min r1.z, r1.z, l(1.000000)
max r1.z, r1.z, l(0.350000)  // exposureAdaptation<0:[0.35f,1f]>

#line 434
mul r6.xyz, r1.zzzz, l(0.260000, 0.280000, 0.340000, 0.000000)  // cubeMapColor<0:[0.091f,0.26f],1:[0.098f,0.28f],2:[0.119f,0.34f]>

#line 438
mov r2.y, l(0)
dp3 r1.z, r2.xyzx, r2.xyzx
rsq r1.z, r1.z
mul r2.xyz, r1.zzzz, r2.xyzx  // eyeDir<0:NaN:Inf,1: 0f,2:NaN:Inf>

#line 439
dp3 r1.z, r2.xyzx, r3.xyzx
add r1.z, r3.y, r1.z
max r1.z, r1.z, l(0.000000)
min r2.xyz, r1.zzzz, l(1.000000, 1.000000, 1.000000, 0.000000)  // colorBlendRate<0:[0f,1f],0:[0f,1f],0:[0f,1f]>

#line 440
dp3 r1.z, r4.xyzx, r4.xyzx
rsq r1.z, r1.z
mul r3.xyz, r1.zzzz, r4.xyzx
add r3.xyz, r3.xyzx, l(-0.250000, -0.250000, -0.250000, 0.000000)
mul r2.xyz, r2.xyzx, r3.xyzx
add r2.xyz, r2.xyzx, l(0.250000, 0.250000, 0.250000, 0.000000)  // sunColorAdaptation<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 441
mul r2.xyz, r2.xyzx, r6.xyzx  // cubeMapColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 445
mul r3.xyz, r2.xyzx, l(0.140000, 0.315000, 0.262500, 0.000000)  // baseColor1<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 446
mul r2.xyz, r2.xyzx, l(0.270000, 0.405000, 0.247500, 0.000000)  // baseColor2<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 449
mul r1.y, r1.y, l(10.000000)
max r1.y, r1.y, l(0.000000)
min r1.y, r1.y, l(1.000000)  // rate1<0:[0f,1f]>

#line 450
mov r1.z, -r1.y
add r1.z, r1.z, l(1.000000)  // rate2<0:[0f,1f]>

#line 451
mul r3.xyz, r1.yyyy, r3.xyzx
mul r1.yzw, r1.zzzz, r2.xxyz
add r1.yzw, r1.yyzw, r3.xxyz  // ambientColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 504
mul r1.yzw, r1.yyzw, l(0.000000, 0.850000, 0.850000, 0.850000)  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 507
mul r1.yzw, r0.wwww, r1.yyzw
add r0.xyz, r0.xyzx, r1.yzwy  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 510
nop 
mov r5.xyz, r5.xyzx  // params<0,1,2>
mov r0.xyz, r0.xyzx  // x<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 11
mov r1.yzw, r5.yyyy
ge r2.xyz, r1.yzwy, r0.xyzx
movc r2.xyz, r2.xyzx, l(1.000000,1.000000,1.000000,0), l(0,0,0,0)  // mask<0:[-0f,1f],1:[-0f,1f],2:[-0f,1f]>

#line 12
mul r3.xyz, r0.xyzx, r2.xyzx
mov r2.xyz, -r2.xyzx
add r2.xyz, r2.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
add r0.xyz, r5.zzzz, r0.xyzx
mov r4.xyz, -r1.zzzz
add r0.xyz, r0.xyzx, r4.xyzx
mul r0.xyz, r0.xyzx, r5.xxxx
div r0.xyz, l(-1.000000, -1.000000, -1.000000, 0.000000), r0.xyzx
add r0.xyz, r5.zzzz, r0.xyzx
add r0.xyz, r1.zzzz, r0.xyzx
mul r0.xyz, r0.xyzx, r2.xyzx
add r0.xyz, r0.xyzx, r3.xyzx  // TppTonemap<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 510
mov r0.xyz, r0.xyzx  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 513
nop 
mov r0.xyz, r0.xyzx  // linearRGB<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 24
ge r1.yzw, l(0.000000, 0.003131, 0.003131, 0.003131), r0.xxyz
movc r1.yzw, r1.yyzw, l(0,1.000000,1.000000,1.000000), l(0,0,0,0)  // mask<0:[-0f,1f],1:[-0f,1f],2:[-0f,1f]>

#line 25
mul r2.xyz, r0.xyzx, l(12.920000, 12.920000, 12.920000, 0.000000)
mul r2.xyz, r1.yzwy, r2.xyzx
mov r1.yzw, -r1.yyzw
add r1.yzw, r1.yyzw, l(0.000000, 1.000000, 1.000000, 1.000000)
max r0.xyz, r0.xyzx, l(0.000010, 0.000010, 0.000010, 0.000000)
log r0.xyz, r0.xyzx
mul r0.xyz, r0.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
exp r0.xyz, r0.xyzx
mul r0.xyz, r0.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000)
add r0.xyz, r0.xyzx, l(-0.055000, -0.055000, -0.055000, 0.000000)
mul r0.xyz, r0.xyzx, r1.yzwy
add r0.xyz, r0.xyzx, r2.xyzx  // GammaCorrection<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 513
mov r0.xyz, r0.xyzx  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 146
mov r0.xyz, r0.xyzx  // NComputeColor_computeColor_outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 95
mov r0.w, v2.z  // NComputeDepthComparisonFactor_computeDepthComparisonFactor_inDepth<0>

#line 96
mov r1.x, r1.x  // NComputeDepthComparisonFactor_computeDepthComparisonFactor_inSceneDepth<1:NaN:Inf>

#line 97
nop 
mov r0.w, r0.w  // inDepth<0>
mov r1.x, r1.x  // inSceneDepth<1:NaN:Inf>

#line 191
ge r0.w, r1.x, r0.w
movc r0.w, r0.w, l(1), l(0)
itof r0.w, r0.w  // outBlendFactor<1:[0f,1f]>

#line 97
mov r0.w, r0.w  // NComputeDepthComparisonFactor_computeDepthComparisonFactor_outBlendFactor<1:[0f,1f]>

#line 159
mov r0.w, r0.w  // NOutputColorBufferSoftBlender_finalBlender_inZBlendFactor<1:[0f,1f]>

#line 160
mov r0.xyz, r0.xyzx  // NOutputColorBufferSoftBlender_finalBlender_inColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 162
nop 
mov r0.w, r0.w  // inZBlendFactor<1:[0f,1f]>
mov r0.xyz, r0.xyzx  // inColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 258
mul r1.xyz, r0.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
mov r1.w, l(1.000000)  // outColor<3: 1f>

#line 260
mul r2.x, r0.w, l(1.000000)
mul r2.xyz, r0.xyzx, r2.xxxx  // outColorSub<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
mul r2.w, r0.w, l(1.000000)  // outColorSub<3:[0f,1f]>

#line 162
mov r1.xyzw, r1.xyzw  // NOutputColorBufferSoftBlender_finalBlender_outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3: 1f>
mov r2.xyzw, r2.xyzw  // NOutputColorBufferSoftBlender_finalBlender_outColorSub<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:[0f,1f]>

#line 164
mov o0.xyzw, r1.xyzw  // outColor0<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3: 1f>

#line 166
mov o1.xyzw, r2.xyzw  // outColor1<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:[0f,1f]>

#line 33
ret 
// Approximately 225 instruction slots used
