Microsoft (R) Direct3D Shader Compiler 10.1
Copyright (C) 2013 Microsoft. All rights reserved.

//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer cPSScene
// {
//
//   struct PSScene
//   {
//       
//       float4x4 m_projectionView;     // Offset:    0
//       float4x4 m_projection;         // Offset:   64
//       float4x4 m_view;               // Offset:  128
//       float4x4 m_shadowProjection;   // Offset:  192
//       float4x4 m_shadowProjection2;  // Offset:  256
//       float4 m_eyepos;               // Offset:  320
//       float4 m_projectionParam;      // Offset:  336
//       float4 m_viewportSize;         // Offset:  352
//       float4 m_exposure;             // Offset:  368
//       float4 m_fogParam[3];          // Offset:  384
//       float4 m_fogColor;             // Offset:  432
//       float4 m_cameraCenterOffset;   // Offset:  448
//       float4 m_shadowMapResolutions; // Offset:  464
//
//   } g_psScene;                       // Offset:    0 Size:   480
//
// }
//
// cbuffer cPSMaterial
// {
//
//   struct PSMaterial
//   {
//       
//       float4 m_materials[8];         // Offset:    0
//
//   } g_psMaterial;                    // Offset:    0 Size:   128
//
// }
//
// cbuffer cPSSystem
// {
//
//   struct PSSystem
//   {
//       
//       float4 m_param;                // Offset:    0
//       float4 m_renderInfo;           // Offset:   16
//       float4 m_renderBuffer;         // Offset:   32
//       float4 m_dominantLightDir;     // Offset:   48
//
//   } g_psSystem;                      // Offset:    0 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// g_samplerPoint_Clamp              sampler      NA          NA             s9      1 
// g_samplerLinear_Wrap              sampler      NA          NA            s10      1 
// g_samplerLinear_Clamp             sampler      NA          NA            s11      1 
// inWaveTexture                     texture  float4          2d             t0      1 
// inDistortionTexture               texture  float4          2d             t1      1 
// inWhitecapTexture1                texture  float4          2d             t2      1 
// inNoiseTexture                    texture  float4          2d             t3      1 
// g_tex_fog                         texture  float4          2d            t12      1 
// inDepthTexture                    texture  float4          2d            t13      1 
// cPSSystem                         cbuffer      NA          NA            cb0      1 
// cPSScene                          cbuffer      NA          NA            cb2      1 
// cPSMaterial                       cbuffer      NA          NA            cb4      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xy  
// TEXCOORD                 0   xyz         1     NONE   float   xyz 
// TEXCOORD                 1      w        1     NONE   float      w
// TEXCOORD                 3   xyz         2     NONE   float     z 
// TEXCOORD                 4   xyzw        3     NONE   float       
// TEXCOORD                 6   xyzw        4     NONE   float   xy  
// TEXCOORD                 7   xyzw        5     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xyzw        1   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB2[26], immediateIndexed
dcl_constantbuffer CB4[8], immediateIndexed
dcl_constantbuffer CB0[3], immediateIndexed
dcl_sampler s9, mode_default
dcl_sampler s10, mode_default
dcl_sampler s11, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t12
dcl_resource_texture2d (float,float,float,float) t13
dcl_input_ps_siv linear noperspective v0.xy, position
dcl_input_ps linear v1.xyz
dcl_input_ps linear v1.w
dcl_input_ps linear v2.z
dcl_input_ps linear v4.xy
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_temps 15

#line 556 "d:\work\master\git_clone\_intermediate\win64\TppShaders_dx11_win64\Release\Primitive_Tpp24hOcean_ps.hlsl"
add r0.xyzw, v0.xyxy, l(-0.500000, -0.500000, -0.500000, -0.500000)  // inVPos<0,1,0,1>

#line 601
mov r1.xy, r0.zwzz  // NScreenToTextureCoordinate_screenToTexcoord_inPixelPosition<0,1>

#line 602
nop 
mov r1.xy, r1.xyxx  // inPixelPosition<0,1>

#line 56
add r1.xy, r1.xyxx, l(0.496094, 0.496094, 0.000000, 0.000000)
mul r1.xy, r1.xyxx, cb0[2].zwzz  // outTexcoord<0:Inf,1:Inf>

#line 602
mov r1.xy, r1.xyxx  // NScreenToTextureCoordinate_screenToTexcoord_outTexcoord<0:Inf,1:Inf>
mov r1.xy, r1.xyxx  // NGetPrimitiveDepthFactor_fetchViewZ_inBaseUV<0:Inf,1:Inf>

#line 603
nop 
mov r1.xy, r1.xyxx  // inBaseUV<0:Inf,1:Inf>

#line 273
nop 
mov r1.xy, r1.xyxx  // inTexCoord<0:Inf,1:Inf>
mov r1.zw, cb2[21].zzzw  // projectionParameter<2,3>

#line 467
sample_indexable(texture2d)(float,float,float,float) r2.xy, r1.xyxx, t13.xyzw, s9
mov r2.xy, r2.xyxx  // fetchDepth<0:Inf,1:Inf>

#line 472
nop 
mov r2.x, r2.x  // zOverW<0:Inf>
mov r1.zw, r1.zzzw  // proj<2,3>

#line 397
mov r1.w, -r1.w
add r2.x, r1.w, r2.x
div r2.x, r1.z, r2.x  // ReconstructViewZ<0:NaN:Inf>

#line 472
mov r2.x, r2.x  // depth<0:NaN:Inf>

#line 480
nop 
mov r2.y, r2.y  // zOverW<0:Inf>

#line 397
add r2.y, r1.w, r2.y
div r2.z, r1.z, r2.y  // ReconstructViewZ<0:NaN:Inf>

#line 480
mov r2.z, r2.z  // depth<1:NaN:Inf>

#line 273
mov r2.x, r2.x  // outDepth<0:NaN:Inf>
mov r2.z, r2.z  // outDepth<1:NaN:Inf>

#line 603
mov r2.xz, r2.xxzx  // NGetPrimitiveDepthFactor_fetchViewZ_outDepth<0:NaN:Inf,1:NaN:Inf>

#line 593
mov r3.xyz, v1.xyzx  // NGetEyeDir_getEyeDir_inWorldPosition<0,1,2>

#line 594
nop 
mov r3.xyz, r3.xyzx  // inWorldPosition<0,1,2>

#line 201
mov r4.xyz, -cb2[20].xyzx
add r3.xyz, r3.xyzx, r4.xyzx  // diff<0:Inf,1:Inf,2:Inf>

#line 202
dp3 r2.y, r3.xyzx, r3.xyzx
rsq r2.y, r2.y
mul r3.xyz, r2.yyyy, r3.xyzx  // outEyeDir<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 594
mov r3.xyz, r3.xyzx  // NGetEyeDir_getEyeDir_outEyeDir<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 627
mov r2.yw, v1.zzzx  // NCalcNormal_calcNormal_inWorldPos<2,0>

#line 628
mov r3.xyz, r3.xyzx  // NCalcNormal_calcNormal_inEyeDirection<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 629
mov r3.w, v4.x  // NCalcNormal_calcNormal_inDistance<0>

#line 630
mov r4.x, v4.y  // NCalcNormal_calcNormal_inTime<0>

#line 634
nop 
mov r2.yw, r2.yyyw  // inWorldPos<2,0>
mov r3.xyz, r3.xyzx  // inEyeDirection<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
mov r3.w, r3.w  // inDistance<0>
mov r4.x, r4.x  // inTime<0>

#line 322
div r3.w, r3.w, l(1000.000000)
max r3.w, r3.w, l(0.500000)
min r3.w, r3.w, l(1.500000)  // inViewZ<0:[0.5f,1.5f]>

#line 326
div r4.yz, r2.wwyw, l(0.000000, 50.000000, 50.000000, 0.000000)  // uv<0:[-6.80565e+036f,6.80565e+036f],1:[-6.80565e+036f,6.80565e+036f]>

#line 327
sample_indexable(texture2d)(float,float,float,float) r4.yzw, r4.yzyy, t3.wxyz, s10
mul r4.yzw, r3.wwww, r4.yyzw  // randomInformation<0:Inf,1:Inf,2:Inf>

#line 328
div r4.z, r4.z, l(256.000000)
add r4.z, r4.z, r4.w
div r4.y, r4.y, l(65536.000000)
add r4.y, r4.y, r4.z  // randomInformation<0:NaN:Inf>

#line 331
mov r3.w, -r3.w
add r3.w, r3.w, l(1.000000)
max r3.w, r3.w, l(0.075000)  // inViewZ<0:[0.075f,0.5f]>

#line 333
nop 
mov r2.yw, r2.yyyw  // pos<2,0>
mul r4.y, r4.y, l(7.000000)
add r4.x, r4.y, r4.x  // time<0:NaN:Inf>

#line 234
mov r4.yzw, cb4[7].xxyz  // waveParamScales<0,1,2>

#line 237
mov r5.xyz, l(1.000000,0,0,0)  // dPdu<0: 1f,1: 0f,2: 0f>

#line 238
mov r6.xyz, l(0,0,-1.000000,0)  // dPdv<0: 0f,1: 0f,2:[-1f,-1f]>

#line 244
mov r5.w, l(1.000000)  // j<0: 1f>

#line 247
mov r6.w, l(0.015625)  // y<0: 0.015625f>

#line 248
mul r7.x, r4.x, l(0.550000)  // velocity<0:NaN:Inf>

#line 249
div r7.y, r4.w, l(1.600000)  // modifWaveParamScalesZ<0:[-2.12676e+038f,2.12676e+038f]>

#line 250
div r7.z, r4.w, l(1.800000)  // modifWaveParamScalesW<0:[-1.89046e+038f,1.89046e+038f]>

#line 251
mul r7.w, r7.y, l(0.500000)  // halfModifWaveParamScalesZ<0:[-1.06338e+038f,1.06338e+038f]>

#line 252
mul r8.x, r7.z, l(0.500000)  // halfModifWaveParamScalesW<0:[-9.45229e+037f,9.45229e+037f]>

#line 254
mov r8.y, l(0)  // i<0: 0>
mov r9.xyz, r5.xyzx  // dPdu<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
mov r10.xyz, r6.xyzx  // dPdv<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
mov r8.z, r8.y  // i<0>
mov r8.w, r5.w  // j<0:Inf>
mov r9.w, r6.w  // y<0:Inf>
loop 
  ilt r10.w, r8.z, l(32)
  breakc_z r10.w

#line 260
  mov r11.y, r9.w
  mov r11.x, l(0.125000)
  sample_indexable(texture2d)(float,float,float,float) r11.xyz, r11.xyxx, t0.xyzw, s10
  mov r11.xyz, r11.xyzx  // col<0:Inf,1:Inf,2:Inf>

#line 261
  div r10.w, r11.y, l(256.000000)
  add r10.w, r10.w, r11.x
  div r11.x, r11.z, l(65536.000000)
  add r10.w, r10.w, r11.x  // waveParam<0:NaN:Inf>

#line 264
  mov r11.y, r9.w
  mov r11.x, l(0.375000)
  sample_indexable(texture2d)(float,float,float,float) r11.xyz, r11.xyxx, t0.xyzw, s10
  mov r11.xyz, r11.xyzx  // col<0:Inf,1:Inf,2:Inf>

#line 265
  div r11.y, r11.y, l(256.000000)
  add r11.x, r11.y, r11.x
  div r11.y, r11.z, l(65536.000000)
  add r11.x, r11.y, r11.x  // waveParam<1:NaN:Inf>

#line 268
  mov r12.y, r9.w
  mov r12.x, l(0.625000)
  sample_indexable(texture2d)(float,float,float,float) r11.yzw, r12.xyxx, t0.wxyz, s10
  mov r11.yzw, r11.yyzw  // col<0:Inf,1:Inf,2:Inf>

#line 269
  div r11.z, r11.z, l(256.000000)
  add r11.y, r11.z, r11.y
  div r11.z, r11.w, l(65536.000000)
  add r11.y, r11.z, r11.y  // waveParam<2:NaN:Inf>

#line 272
  mov r12.y, r9.w
  mov r12.x, l(0.875000)
  sample_indexable(texture2d)(float,float,float,float) r12.xyz, r12.xyxx, t0.xyzw, s10
  mov r12.xyz, r12.xyzx  // col<0:Inf,1:Inf,2:Inf>

#line 273
  div r11.z, r12.y, l(256.000000)
  add r11.z, r11.z, r12.x
  div r11.w, r12.z, l(65536.000000)
  add r11.z, r11.w, r11.z  // waveParam<3:NaN:Inf>

#line 276
  mov r11.w, r4.y
  mul r12.x, r10.w, r11.w  // fixedParam<0:NaN:Inf>

#line 277
  mov r12.y, r4.z
  mul r12.z, r11.x, r12.y  // fixedParam<1:NaN:Inf>

#line 278
  mov r12.w, r7.y
  mul r12.w, r11.y, r12.w
  mov r13.x, r7.w
  mov r13.x, -r13.x
  add r12.w, r12.w, r13.x  // fixedParam<2:NaN:Inf>

#line 279
  mov r13.x, r7.z
  mul r13.x, r11.z, r13.x
  mov r13.y, r8.x
  mov r13.y, -r13.y
  add r13.x, r13.y, r13.x  // fixedParam<3:NaN:Inf>

#line 281
  nop 
  mov r13.yz, r2.wwyw  // pos<0,2>
  mov r12.x, r12.x  // waveParam<0:NaN:Inf>
  mov r12.z, r12.z  // waveParam<1:NaN:Inf>
  mov r12.w, r12.w  // waveParam<2:NaN:Inf>
  mov r13.x, r13.x  // waveParam<3:NaN:Inf>
  mov r9.xyz, r9.xyzx  // dPdu<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
  mov r10.xyz, r10.xyzx  // dPdv<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
  mov r13.w, r7.x  // time<0:NaN:Inf>

#line 209
  mov r12.x, r12.x  // amplitude<0:NaN:Inf>

#line 210
  mov r12.z, r12.z  // omega<0:NaN:Inf>

#line 211
  mov r12.w, r12.w  // cosTheta<0:NaN:Inf>

#line 212
  mov r13.x, r13.x  // sinTheta<0:NaN:Inf>

#line 214
  mul r12.z, r13.w, r12.z
  mul r13.y, r12.w, r13.y
  mul r13.z, r13.x, r13.z
  add r13.y, r13.z, r13.y
  mov r13.y, -r13.y
  add r12.z, r12.z, r13.y  // phase<0:NaN:Inf>

#line 216
  sincos r13.y, null, r12.z  // s<0:NaN>
  sincos null, r12.z, r12.z  // c<0:NaN>

#line 218
  mul r13.z, r13.y, r12.z
  add r14.xz, r12.zzzz, r13.zzzz  // ds<0:NaN,0:NaN>

#line 219
  mov r13.y, -r13.y
  mul r12.z, r12.z, r13.y
  add r14.y, r13.y, r12.z  // dc<0:NaN>

#line 221
  mov r12.z, -r12.x
  max r12.x, r12.z, r12.x
  log r12.x, r12.x
  mul r12.x, r12.x, l(0.600000)
  exp r12.x, r12.x  // normInfluence<0:NaN:Inf>

#line 223
  mov r14.xz, r14.xxzx  // dPd<0:NaN,2:NaN>
  mov r14.y, r14.y  // dPd<1:NaN>

#line 224
  mul r12.x, r12.x, l(2.000000)
  mul r13.yzw, r12.xxxx, r14.xxyz  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 225
  mul r12.xzw, r12.wwww, r13.yyzw
  mov r12.xzw, -r12.xxzw
  add r9.xyz, r9.xyzx, r12.xzwx  // dPdu<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 226
  mul r12.xzw, r13.yyzw, r13.xxxx
  add r10.xyz, r10.xyzx, r12.xzwx  // dPdv<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 281
  mov r9.xyz, r9.xyzx  // dPdu<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
  mov r10.xyz, r10.xyzx  // dPdv<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 286
  ilt r12.x, r8.z, l(4)
  if_nz r12.x

#line 287
    add r10.w, r10.w, l(-0.000000)
    mul r10.w, r11.w, r10.w
    mul r10.w, r10.w, l(8.000000)  // fixedParam<0:NaN:Inf>

#line 288
    add r11.x, r11.x, l(-0.000000)
    mul r11.x, r12.y, r11.x  // fixedParam<1:NaN:Inf>

#line 289
    add r11.y, r11.y, l(-0.500000)
    mov r11.w, r4.w
    mul r11.y, r11.w, r11.y
    mul r12.x, r8.w, l(1.500000)
    div r11.y, r11.y, r12.x
    mul r11.y, r11.y, l(0.600000)  // fixedParam<2:NaN:Inf>

#line 290
    add r11.z, r11.z, l(-0.500000)
    mul r11.z, r11.w, r11.z
    mul r11.w, r8.w, l(2.250000)
    div r11.z, r11.z, r11.w
    mul r11.z, r11.z, l(0.600000)  // fixedParam<3:NaN:Inf>

#line 292
    nop 
    mov r12.xy, r2.ywyy  // pos<0,2>
    mov r10.w, r10.w  // waveParam<0:NaN:Inf>
    mov r11.x, r11.x  // waveParam<1:NaN:Inf>
    mov r11.y, r11.y  // waveParam<2:NaN:Inf>
    mov r11.z, r11.z  // waveParam<3:NaN:Inf>
    mov r9.xyz, r9.xyzx  // dPdu<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
    mov r10.xyz, r10.xyzx  // dPdv<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
    mul r11.w, r4.x, l(0.600000)  // time<0:NaN:Inf>

#line 209
    mov r10.w, r10.w  // amplitude<0:NaN:Inf>

#line 210
    mov r11.x, r11.x  // omega<0:NaN:Inf>

#line 211
    mov r11.y, r11.y  // cosTheta<0:NaN:Inf>

#line 212
    mov r11.z, r11.z  // sinTheta<0:NaN:Inf>

#line 214
    mul r11.x, r11.w, r11.x
    mul r11.w, r11.y, r12.x
    mul r12.x, r11.z, r12.y
    add r11.w, r11.w, r12.x
    mov r11.w, -r11.w
    add r11.x, r11.w, r11.x  // phase<0:NaN:Inf>

#line 216
    sincos r11.w, null, r11.x  // s<0:NaN>
    sincos null, r11.x, r11.x  // c<0:NaN>

#line 218
    mul r12.x, r11.w, r11.x
    add r12.xz, r11.xxxx, r12.xxxx  // ds<0:NaN,0:NaN>

#line 219
    mov r11.w, -r11.w
    mul r11.x, r11.x, r11.w
    add r12.y, r11.w, r11.x  // dc<0:NaN>

#line 221
    mov r11.x, -r10.w
    max r10.w, r10.w, r11.x
    log r10.w, r10.w
    mul r10.w, r10.w, l(0.600000)
    exp r10.w, r10.w  // normInfluence<0:NaN:Inf>

#line 223
    mov r12.xz, r12.xxzx  // dPd<0:NaN,2:NaN>
    mov r12.y, r12.y  // dPd<1:NaN>

#line 224
    mul r10.w, r10.w, l(2.000000)
    mul r12.xyz, r10.wwww, r12.xyzx  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 225
    mul r11.xyw, r11.yyyy, r12.xyxz
    mov r11.xyw, -r11.xyxw
    add r9.xyz, r9.xyzx, r11.xywx  // dPdu<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 226
    mul r11.xyz, r11.zzzz, r12.xyzx
    add r10.xyz, r10.xyzx, r11.xyzx  // dPdv<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 292
    mov r9.xyz, r9.xyzx  // dPdu<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
    mov r10.xyz, r10.xyzx  // dPdv<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 294
    add r8.w, r8.w, l(0.075000)  // j<0:Inf>

#line 286
  endif 

#line 296
  add r9.w, r9.w, l(0.031250)  // y<0:Inf>

#line 254
  iadd r8.z, r8.z, l(1)  // i<0>
endloop 

#line 299
mul r4.xyz, r9.yzxy, r10.zxyz
mul r5.xyz, r9.zxyz, r10.yzxy
mov r5.xyz, -r5.xyzx
add r4.xyz, r4.xyzx, r5.xyzx
dp3 r2.y, r4.xyzx, r4.xyzx
rsq r2.y, r2.y
mul r4.xyz, r2.yyyy, r4.xyzx  // normal<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 333
mov r4.xyz, r4.xyzx  // normal<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 337
dp3 r2.y, r3.xyzx, r4.xyzx
lt r2.w, l(0.000000), r2.y
if_nz r2.w

#line 339
  add r2.y, r2.y, r2.y
  mov r2.y, -r2.y
  mul r5.xyz, r2.yyyy, r3.xyzx
  add r4.xyz, r4.xyzx, r5.xyzx  // normal<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 337
endif 

#line 344
sqrt r2.y, r3.w  // inViewZ<0:[0.273861f,0.707107f]>

#line 345
max r2.y, r2.y, l(0.300000)  // inViewZ<0:[0.3f,0.707107f]>

#line 348
add r4.xyz, r4.xyzx, l(-0.000000, -1.000000, -0.000000, 0.000000)
mul r4.xyz, r2.yyyy, r4.xyzx
add r4.xyz, r4.xyzx, l(0.000000, 1.000000, 0.000000, 0.000000)
dp3 r2.y, r4.xyzx, r4.xyzx
rsq r2.y, r2.y
mul r4.xyz, r2.yyyy, r4.xyzx  // normal<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 350
mov r4.xyz, r4.xyzx  // outNormal<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 634
mov r4.xyz, r4.xyzx  // NCalcNormal_calcNormal_outNormal<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 71
nop 

#line 76
nop 

#line 77
nop 
nop 

#line 78
nop 

#line 626
nop 

#line 56
nop 

#line 61
nop 

#line 62
nop 
nop 

#line 63
nop 

#line 621
nop 

#line 41
nop 

#line 46
nop 

#line 47
nop 
nop 

#line 48
nop 

#line 616
nop 

#line 636
nop 

#line 33
nop 

#line 363
nop 

#line 364
nop 

#line 33
nop 

#line 15
nop 

#line 19
nop 

#line 20
nop 

#line 173
nop 

#line 608
mov r0.xyzw, r0.xyzw  // NScreenToClipCoordinate_screenToClipcoord_inPixelPosition<0,1,0,1>

#line 609
nop 
mov r0.xyzw, r0.xyzw  // inPixelPosition<0,1,0,1>

#line 72
div r0.xyzw, r0.xyzw, cb0[1].xyxy  // outClipPosition<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>

#line 73
mul r0.xyzw, r0.xyzw, l(2.000000, -2.000000, 2.000000, -2.000000)
add r0.xyzw, r0.xyzw, l(-1.000000, 1.000000, -1.000000, 1.000000)  // outClipPosition<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>

#line 609
mov r0.xyzw, r0.xyzw  // NScreenToClipCoordinate_screenToClipcoord_outClipPosition<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>
mov r0.xyzw, r0.xyzw  // NFetchVolFog_fetchFog_inClipPos<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>

#line 610
mov r2.y, v1.w  // NFetchVolFog_fetchFog_inViewZ<0>

#line 611
nop 
mov r0.xyzw, r0.xyzw  // inClipPos<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>
mov r2.y, r2.y  // inViewZ<0>

#line 18
nop 
mov r0.xyzw, r0.xyzw  // inClipPos<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>
mov r2.y, r2.y  // inViewZ<0>

#line 142
nop 
mov r0.xyzw, r0.xyzw  // inClipPos<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>
mov r2.w, r2.y  // inViewZ<0>

#line 50
nop 
mov r2.w, r2.w  // inViewZ<0>

#line 27
mov r3.w, cb2[25].x  // invLogFarDistance<0>

#line 30
log r2.w, r2.w
mul r2.w, r2.w, r3.w  // EncodeFogCameraZ<0:NaN:Inf>

#line 50
mov r2.w, r2.w  // zEncoded<0:NaN:Inf>

#line 51
max r2.w, r2.w, l(0.000000)
min r2.w, r2.w, l(1.000000)  // zEncoded<0:[0f,1f]>

#line 52
mul r2.w, r2.w, l(127.000000)  // zEncoded<0:[0f,127f]>

#line 56
mul r0.xyzw, r0.xyzw, l(0.014648, 0.123047, 0.014648, 0.123047)
add r0.xyzw, r0.xyzw, l(0.015625, 0.125000, 0.015625, 0.125000)  // uv<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>

#line 57
add r3.w, r2.w, l(1.000000)
max r3.w, r3.w, l(0.000000)
min r5.w, r3.w, l(127.000000)
mov r5.y, r2.w
round_ni r5.xy, r5.ywyy  // zInt<0:[0f,127f],1:[1f,127f]>

#line 59
div r5.xy, r5.xyxx, l(32.000000, 32.000000, 0.000000, 0.000000)
frc r5.zw, r5.xxxy
mul r6.xz, r5.zzwz, l(32.000000, 0.000000, 32.000000, 0.000000)  // layerOffset<0:[0f,32f],2:[0f,32f]>

#line 60
round_ni r6.yw, r5.xxxy  // layerOffset<1:[0f,3f],3:[0f,3f]>

#line 61
mul r5.xyzw, r6.xyzw, l(0.031250, 0.250000, 0.031250, 0.250000)
add r0.xyzw, r0.xyzw, r5.xyzw  // uv_lerp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 62
frc r5.xyzw, r2.wwww  // zBlend<0:[0f,1f],1:[0f,1f],2:[0f,1f],3:[0f,1f]>

#line 63
sample_indexable(texture2d)(float,float,float,float) r6.xyzw, r0.xyxx, t12.xyzw, s11  // c0<0:Inf,1:Inf,2:Inf,3:Inf>

#line 64
sample_indexable(texture2d)(float,float,float,float) r0.xyzw, r0.zwzz, t12.xyzw, s11  // c1<0:Inf,1:Inf,2:Inf,3:Inf>

#line 65
mov r7.xyzw, -r5.xyzw
add r7.xyzw, r7.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
mul r6.xyzw, r6.xyzw, r7.xyzw
mul r0.xyzw, r0.xyzw, r5.xyzw
add r0.xyzw, r0.xyzw, r6.xyzw  // fogColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 69
mov r2.w, cb2[25].y  // normalizeFactor<0>

#line 70
mul r0.xyz, r0.xyzx, r2.wwww  // fogColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 71
mov r0.xyz, r0.xyzx  // GetVolumetricFog2D<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
mov r0.w, r0.w  // GetVolumetricFog2D<3:NaN:Inf>

#line 142
mov r0.xyzw, r0.xyzw  // GetVolumetricFog<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 18
mov r0.xyzw, r0.xyzw  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 611
mov r0.xyzw, r0.xyzw  // NFetchVolFog_fetchFog_outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 637
mov r0.xyzw, r0.xyzw  // NComputeColor_computeColor_inFogColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 649
mov r4.xyz, r4.xyzx  // NComputeColor_computeColor_inNormal<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 652
mov r2.x, r2.x  // NComputeColor_computeColor_inDepthZ<0:NaN:Inf>

#line 661
mov r5.xy, v1.xzxx  // NComputeColor_computeColor_inWorldPos<0,2>

#line 656
nop 
mov r0.xyzw, r0.xyzw  // inFogColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mov r4.xyz, r4.xyzx  // inNormal<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
mov r2.x, r2.x  // inDepthZ<0:NaN:Inf>
mov r5.xy, r5.xyxx  // inWorldPos<0,2>

#line 389
mov r6.xyz, cb4[3].xyzx  // inSunDirection<0,1,2>

#line 391
mov r7.xyz, cb4[2].xyzx  // inSunColor<0,1,2>

#line 392
mov r8.xyz, cb4[4].xyzx  // tonemapParam<0,1,2>

#line 393
mov r2.w, cb4[6].w  // screen<0>

#line 394
mul r3.w, r2.y, l(2.000000)
div r2.w, r3.w, r2.w  // screenAdjustedViewZ<0:NaN:Inf>

#line 398
mov r9.xyz, -r3.xyzx
dp3 r3.w, r9.xyzx, r4.xyzx  // EN<0:NaN:Inf>

#line 399
mov r3.w, -r3.w
add r3.w, r3.w, l(1.000000)
mul r4.w, r3.w, l(1.000000)
mul r3.w, r3.w, r3.w
mul r3.w, r3.w, r3.w
mul r3.w, r3.w, r4.w
mul r3.w, r3.w, l(0.980000)
add r3.w, r3.w, l(0.020000)  // fresnel<0:NaN:Inf>

#line 402
add r9.xyz, r6.xyzx, r9.xyzx
dp3 r4.w, r9.xyzx, r9.xyzx
rsq r4.w, r4.w
mul r9.xyz, r4.wwww, r9.xyzx  // EL<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 404
dp3 r4.w, r4.xyzx, r9.xyzx
mov r5.z, -r6.y
add r5.z, r5.z, l(1.150000)
max r5.z, r5.z, l(1.010000)
mul r4.w, r4.w, r5.z  // NH<0:NaN:Inf>

#line 405
mul r9.xyz, r7.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
max r5.z, r4.w, l(0.000000)
min r5.z, r5.z, l(1.000000)
log r5.z, r5.z
mul r5.z, r5.z, l(400.000000)
exp r5.z, r5.z
mul r9.xyz, r5.zzzz, r9.xyzx  // specularColor<0,1,2>

#line 407
add r4.w, r4.w, l(-1.000000)
max r4.w, r4.w, l(0.000000)
min r4.w, r4.w, l(1.000000)
mul r4.w, r4.w, l(100.000000)
max r4.w, r4.w, l(0.000000)
min r4.w, r4.w, l(1.000000)
mul r4.w, r4.w, l(3.000000)
add r4.w, r4.w, l(1.000000)
mul r9.xyz, r4.wwww, r9.xyzx  // specularColor<0:Inf,1:Inf,2:Inf>

#line 409
mul r4.w, r6.y, l(5.000000)
add r4.w, r4.w, l(0.100000)
max r4.w, r4.w, l(0.000000)
min r4.w, r4.w, l(1.000000)
mul r9.xyz, r4.wwww, r9.xyzx  // specularColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 416
mul r5.zw, r4.xxxz, l(0.000000, 0.000000, 10.000000, 10.000000)
add r5.xy, r5.zwzz, r5.xyxx
div r5.xy, r5.xyxx, l(300.000000, 300.000000, 0.000000, 0.000000)  // waterDepthUv<0:NaN:Inf,1:NaN:Inf>

#line 417
sample_indexable(texture2d)(float,float,float,float) r5.xyz, r5.xyxx, t2.xyzw, s10
mov r5.xyz, r5.xyzx  // waterDepthTexColor<0:Inf,1:Inf,2:Inf>

#line 425
mul r4.w, r5.z, l(40.000000)
max r4.w, r4.w, l(0.000000)
min r4.w, r4.w, l(1.000000)  // rate1<0:[0f,1f]>

#line 426
mov r5.z, -r4.w
add r5.z, r5.z, l(1.000000)  // rate2<0:[0f,1f]>

#line 428
mul r10.xyz, r4.wwww, l(0.260000, 0.280000, 0.340000, 0.000000)
mul r11.xyz, r5.zzzz, l(0.105000, 0.120000, 0.150000, 0.000000)
add r10.xyz, r10.xyzx, r11.xyzx  // cubeMapReflectionColor<0:[0f,0.365f],1:[0f,0.4f],2:[0f,0.49f]>

#line 433
div r4.w, l(0.000100), cb2[23].z
max r4.w, r4.w, l(0.000000)
min r4.w, r4.w, l(1.000000)
max r4.w, r4.w, l(0.350000)  // exposureAdaptation<0:[0.35f,1f]>

#line 434
mul r11.xyz, r4.wwww, l(0.260000, 0.280000, 0.340000, 0.000000)  // cubeMapColor<0:[0.091f,0.26f],1:[0.098f,0.28f],2:[0.119f,0.34f]>

#line 435
mul r10.xyz, r4.wwww, r10.xyzx  // cubeMapReflectionColor<0:[0f,0.365f],1:[0f,0.4f],2:[0f,0.49f]>

#line 438
mov r12.y, l(0)
mov r12.xz, r3.xxzx
dp3 r3.x, r12.xyzx, r12.xyzx
rsq r3.x, r3.x
mul r12.xyz, r3.xxxx, r12.xyzx  // eyeDir<0:NaN:Inf,1: 0f,2:NaN:Inf>

#line 439
dp3 r3.x, r12.xyzx, r6.xyzx
add r3.x, r6.y, r3.x
max r3.x, r3.x, l(0.000000)
min r12.xyz, r3.xxxx, l(1.000000, 1.000000, 1.000000, 0.000000)  // colorBlendRate<0:[0f,1f],0:[0f,1f],0:[0f,1f]>

#line 440
dp3 r3.x, r7.xyzx, r7.xyzx
rsq r3.x, r3.x
mul r7.xyz, r3.xxxx, r7.xyzx
add r7.xyz, r7.xyzx, l(-0.250000, -0.250000, -0.250000, 0.000000)
mul r7.xyz, r7.xyzx, r12.xyzx
add r7.xyz, r7.xyzx, l(0.250000, 0.250000, 0.250000, 0.000000)  // sunColorAdaptation<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 441
mul r11.xyz, r7.xyzx, r11.xyzx  // cubeMapColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 442
mul r7.xyz, r7.xyzx, r10.xyzx  // cubeMapReflectionColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 445
mul r10.xyz, r11.xyzx, l(0.140000, 0.315000, 0.262500, 0.000000)  // baseColor1<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 446
mul r11.xyz, r11.xyzx, l(0.270000, 0.405000, 0.247500, 0.000000)  // baseColor2<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 449
mul r3.x, r5.y, l(10.000000)
max r3.x, r3.x, l(0.000000)
min r3.x, r3.x, l(1.000000)  // rate1<0:[0f,1f]>

#line 450
mov r3.z, -r3.x
add r3.z, r3.z, l(1.000000)  // rate2<0:[0f,1f]>

#line 451
mul r5.yzw, r3.xxxx, r10.xxyz
mul r10.xyz, r3.zzzz, r11.xyzx
add r5.yzw, r5.yyzw, r10.xxyz  // ambientColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 456
div r3.x, r2.w, l(500.000000)
max r3.z, r3.x, l(0.000000)
min r3.z, r3.z, l(1.000000)
mov r3.z, -r3.z
add r3.z, r3.z, l(1.000000)
mul r3.z, r3.z, l(0.950000)
add r10.xy, r3.zzzz, l(0.050000, 0.050000, 0.000000, 0.000000)  // bendRate<0:[0.05f,1f],0:[0.05f,1f]>

#line 457
mul r10.zw, r4.xxxz, l(0.000000, 0.000000, 0.040000, 0.040000)
add r10.zw, r10.zzzw, l(0.000000, 0.000000, 0.000000, 0.040000)
mul r10.xy, r10.zwzz, r10.xyxx
mov r10.xy, -r10.xyxx
add r10.xy, r1.xyxx, r10.xyxx
max r10.xy, r10.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
min r10.xy, r10.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)  // distortionUV<0:[0f,1f],1:[0f,1f]>

#line 459
nop 

#line 462
nop 
mov r10.xy, r10.xyxx  // inTexCoord<0:[0f,1f],1:[0f,1f]>

#line 467
sample_indexable(texture2d)(float,float,float,float) r3.z, r10.xyxx, t13.yzxw, s9
mov r3.z, r3.z  // fetchDepth<0:Inf>

#line 472
nop 
mov r3.z, r3.z  // zOverW<0:Inf>

#line 397
add r1.w, r1.w, r3.z
div r1.z, r1.z, r1.w  // ReconstructViewZ<0:NaN:Inf>

#line 472
mov r1.z, r1.z  // depth<0:NaN:Inf>

#line 480
nop 

#line 462
mov r1.z, r1.z  // depthFactor<0:NaN:Inf>

#line 463
mov r1.z, r1.z  // distortionDepth<0:NaN:Inf>

#line 467
lt r1.w, r1.z, r2.y
mov r3.z, -r1.z
add r3.z, r2.y, r3.z
div r3.z, r3.z, l(50.000000)
mov r3.z, -r3.z
add r3.z, r3.z, l(1.000000)
max r3.z, r3.z, l(0.000000)
min r3.z, r3.z, l(1.000000)
mov r2.y, -r2.y
add r1.z, r1.z, r2.y
mul r4.w, r3.y, l(50.000000)
mov r4.w, -r4.w
add r4.w, r4.w, l(100.000000)
div r1.z, r1.z, r4.w
mov r1.z, -r1.z
add r1.z, r1.z, l(1.000000)
max r1.z, r1.z, l(0.000000)
min r1.z, r1.z, l(1.000000)
movc r1.z, r1.w, r3.z, r1.z  // distortionBlendRate<0:[0f,1f]>

#line 472
mul r10.xyz, r7.xyzx, l(10.000000, 10.000000, 10.000000, 0.000000)  // cubeMapReflectionMult10<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 474
add r11.xyz, r10.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
mul r10.xyz, r1.zzzz, r10.xyzx
mov r10.xyz, -r10.xyzx
add r10.xyz, r10.xyzx, r11.xyzx  // cubeMapDistortionBlendColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 477
add r11.xyz, r9.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
mul r12.xyz, r1.zzzz, r9.xyzx
mov r12.xyz, -r12.xyzx
add r11.xyz, r11.xyzx, r12.xyzx  // specularDistortionBlendColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 481
dp3 r1.w, r6.xyzx, r4.xyzx
mul r4.xzw, r1.wwww, r11.xxyz
mul r6.xyz, r10.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
add r4.xzw, r4.xxzw, r6.xxyz  // formColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 482
div r1.w, r2.w, l(200.000000)
max r1.w, r1.w, l(0.000000)
min r1.w, r1.w, l(1.000000)
mul r1.w, r1.w, r5.x  // formIntensity<0:NaN:Inf>

#line 486
mul r6.xyz, r7.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
add r6.xyz, r6.xyzx, r9.xyzx  // specularColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 487
mul r7.xyz, r1.zzzz, r6.xyzx
mov r7.xyz, -r7.xyzx
add r6.xyz, r6.xyzx, r7.xyzx
add r6.xyz, r6.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)  // specularColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 488
mul r6.xyz, r3.wwww, r6.xyzx  // specularColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 490
mul r1.z, r1.w, l(5.000000)
mov r1.z, -r1.z
add r1.z, r1.z, l(1.000000)
max r1.z, r1.z, l(0.000000)
min r1.z, r1.z, l(1.000000)
mul r1.z, r1.z, l(1.000000)  // specularIntensity<0:[0f,1f]>

#line 494
mov r2.w, -r1.w
add r2.w, r2.w, l(1.000000)
mul r2.w, r2.w, l(0.850000)  // ambientIntensity<0:NaN:Inf>

#line 504
mul r6.xyz, r1.zzzz, r6.xyzx
mul r4.xzw, r1.wwww, r4.xxzw
add r4.xzw, r4.xxzw, r6.xxyz
mul r5.xyz, r2.wwww, r5.yzwy
add r4.xzw, r4.xxzw, r5.xxyz  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 507
mul r4.xzw, r0.wwww, r4.xxzw
add r0.xyz, r0.xyzx, r4.xzwx  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 510
nop 
mov r8.xyz, r8.xyzx  // params<0,1,2>
mov r0.xyz, r0.xyzx  // x<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 11
mov r4.xzw, r8.yyyy
ge r5.xyz, r4.xzwx, r0.xyzx
movc r5.xyz, r5.xyzx, l(1.000000,1.000000,1.000000,0), l(0,0,0,0)  // mask<0:[-0f,1f],1:[-0f,1f],2:[-0f,1f]>

#line 12
mul r6.xyz, r0.xyzx, r5.xyzx
mov r5.xyz, -r5.xyzx
add r5.xyz, r5.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
add r0.xyz, r8.zzzz, r0.xyzx
mov r7.xyz, -r4.zzzz
add r0.xyz, r0.xyzx, r7.xyzx
mul r0.xyz, r0.xyzx, r8.xxxx
div r0.xyz, l(-1.000000, -1.000000, -1.000000, 0.000000), r0.xyzx
add r0.xyz, r8.zzzz, r0.xyzx
add r0.xyz, r4.zzzz, r0.xyzx
mul r0.xyz, r0.xyzx, r5.xyzx
add r0.xyz, r0.xyzx, r6.xyzx  // TppTonemap<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 510
mov r0.xyz, r0.xyzx  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 513
nop 
mov r0.xyz, r0.xyzx  // linearRGB<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 24
ge r4.xzw, l(0.003131, 0.000000, 0.003131, 0.003131), r0.xxyz
movc r4.xzw, r4.xxzw, l(1.000000,0,1.000000,1.000000), l(0,0,0,0)  // mask<0:[-0f,1f],1:[-0f,1f],2:[-0f,1f]>

#line 25
mul r5.xyz, r0.xyzx, l(12.920000, 12.920000, 12.920000, 0.000000)
mul r5.xyz, r4.xzwx, r5.xyzx
mov r4.xzw, -r4.xxzw
add r4.xzw, r4.xxzw, l(1.000000, 0.000000, 1.000000, 1.000000)
max r0.xyz, r0.xyzx, l(0.000010, 0.000010, 0.000010, 0.000000)
log r0.xyz, r0.xyzx
mul r0.xyz, r0.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
exp r0.xyz, r0.xyzx
mul r0.xyz, r0.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000)
add r0.xyz, r0.xyzx, l(-0.055000, -0.055000, -0.055000, 0.000000)
mul r0.xyz, r0.xyzx, r4.xzwx
add r0.xyz, r0.xyzx, r5.xyzx  // GammaCorrection<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 513
mov r0.xyz, r0.xyzx  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 518
mov r0.w, -r3.x
add r0.w, r0.w, l(1.000000)
max r0.w, r0.w, l(0.000000)
min r0.w, r0.w, l(1.000000)
mul r0.w, r0.w, l(0.950000)
add r0.w, r0.w, l(0.050000)  // bendRate<0:[0.05f,1f]>

#line 519
mul r1.zw, r0.wwww, l(0.000000, 0.000000, 0.000000, 0.005000)
mov r1.zw, -r1.zzzw
add r1.xy, r1.zwzz, r1.xyxx
max r1.xy, r1.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
min r1.xy, r1.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)  // distortionUV<0:[0f,1f],1:[0f,1f]>

#line 520
sample_indexable(texture2d)(float,float,float,float) r1.xyz, r1.xyxx, t1.xyzw, s10
mov r1.xyz, r1.xyzx  // distortionColor<0:Inf,1:Inf,2:Inf>

#line 522
mov r0.w, -r3.y
mul r0.w, r0.w, l(3.000000)
max r0.w, r0.w, l(0.000000)
min r0.w, r0.w, l(1.000000)
mul r0.w, r0.w, l(26.000000)
mov r0.w, -r0.w
add r0.w, r0.w, l(30.000000)  // LimitLength<0:[4f,30f]>

#line 523
add r1.w, r4.y, l(-0.900000)
mul r1.w, r1.w, l(10.000000)
max r1.w, r1.w, l(0.000000)
min r1.w, r1.w, l(1.000000)
mul r0.w, r0.w, r1.w
add r0.w, r0.w, l(0.010000)  // depthBlendLength<0:[0.01f,30.01f]>

#line 524
add r1.w, r2.y, r2.x
div r0.w, r1.w, r0.w
mov r0.w, -r0.w
add r0.w, r0.w, l(1.000000)
max r0.w, r0.w, l(0.000000)
min r0.w, r0.w, l(1.000000)  // depthBlendFactor<0:[0f,1f]>

#line 527
mul r1.xyz, r0.wwww, r1.xyzx
mov r0.w, -r0.w
add r0.w, r0.w, l(1.000000)
mul r0.xyz, r0.wwww, r0.xyzx
add r0.xyz, r0.xyzx, r1.xyzx  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 656
mov r0.xyz, r0.xyzx  // NComputeColor_computeColor_outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 605
mov r0.w, v2.z  // NComputeDepthComparisonFactor_computeDepthComparisonFactor_inDepth<0>

#line 606
mov r2.z, r2.z  // NComputeDepthComparisonFactor_computeDepthComparisonFactor_inSceneDepth<1:NaN:Inf>

#line 607
nop 
mov r0.w, r0.w  // inDepth<0>
mov r2.z, r2.z  // inSceneDepth<1:NaN:Inf>

#line 191
ge r0.w, r2.z, r0.w
movc r0.w, r0.w, l(1), l(0)
itof r0.w, r0.w  // outBlendFactor<1:[0f,1f]>

#line 607
mov r0.w, r0.w  // NComputeDepthComparisonFactor_computeDepthComparisonFactor_outBlendFactor<1:[0f,1f]>

#line 669
mov r0.w, r0.w  // NOutputColorBufferSoftBlender_finalBlender_inZBlendFactor<1:[0f,1f]>

#line 670
mov r0.xyz, r0.xyzx  // NOutputColorBufferSoftBlender_finalBlender_inColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 672
nop 
mov r0.w, r0.w  // inZBlendFactor<1:[0f,1f]>
mov r0.xyz, r0.xyzx  // inColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 258
mul r1.xyz, r0.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
mov r1.w, l(1.000000)  // outColor<3: 1f>

#line 260
mul r2.x, r0.w, l(1.000000)
mul r2.xyz, r0.xyzx, r2.xxxx  // outColorSub<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
mul r2.w, r0.w, l(1.000000)  // outColorSub<3:[0f,1f]>

#line 672
mov r1.xyzw, r1.xyzw  // NOutputColorBufferSoftBlender_finalBlender_outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3: 1f>
mov r2.xyzw, r2.xyzw  // NOutputColorBufferSoftBlender_finalBlender_outColorSub<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:[0f,1f]>

#line 674
mov o0.xyzw, r1.xyzw  // outColor0<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3: 1f>

#line 676
mov o1.xyzw, r2.xyzw  // outColor1<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:[0f,1f]>

#line 543
ret 
// Approximately 630 instruction slots used
