Microsoft (R) Direct3D Shader Compiler 10.1
Copyright (C) 2013 Microsoft. All rights reserved.

//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer cPSScene
// {
//
//   struct PSScene
//   {
//       
//       float4x4 m_projectionView;     // Offset:    0
//       float4x4 m_projection;         // Offset:   64
//       float4x4 m_view;               // Offset:  128
//       float4x4 m_shadowProjection;   // Offset:  192
//       float4x4 m_shadowProjection2;  // Offset:  256
//       float4 m_eyepos;               // Offset:  320
//       float4 m_projectionParam;      // Offset:  336
//       float4 m_viewportSize;         // Offset:  352
//       float4 m_exposure;             // Offset:  368
//       float4 m_fogParam[3];          // Offset:  384
//       float4 m_fogColor;             // Offset:  432
//       float4 m_cameraCenterOffset;   // Offset:  448
//       float4 m_shadowMapResolutions; // Offset:  464
//
//   } g_psScene;                       // Offset:    0 Size:   480
//
// }
//
// cbuffer cPSMaterial
// {
//
//   struct PSMaterial
//   {
//       
//       float4 m_materials[8];         // Offset:    0
//
//   } g_psMaterial;                    // Offset:    0 Size:   128
//
// }
//
// cbuffer cPSSystem
// {
//
//   struct PSSystem
//   {
//       
//       float4 m_param;                // Offset:    0
//       float4 m_renderInfo;           // Offset:   16
//       float4 m_renderBuffer;         // Offset:   32
//       float4 m_dominantLightDir;     // Offset:   48
//
//   } g_psSystem;                      // Offset:    0 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// g_samplerLinear_Wrap              sampler      NA          NA            s10      1 
// g_samplerLinear_Clamp             sampler      NA          NA            s11      1 
// inDomeTexture                     texture  float4          2d             t0      1 
// inLowCylinderTexture              texture  float4          2d             t1      1 
// inMidCylinderTexture              texture  float4          2d             t2      1 
// g_tex_fog                         texture  float4          2d            t12      1 
// cPSSystem                         cbuffer      NA          NA            cb0      1 
// cPSScene                          cbuffer      NA          NA            cb2      1 
// cPSMaterial                       cbuffer      NA          NA            cb4      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// COLOR                    0   xyzw        0     NONE   float   xyz 
// TEXCOORD                 1   xyzw        1     NONE   float   xyzw
// TEXCOORD                 2   xyzw        2     NONE   float   x zw
// TEXCOORD                 3   xyz         3     NONE   float   xyz 
// SV_Position              0   xyzw        4      POS   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xyzw        1   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB2[26], immediateIndexed
dcl_constantbuffer CB4[6], immediateIndexed
dcl_constantbuffer CB0[2], immediateIndexed
dcl_sampler s10, mode_default
dcl_sampler s11, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t12
dcl_input_ps linear v0.xyz
dcl_input_ps linear v1.xyzw
dcl_input_ps linear v2.xzw
dcl_input_ps linear v3.xyz
dcl_input_ps_siv linear noperspective v4.xy, position
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_temps 7

#line 269 "d:\work\master\git_clone\_intermediate\win64\TppShaders_dx11_win64\Release\Prim_TppSkyCld3_DG_ps.hlsl"
add r0.xyzw, v4.xyxy, l(-0.500000, -0.500000, -0.500000, -0.500000)  // inVPos<0,1,0,1>

#line 296
mov r0.xyzw, r0.xyzw  // NScreenToClipCoordinate_screenToClipcoord_inPixelPosition<0,1,0,1>

#line 297
nop 
mov r0.xyzw, r0.xyzw  // inPixelPosition<0,1,0,1>

#line 72
div r0.xyzw, r0.xyzw, cb0[1].xyxy  // outClipPosition<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>

#line 73
mul r0.xyzw, r0.xyzw, l(2.000000, -2.000000, 2.000000, -2.000000)
add r0.xyzw, r0.xyzw, l(-1.000000, 1.000000, -1.000000, 1.000000)  // outClipPosition<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>

#line 297
mov r0.xyzw, r0.xyzw  // NScreenToClipCoordinate_screenToClipcoord_outClipPosition<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>
mov r0.xyzw, r0.xyzw  // NFetchVolFog_fetchFog_inClipPos<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>

#line 298
mov r1.x, v3.z  // NFetchVolFog_fetchFog_inViewZ<0>

#line 299
nop 
mov r0.xyzw, r0.xyzw  // inClipPos<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>
mov r1.x, r1.x  // inViewZ<0>

#line 18
nop 
mov r0.xyzw, r0.xyzw  // inClipPos<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>
mov r1.x, r1.x  // inViewZ<0>

#line 142
nop 
mov r0.xyzw, r0.xyzw  // inClipPos<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>
mov r1.x, r1.x  // inViewZ<0>

#line 50
nop 
mov r1.x, r1.x  // inViewZ<0>

#line 27
mov r1.y, cb2[25].x  // invLogFarDistance<0>

#line 30
log r1.x, r1.x
mul r1.x, r1.x, r1.y  // EncodeFogCameraZ<0:NaN:Inf>

#line 50
mov r1.x, r1.x  // zEncoded<0:NaN:Inf>

#line 51
max r1.x, r1.x, l(0.000000)
min r1.x, r1.x, l(1.000000)  // zEncoded<0:[0f,1f]>

#line 52
mul r1.x, r1.x, l(127.000000)  // zEncoded<0:[0f,127f]>

#line 56
mul r0.xyzw, r0.xyzw, l(0.014648, 0.123047, 0.014648, 0.123047)
add r0.xyzw, r0.xyzw, l(0.015625, 0.125000, 0.015625, 0.125000)  // uv<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>

#line 57
add r1.y, r1.x, l(1.000000)
max r1.y, r1.y, l(0.000000)
min r1.w, r1.y, l(127.000000)
mov r1.y, r1.x
round_ni r1.yz, r1.yywy  // zInt<0:[0f,127f],1:[1f,127f]>

#line 59
div r1.yz, r1.yyzy, l(0.000000, 32.000000, 32.000000, 0.000000)
frc r2.xy, r1.yzyy
mul r2.xz, r2.xxyx, l(32.000000, 0.000000, 32.000000, 0.000000)  // layerOffset<0:[0f,32f],2:[0f,32f]>

#line 60
round_ni r2.yw, r1.yyyz  // layerOffset<1:[0f,3f],3:[0f,3f]>

#line 61
mul r2.xyzw, r2.xyzw, l(0.031250, 0.250000, 0.031250, 0.250000)
add r0.xyzw, r0.xyzw, r2.xyzw  // uv_lerp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 62
frc r1.xyzw, r1.xxxx  // zBlend<0:[0f,1f],1:[0f,1f],2:[0f,1f],3:[0f,1f]>

#line 63
sample_indexable(texture2d)(float,float,float,float) r2.xyzw, r0.xyxx, t12.xyzw, s11  // c0<0:Inf,1:Inf,2:Inf,3:Inf>

#line 64
sample_indexable(texture2d)(float,float,float,float) r0.xyzw, r0.zwzz, t12.xyzw, s11  // c1<0:Inf,1:Inf,2:Inf,3:Inf>

#line 65
mov r3.xyzw, -r1.xyzw
add r3.xyzw, r3.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
mul r2.xyzw, r2.xyzw, r3.xyzw
mul r0.xyzw, r0.xyzw, r1.xyzw
add r0.xyzw, r0.xyzw, r2.xyzw  // fogColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 69
mov r1.x, cb2[25].y  // normalizeFactor<0>

#line 70
mul r0.xyz, r0.xyzx, r1.xxxx  // fogColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 71
mov r0.xyz, r0.xyzx  // GetVolumetricFog2D<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
mov r0.w, r0.w  // GetVolumetricFog2D<3:NaN:Inf>

#line 142
mov r0.xyzw, r0.xyzw  // GetVolumetricFog<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 18
mov r0.xyzw, r0.xyzw  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 299
mov r0.xyzw, r0.xyzw  // NFetchVolFog_fetchFog_outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 302
mov r1.xyz, v0.xyzx  // NComputeCloudColor_computeCloudColor_inColor<0,1,2>

#line 315
mov r0.xyzw, r0.xyzw  // NComputeCloudColor_computeCloudColor_inFogColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 303
mov r2.xyzw, v1.wxyz  // NComputeCloudColor_computeCloudColor_inAttribute1<3,0,1,2>

#line 304
mov r3.xyz, v2.zwxz  // NComputeCloudColor_computeCloudColor_inAttribute2<2,3,0>

#line 305
mov r4.xy, v3.xyxx  // NComputeCloudColor_computeCloudColor_inLightInfo<0,1>

#line 306
nop 
mov r1.xyz, r1.xyzx  // inColor<0,1,2>
mov r0.xyzw, r0.xyzw  // inFogColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mov r2.xyzw, r2.xyzw  // inAttribute1<3,0,1,2>
mov r3.xyz, r3.xyzx  // inAttribute2<2,3,0>
mov r4.xy, r4.xyxx  // inLightInfo<0,1>

#line 166
mov r3.xy, r3.xyxx  // inDomUV<0,1>

#line 167
mov r2.x, r2.x  // domeOpacity<0>

#line 171
add r3.xy, r3.xyxx, cb4[1].xyxx
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r3.xyxx, t0.xyzw, s10  // domeColor<0:Inf,1:Inf,2:Inf,3:Inf>

#line 176
mul r5.xyzw, r2.xxxx, r5.xyzw  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 180
mov r3.xy, r2.yzyy  // lowCylUV<0,1>

#line 184
mov r6.x, cb4[1].z
mov r6.y, l(0)
add r3.xy, r3.xyxx, r6.xyxx
sample_indexable(texture2d)(float,float,float,float) r6.xyzw, r3.xyxx, t1.xyzw, s10  // lowCylColor<0:Inf,1:Inf,2:Inf,3:Inf>

#line 189
mov r1.w, -r2.x
add r1.w, r1.w, l(1.000000)
mul r6.xyzw, r1.wwww, r6.xyzw
add r5.xyzw, r5.xyzw, r6.xyzw  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 194
mov r2.yw, r2.yyyw  // midCylUV<0,1>

#line 198
mov r3.x, cb4[1].w
mov r3.y, l(0)
add r2.xy, r2.ywyy, r3.xyxx
sample_indexable(texture2d)(float,float,float,float) r2.xyzw, r2.xyxx, t2.xyzw, s10  // midCylColor<0:Inf,1:Inf,2:Inf,3:Inf>

#line 204
mov r3.z, r3.z  // midCylOpacity<0>

#line 205
mul r2.xyzw, r2.xyzw, r3.zzzz  // midCylColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 206
mov r1.w, -r2.w
add r1.w, r1.w, l(1.000000)
mul r3.xyz, r1.wwww, r5.xyzx
mul r2.xyz, r2.wwww, r2.xyzx
add r2.xyz, r2.xyzx, r3.xyzx  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 207
add r1.w, r2.w, r5.w  // outColor<3:NaN:Inf>

#line 212
mov r4.x, r4.x  // lightBlendRate<0>

#line 213
mov r3.xyz, cb4[4].xyzx
mul r3.xyz, r4.xxxx, r3.xyzx
mov r2.w, -r4.x
add r2.w, r2.w, l(1.000000)
mul r2.xyz, r2.wwww, r2.xyzx
add r2.xyz, r2.xyzx, r3.xyzx  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 217
min r1.w, r1.w, l(1.000000)  // cloudAlpha<0:Inf:[-1.#INFf,1f]>

#line 218
mov r2.w, cb4[0].x  // luminance<0>

#line 221
add r3.x, r4.y, l(1.000000)
mul r2.w, r2.w, r3.x  // luminance<0:Inf>

#line 222
mul r2.w, r2.w, cb2[23].z  // luminance<0:NaN:Inf>

#line 226
mul r2.xyz, r2.wwww, r2.xyzx  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 229
mov r2.w, -r1.w
add r2.w, r2.w, l(1.000000)
mul r1.xyz, r1.xyzx, r2.wwww
mul r2.xyz, r1.wwww, r2.xyzx
add r1.xyz, r1.xyzx, r2.xyzx  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 235
nop 
mov r0.xyz, r0.xyzx  // linearRGB<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 24
ge r2.xyz, l(0.003131, 0.003131, 0.003131, 0.000000), r0.xyzx
movc r2.xyz, r2.xyzx, l(1.000000,1.000000,1.000000,0), l(0,0,0,0)  // mask<0:[-0f,1f],1:[-0f,1f],2:[-0f,1f]>

#line 25
mul r3.xyz, r0.xyzx, l(12.920000, 12.920000, 12.920000, 0.000000)
mul r3.xyz, r2.xyzx, r3.xyzx
mov r2.xyz, -r2.xyzx
add r2.xyz, r2.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
max r0.xyz, r0.xyzx, l(0.000010, 0.000010, 0.000010, 0.000000)
log r0.xyz, r0.xyzx
mul r0.xyz, r0.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
exp r0.xyz, r0.xyzx
mul r0.xyz, r0.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000)
add r0.xyz, r0.xyzx, l(-0.055000, -0.055000, -0.055000, 0.000000)
mul r0.xyz, r0.xyzx, r2.xyzx
add r0.xyz, r0.xyzx, r3.xyzx  // GammaCorrection<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 235
mov r0.xyz, r0.xyzx  // inFogColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 237
mul r1.xyz, r0.wwww, r1.xyzx
add r0.xyz, r0.xyzx, r1.xyzx  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 241
nop 
mov r1.xyz, cb4[5].xyzx  // params<0,1,2>
mov r0.xyz, r0.xyzx  // x<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 11
mov r2.xyz, r1.yyyy
ge r2.xzw, r2.xxyz, r0.xxyz
movc r2.xzw, r2.xxzw, l(1.000000,0,1.000000,1.000000), l(0,0,0,0)  // mask<0:[-0f,1f],1:[-0f,1f],2:[-0f,1f]>

#line 12
mul r3.xyz, r0.xyzx, r2.xzwx
mov r2.xzw, -r2.xxzw
add r2.xzw, r2.xxzw, l(1.000000, 0.000000, 1.000000, 1.000000)
add r0.xyz, r1.zzzz, r0.xyzx
mov r4.xyz, -r2.yyyy
add r0.xyz, r0.xyzx, r4.xyzx
mul r0.xyz, r0.xyzx, r1.xxxx
div r0.xyz, l(-1.000000, -1.000000, -1.000000, 0.000000), r0.xyzx
add r0.xyz, r1.zzzz, r0.xyzx
add r0.xyz, r2.yyyy, r0.xyzx
mul r0.xyz, r0.xyzx, r2.xzwx
add r0.xyz, r0.xyzx, r3.xyzx  // TppTonemap<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 241
mov r0.xyz, r0.xyzx  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 306
mov r0.xyz, r0.xyzx  // NComputeCloudColor_computeCloudColor_outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
mov r0.w, l(0)  // NComputeCloudColor_computeCloudColor_outColor<3: 0f>

#line 316
mov o0.xyzw, r0.xyzw  // outColor0<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3: 0f>

#line 319
mov o1.xyzw, r0.xyzw  // outColor1<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3: 0f>

#line 258
ret 
// Approximately 155 instruction slots used
