Microsoft (R) Direct3D Shader Compiler 10.1
Copyright (C) 2013 Microsoft. All rights reserved.

//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer cPSScene
// {
//
//   struct PSScene
//   {
//       
//       float4x4 m_projectionView;     // Offset:    0
//       float4x4 m_projection;         // Offset:   64
//       float4x4 m_view;               // Offset:  128
//       float4x4 m_shadowProjection;   // Offset:  192
//       float4x4 m_shadowProjection2;  // Offset:  256
//       float4 m_eyepos;               // Offset:  320
//       float4 m_projectionParam;      // Offset:  336
//       float4 m_viewportSize;         // Offset:  352
//       float4 m_exposure;             // Offset:  368
//       float4 m_fogParam[3];          // Offset:  384
//       float4 m_fogColor;             // Offset:  432
//       float4 m_cameraCenterOffset;   // Offset:  448
//       float4 m_shadowMapResolutions; // Offset:  464
//
//   } g_psScene;                       // Offset:    0 Size:   480
//
// }
//
// cbuffer cPSObject
// {
//
//   struct PSObject
//   {
//       
//       float4x4 m_viewWorld;          // Offset:    0
//       float4x4 m_world;              // Offset:   64
//       float4 m_useWeightCount;       // Offset:  128
//       float4 m_localParam[4];        // Offset:  144
//
//   } g_psObject;                      // Offset:    0 Size:   208
//
// }
//
// cbuffer cPSLight
// {
//
//   struct PSLight
//   {
//       
//       float4 m_lightParams[11];      // Offset:    0
//
//   } g_psLight;                       // Offset:    0 Size:   176
//
// }
//
// cbuffer cPSMaterial
// {
//
//   struct PSMaterial
//   {
//       
//       float4 m_materials[8];         // Offset:    0
//
//   } g_psMaterial;                    // Offset:    0 Size:   128
//
// }
//
// cbuffer cPSSystem
// {
//
//   struct PSSystem
//   {
//       
//       float4 m_param;                // Offset:    0
//       float4 m_renderInfo;           // Offset:   16
//       float4 m_renderBuffer;         // Offset:   32
//       float4 m_dominantLightDir;     // Offset:   48
//
//   } g_psSystem;                      // Offset:    0 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// g_samplerPoint_Wrap               sampler      NA          NA             s8      1 
// g_samplerPoint_Clamp              sampler      NA          NA             s9      1 
// g_samplerLinear_Wrap              sampler      NA          NA            s10      1 
// inDistortionTexture               texture  float4          2d             t0      1 
// inNoiseTexture                    texture  float4          2d             t1      1 
// inNormalTexture                   texture  float4          2d             t2      1 
// inMaterialTexture                 texture  float4          2d             t3      1 
// inHalfDepthTexture                texture  float4          2d            t13      1 
// cPSSystem                         cbuffer      NA          NA            cb0      1 
// cPSScene                          cbuffer      NA          NA            cb2      1 
// cPSLight                          cbuffer      NA          NA            cb3      1 
// cPSMaterial                       cbuffer      NA          NA            cb4      1 
// cPSObject                         cbuffer      NA          NA            cb5      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// COLOR                    0   xyzw        0     NONE   float       
// COLOR                    1   xyzw        1     NONE   float       
// SV_Position              0   xyzw        2      POS   float   xy  
// TEXCOORD                 0   xy          3     NONE   float       
// TEXCOORD                 1   xyz         4     NONE   float       
// TEXCOORD                 2   xyz         5     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xyzw        1   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB2[24], immediateIndexed
dcl_constantbuffer CB5[11], immediateIndexed
dcl_constantbuffer CB3[2], immediateIndexed
dcl_constantbuffer CB4[5], immediateIndexed
dcl_constantbuffer CB0[3], immediateIndexed
dcl_sampler s8, mode_default
dcl_sampler s9, mode_default
dcl_sampler s10, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t13
dcl_input_ps_siv linear noperspective v2.xy, position
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_temps 13

#line 260 "d:\work\master\git_clone\_intermediate\win64\TppShaders_dx11_win64\Release\Primitive_TppSandWind_ps.hlsl"
add r0.xy, v2.xyxx, l(-0.500000, -0.500000, 0.000000, 0.000000)  // inVPos<0,1>

#line 15
nop 

#line 19
nop 

#line 155
mov r1.xyz, cb5[9].xyzx  // GetSunLightDirection<0,1,2>

#line 19
mov r1.xyz, r1.xyzx  // outLightDir<0,1,2>

#line 20
nop 

#line 173
nop 

#line 122
mov r0.z, cb2[23].z  // GetCurrentExposureValue<0>

#line 173
mul r2.xyz, r0.zzzz, cb5[10].xyzx  // GetExposureAdjustedSunLightColor<0:Inf,1:Inf,2:Inf>

#line 20
mov r2.xyz, r2.xyzx  // outLightColor<0:Inf,1:Inf,2:Inf>

#line 15
mov r1.xyz, r1.xyzx  // NGetSunLightParam_sunLightParameters_outLightDir<0,1,2>
mov r2.xyz, r2.xyzx  // NGetSunLightParam_sunLightParameters_outLightColor<0:Inf,1:Inf,2:Inf>

#line 274
mov r0.xy, r0.xyxx  // NScreenToTextureCoordinate_textureCoordinate_inPixelPosition<0,1>

#line 275
nop 
mov r0.xy, r0.xyxx  // inPixelPosition<0,1>

#line 56
add r0.zw, r0.xxxy, l(0.000000, 0.000000, 0.496094, 0.496094)
mul r0.zw, r0.zzzw, cb0[2].zzzw  // outTexcoord<0:Inf,1:Inf>

#line 275
mov r0.zw, r0.zzzw  // NScreenToTextureCoordinate_textureCoordinate_outTexcoord<0:Inf,1:Inf>

#line 277
mov r0.zw, r0.zzzw  // NComputePrimitiveColor2_computePrimitiveColor_inBaseUV<0:Inf,1:Inf>

#line 278
mov r1.xyz, r1.xyzx  // NComputePrimitiveColor2_computePrimitiveColor_inSunDirection<0,1,2>

#line 279
mov r2.xyz, r2.xyzx  // NComputePrimitiveColor2_computePrimitiveColor_inSunColor<0:Inf,1:Inf,2:Inf>

#line 280
nop 
mov r0.zw, r0.zzzw  // inBaseUV<0:Inf,1:Inf>
mov r1.xyz, r1.xyzx  // inSunDirection<0,1,2>
mov r2.xyz, r2.xyzx  // inSunColor<0:Inf,1:Inf,2:Inf>

#line 102
mov r3.x, cb4[0].x  // textureRepetition<0>

#line 103
mov r1.w, cb4[0].y  // intensity<0>

#line 104
mov r2.w, cb4[0].z  // rotation<0>

#line 106
mov r3.z, cb4[1].x  // intervalDuration<0>

#line 107
mov r3.w, cb4[1].y  // phaseScale<0>

#line 108
mov r4.x, cb4[1].z  // amount<0>

#line 109
mov r4.y, cb4[1].w  // closeSandRelativeIntensity<0>

#line 110
mov r5.xyz, cb4[2].xyzx  // tonemapParam<0,1,2>

#line 111
mov r4.z, cb4[2].w  // time<0>

#line 112
mov r4.w, cb4[3].w  // closeSandRelativeVelocity<0>

#line 113
mov r6.xy, cb4[4].xyxx  // projectionWindDirection<0,1>

#line 114
mov r6.zw, cb4[4].zzzw  // projectionWindDirectionShifted<0,1>

#line 117
nop 
mov r0.zw, r0.zzzw  // inTexCoord<0:Inf,1:Inf>
mov r7.xy, cb2[21].zwzz  // projectionParameter<2,3>

#line 425
sample_l_indexable(texture2d)(float,float,float,float) r5.w, r0.zwzz, t13.yzwx, s9, l(0.000000)
mov r5.w, r5.w  // zOverW<0:Inf>

#line 431
nop 
mov r5.w, r5.w  // zOverW<0:Inf>
mov r7.xy, r7.xyxx  // proj<2,3>

#line 397
mov r7.y, -r7.y
add r5.w, r5.w, r7.y
div r5.w, r7.x, r5.w  // ReconstructViewZ<0:NaN:Inf>

#line 431
mov r5.w, r5.w  // ReconstructViewZFromTexture<0:NaN:Inf>

#line 117
mov r5.w, r5.w  // depth<0:NaN:Inf>

#line 122
nop 
mov r5.w, r5.w  // depth<0:NaN:Inf>
mov r0.xy, r0.xyxx  // inVPos<0,1>
mov r7.xy, cb0[1].xyxx  // viewportSize<0,1>
mov r7.zw, cb2[21].xxxy  // inProjectionParam<0,1>

#line 33
div r0.xy, r0.xyxx, r7.xyxx
mul r0.xy, r0.xyxx, l(2.000000, -2.000000, 0.000000, 0.000000)
add r0.xy, r0.xyxx, l(-1.000000, 1.000000, 0.000000, 0.000000)  // clipSpaceXY<0:NaN:Inf,1:NaN:Inf>

#line 35
mul r0.xy, r7.zwzz, r0.xyxx
mul r7.xy, r5.wwww, r0.xyxx  // viewPos<0:NaN:Inf,1:NaN:Inf>

#line 36
mov r7.z, r5.w  // viewPos<2:NaN:Inf>

#line 37
mov r7.xy, r7.xyxx  // CalculateViewPosition<0:NaN:Inf,1:NaN:Inf>
mov r7.z, r7.z  // CalculateViewPosition<2:NaN:Inf>

#line 122
mov r7.xyz, r7.xyzx  // positionVS<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 123
nop 
mov r7.xyz, r7.xyzx  // viewPos<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 43
nop 

#line 463
mov r8.x, cb2[8].x  // GetRowT<0>
mov r8.y, cb2[9].x  // GetRowT<1>
mov r8.z, cb2[10].x  // GetRowT<2>

#line 43
mov r8.xyz, r8.xyzx  // cameraWorldX<0,1,2>

#line 44
nop 

#line 463
mov r9.x, cb2[8].y  // GetRowT<0>
mov r9.y, cb2[9].y  // GetRowT<1>
mov r9.z, cb2[10].y  // GetRowT<2>

#line 44
mov r9.xyz, r9.xyzx  // cameraWorldY<0,1,2>

#line 45
nop 

#line 463
mov r10.x, cb2[8].z  // GetRowT<0>
mov r10.y, cb2[9].z  // GetRowT<1>
mov r10.z, cb2[10].z  // GetRowT<2>

#line 45
mov r10.xyz, r10.xyzx  // cameraWorldZ<0,1,2>

#line 46
nop 

#line 463
mov r11.x, cb2[8].w  // GetRowT<0>
mov r11.y, cb2[9].w  // GetRowT<1>
mov r11.z, cb2[10].w  // GetRowT<2>

#line 46
mov r11.xyz, -r11.xyzx  // cameraPos<0,1,2>

#line 48
add r11.xyz, r7.xyzx, r11.xyzx  // tmp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 49
dp3 r8.x, r8.xyzx, r11.xyzx  // worldPos<0:NaN:Inf>

#line 50
dp3 r8.y, r9.xyzx, r11.xyzx  // worldPos<1:NaN:Inf>

#line 51
dp3 r8.z, r10.xyzx, r11.xyzx  // worldPos<2:NaN:Inf>

#line 52
mov r8.x, r8.x  // CalculateWorldPosition<0:NaN:Inf>
mov r8.y, r8.y  // CalculateWorldPosition<1:NaN:Inf>
mov r8.z, r8.z  // CalculateWorldPosition<2:NaN:Inf>

#line 123
mov r8.xyz, r8.xyzx  // positionWS<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 126
nop 

#line 158
nop 
sample_l_indexable(texture2d)(float,float,float,float) r9.xyz, r0.zwzz, t2.xyzw, s9, l(0.000000)
mov r9.xyz, r9.xyzx  // encodeNormal<0:Inf,1:Inf,2:Inf>

#line 132
mul r0.xy, r9.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000)
add r0.xy, r0.xyxx, l(-1.000000, -1.000000, 0.000000, 0.000000)  // viewSpaceNormal<0:Inf,1:Inf>

#line 133
mul r7.w, r9.z, r9.z
mul r7.w, r7.w, l(2.000000)
add r9.z, r7.w, l(-1.000000)  // viewSpaceNormal<2:NaN:Inf>

#line 134
mul r7.w, r9.z, r9.z
mov r7.w, -r7.w
add r7.w, r7.w, l(1.000000)  // oneMinusZz<0:NaN:Inf>

#line 135
mul r10.xy, r0.xyxx, r7.wwww
dp2 r0.x, r0.xyxx, r0.xyxx
mul r0.x, r0.x, r7.w
add r0.x, r0.x, l(0.000000)
rsq r0.x, r0.x
mul r9.xy, r0.xxxx, r10.xyxx  // viewSpaceNormal<0:NaN:Inf,1:NaN:Inf>

#line 145
mov r9.xy, r9.xyxx  // DecodeViewSpaceNormal<0:NaN:Inf,1:NaN:Inf>
mov r9.z, r9.z  // DecodeViewSpaceNormal<2:NaN:Inf>

#line 158
mov r9.xyz, r9.xyzx  // ReconstructViewSpaceNormal<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 126
mov r9.xyz, r9.xyzx  // normalVS<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 127
nop 
mov r9.xyz, r9.xyzx  // viewPos<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 58
nop 

#line 463
mov r10.x, cb2[8].x  // GetRowT<0>
mov r10.y, cb2[9].x  // GetRowT<1>
mov r10.z, cb2[10].x  // GetRowT<2>

#line 58
mov r10.xyz, r10.xyzx  // cameraWorldX<0,1,2>

#line 59
nop 

#line 463
mov r11.x, cb2[8].y  // GetRowT<0>
mov r11.y, cb2[9].y  // GetRowT<1>
mov r11.z, cb2[10].y  // GetRowT<2>

#line 59
mov r11.xyz, r11.xyzx  // cameraWorldY<0,1,2>

#line 60
nop 

#line 463
mov r12.x, cb2[8].z  // GetRowT<0>
mov r12.y, cb2[9].z  // GetRowT<1>
mov r12.z, cb2[10].z  // GetRowT<2>

#line 60
mov r12.xyz, r12.xyzx  // cameraWorldZ<0,1,2>

#line 62
mov r9.xyz, r9.xyzx  // tmp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 63
dp3 r10.x, r10.xyzx, r9.xyzx  // worldDir<0:NaN:Inf>

#line 64
dp3 r10.y, r11.xyzx, r9.xyzx  // worldDir<1:NaN:Inf>

#line 65
dp3 r10.z, r12.xyzx, r9.xyzx  // worldDir<2:NaN:Inf>

#line 66
mov r10.x, r10.x  // CalculateWorldDirection<0:NaN:Inf>
mov r10.y, r10.y  // CalculateWorldDirection<1:NaN:Inf>
mov r10.z, r10.z  // CalculateWorldDirection<2:NaN:Inf>

#line 127
mov r10.xyz, r10.xyzx  // normalWS<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 131
nop 

#line 26
mul r9.xyz, r7.xyzx, l(0.002000, 0.002000, 0.002000, 0.000000)  // distance<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 27
dp3 r0.x, r9.xyzx, r9.xyzx
mov r0.x, -r0.x
add r0.x, r0.x, l(1.000000)
max r0.x, r0.x, l(0.000000)
min r0.x, r0.x, l(1.000000)  // attenuation<0:[0f,1f]>

#line 28
mov r0.x, r0.x  // Attenuation<0:[0f,1f]>

#line 131
mov r0.x, r0.x  // attenuation<0:[0f,1f]>

#line 134
sample_l_indexable(texture2d)(float,float,float,float) r0.y, r0.zwzz, t3.xzyw, s8, l(0.000000)
mov r0.y, r0.y  // materialId<0:Inf>

#line 135
ge r0.z, l(0.076471), r0.y
ge r0.y, r0.y, l(0.080392)
or r0.y, r0.y, r0.z
movc r0.x, r0.y, l(0), r0.x  // attenuation<0:[-0f,1f]>

#line 139
sincos null, r9.x, r2.w  // generalDirection<0:[-1f,1f]>

#line 140
sincos r9.y, null, r2.w  // generalDirection<1:[-1f,1f]>

#line 143
mov r11.y, l(0)
mov r11.x, r9.x
mov r11.z, r9.y
dp3 r0.y, r11.xyzx, r11.xyzx
rsq r0.y, r0.y
mul r0.yzw, r0.yyyy, r11.xxyz
dp3 r0.y, r10.xyzx, r0.yzwy  // NW<0:NaN:Inf>

#line 145
mul r0.y, r0.y, l(0.500000)
add r0.y, r0.y, l(0.500000)
max r0.y, r0.y, l(0.000000)
min r0.y, r0.y, l(1.000000)  // normalAtenuation<0:[0f,1f]>

#line 148
mul r3.y, r3.x, l(1.200000)
mul r0.zw, r3.xxxy, r8.xxxz  // uv<0:NaN:Inf,1:NaN:Inf>

#line 151
nop 

#line 26
mul r7.xyz, r7.xyzx, l(0.020000, 0.020000, 0.020000, 0.000000)  // distance<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 27
dp3 r3.x, r7.xyzx, r7.xyzx
mov r3.x, -r3.x
add r3.x, r3.x, l(1.000000)
max r3.x, r3.x, l(0.000000)
min r3.x, r3.x, l(1.000000)  // attenuation<0:[0f,1f]>

#line 28
mov r3.x, r3.x  // Attenuation<0:[0f,1f]>

#line 151
mov r3.x, r3.x  // sandGrainAttenuation<0:[0f,1f]>

#line 152
mov r3.y, -r3.x
add r3.y, r3.y, l(1.000000)  // invSandGrainAttenuation<0:[0f,1f]>

#line 155
mul r7.xy, r0.zwzz, l(0.100000, 0.100000, 0.000000, 0.000000)
mul r7.zw, r6.xxxy, l(0.000000, 0.000000, 0.200000, 0.200000)
add r7.xy, r7.zwzz, r7.xyxx
sample_l_indexable(texture2d)(float,float,float,float) r7.x, r7.xyxx, t0.zxyw, s10, l(2.000000)
mov r7.x, r7.x  // mainMask<0:Inf>

#line 159
add r2.w, r2.w, l(-0.330000)
sincos null, r11.x, r2.w  // rotatedDirection<0:[-1f,1f]>

#line 160
sincos r11.y, null, r2.w  // rotatedDirection<1:[-1f,1f]>

#line 163
mul r2.w, r3.y, r3.w  // phaseScale<0>

#line 166
mul r3.w, r3.z, r7.x
add r3.w, r3.w, r4.z
div r12.x, r3.w, r3.z  // timeInt<0:NaN:Inf>

#line 168
sample_l_indexable(texture2d)(float,float,float,float) r3.z, r0.zwzz, t0.yzxw, s10, l(2.000000)
mul r3.zw, r2.wwww, r3.zzzz  // offsetPhase<0:NaN:Inf,0:NaN:Inf>

#line 172
add r12.y, r12.x, l(0.500000)
add r3.zw, r3.zzzw, r12.xxxy
frc r3.zw, r3.zzzw  // fTime<0:NaN,1:NaN>

#line 174
mul r7.yz, r0.zzwz, l(0.000000, 0.350000, 0.350000, 0.000000)
mul r9.zw, r9.xxxy, l(0.000000, 0.000000, 0.500000, 0.500000)
mov r9.zw, -r9.zzzw
add r7.yz, r7.yyzy, r9.zzwz
mul r9.zw, r3.zzzz, r9.xxxy
add r7.yz, r7.yyzy, r9.zzwz  // flowUV1<0:NaN:Inf,1:NaN:Inf>

#line 175
mul r9.zw, r0.zzzw, l(0.000000, 0.000000, 0.420000, 0.420000)
mul r11.zw, r11.xxxy, l(0.000000, 0.000000, 0.500000, 0.500000)
mov r11.zw, -r11.zzzw
add r9.zw, r9.zzzw, r11.zzzw
mul r3.zw, r3.wwww, r11.xxxy
add r3.zw, r3.zzzw, r9.zzzw  // flowUV2<0:NaN:Inf,1:NaN:Inf>

#line 176
sample_l_indexable(texture2d)(float,float,float,float) r9.zw, r7.yzyy, t0.zwxy, s10, l(2.000000)
mov r9.zw, r9.zzzw  // tx1<0:Inf,1:Inf>

#line 177
sample_l_indexable(texture2d)(float,float,float,float) r11.xy, r3.zwzz, t0.xyzw, s10, l(2.000000)
mov r11.xy, r11.xyxx  // tx2<0:Inf,1:Inf>

#line 178
mul r9.zw, r9.zzzw, l(0.000000, 0.000000, 0.100000, 0.100000)
add r7.yz, r7.yyzy, r9.zzwz
sample_l_indexable(texture2d)(float,float,float,float) r7.yz, r7.yzyy, t0.zxyw, s10, l(2.000000)
mov r7.yz, r7.yyzy  // tx1<0:Inf,1:Inf>

#line 179
mul r9.zw, r11.xxxy, l(0.000000, 0.000000, 0.100000, 0.100000)
add r3.zw, r3.zzzw, r9.zzzw
sample_l_indexable(texture2d)(float,float,float,float) r3.zw, r3.zwzz, t0.zwxy, s10, l(2.000000)
mov r3.zw, r3.zzzw  // tx2<0:Inf,1:Inf>

#line 182
mov r2.w, -r7.x
add r2.w, r2.w, l(1.000000)  // invMainMask<0:Inf>

#line 183
mul r4.z, r2.w, l(0.200000)
add r4.z, r4.z, r7.x
mul r9.zw, r4.zzzz, r7.yyyz
mul r4.z, r7.x, l(0.200000)
add r2.w, r2.w, r4.z
mul r7.xw, r2.wwww, r3.zzzw
frc r2.w, r12.x
mul r2.w, r2.w, l(2.000000)
add r2.w, r2.w, l(-1.000000)
mov r4.z, -r2.w
max r2.w, r2.w, r4.z
mov r11.xy, -r9.zwzz
add r7.xw, r7.xxxw, r11.xxxy
mul r7.xw, r2.wwww, r7.xxxw
add r7.xw, r7.xxxw, r9.zzzw  // flowPattern<0:NaN:Inf,1:NaN:Inf>

#line 186
mul r2.w, r7.x, r7.x
max r2.w, r2.w, l(0.000010)
log r2.w, r2.w
mul r2.w, r2.w, r4.x
exp r2.w, r2.w  // mainWindPattern<0:NaN:Inf>

#line 189
mul r0.zw, r0.zzzw, l(0.000000, 0.000000, 5.000000, 5.000000)  // positionWSXZScaled<0:NaN:Inf,1:NaN:Inf>

#line 190
mul r4.xz, r7.yyzy, l(0.150000, 0.000000, 0.150000, 0.000000)
add r4.xz, r0.zzwz, r4.xxzx
mul r7.yz, r4.wwww, l(0.000000, 16.000000, 16.000000, 0.000000)
mul r6.xy, r6.xyxx, r7.yzyy
add r4.xz, r4.xxzx, r6.xxyx
sample_indexable(texture2d)(float,float,float,float) r4.x, r4.xzxx, t1.xyzw, s8
mov r4.x, r4.x  // sandGrainPattern<0:Inf>

#line 192
mul r3.zw, r3.zzzw, l(0.000000, 0.000000, 0.500000, 0.500000)
add r0.zw, r0.zzzw, r3.zzzw
mul r3.zw, r4.wwww, l(0.000000, 0.000000, 4.000000, 4.000000)
mul r3.zw, r3.zzzw, r6.zzzw
add r0.zw, r0.zzzw, r3.zzzw
sample_indexable(texture2d)(float,float,float,float) r0.z, r0.zwzz, t1.yzxw, s8
mov r0.z, r0.z  // sandGrainPattern2<0:Inf>

#line 199
nop 

#line 174
nop 

#line 78
mov r6.xyz, cb2[20].xyzx  // GetEyePosition<0,1,2>

#line 174
mov r6.xyz, r6.xyzx  // GetCameraEyePosition<0,1,2>

#line 199
mov r6.xyz, r6.xyzx  // cameraPos<0,1,2>

#line 200
mov r6.xyz, -r6.xyzx
add r6.xyz, r6.xyzx, r8.xyzx
dp3 r0.w, r6.xyzx, r6.xyzx
rsq r0.w, r0.w
mul r3.zw, r0.wwww, r6.xxxz  // viewWS<0:NaN:Inf,2:NaN:Inf>

#line 201
dp2 r0.w, r3.zwzz, r9.xyxx
mov r3.z, -r0.w
max r0.w, r0.w, r3.z
max r0.w, r0.w, l(0.000000)
min r0.w, r0.w, l(1.000000)  // VD<0:[0f,1f]>

#line 202
log r0.w, r0.w
mul r0.w, r0.w, l(16.000000)
exp r0.w, r0.w  // VD<0:[0f,1f]>

#line 203
mul r0.w, r3.y, r0.w
mov r0.w, -r0.w
add r0.w, r0.w, l(1.000000)
mul r0.x, r0.w, r0.x  // attenuation<0:[0f,1f]>

#line 207
dp3 r0.w, r1.xyzx, r10.xyzx
max r0.w, r0.w, l(0.000000)
min r0.w, r0.w, l(1.000000)  // LN<0:[0f,1f]>

#line 210
dp3 r1.x, r10.xzyx, l(0.000000, 0.000000, 1.000000, 0.000000)  // fT<0:NaN:Inf>

#line 211
nop 

#line 283
mov r3.yzw, cb3[0].xxyz  // GetHemisphereAmbientLightFactor0<0,1,2>

#line 211
mov r3.yzw, r3.yyzw  // c0<0,1,2>

#line 212
nop 

#line 291
mov r6.xyz, cb3[1].xyzx  // GetHemisphereAmbientLightFactor1<0,1,2>

#line 212
mov r6.xyz, r6.xyzx  // c1<0,1,2>

#line 213
mul r1.xyz, r1.xxxx, r3.yzwy
add r1.xyz, r6.xyzx, r1.xyzx  // ambientContribution<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 214
mul r3.yzw, r1.wwww, l(0.000000, 1.000000, 0.500000, 0.150000)
mul r2.xyz, r2.xyzx, r0.wwww
add r1.xyz, r1.xyzx, r2.xyzx
mul r1.xyz, r1.xyzx, r3.yzwy  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 216
mov r0.w, -r0.y
add r0.w, r0.w, l(1.250000)
max r0.w, r0.w, l(0.000000)
min r0.w, r0.w, l(1.000000)
mul r0.w, r0.w, r3.x  // sandGrainAttenuation<0:[0f,1f]>

#line 218
mul r2.x, r0.y, r2.w  // farAwaySand<0:NaN:Inf>

#line 220
mul r2.y, r7.x, l(0.500000)
mul r0.y, r0.y, r7.w
mov r0.y, -r0.y
add r0.y, r0.y, r7.w
mul r0.y, r0.y, r2.y  // downCloseSand<0:NaN:Inf>

#line 221
mul r2.y, r4.x, r2.x  // upCloseSand<0:NaN:Inf>

#line 222
mul r2.z, r4.y, l(1.500000)
add r0.y, r0.y, r2.y
mul r0.y, r0.y, r2.z
mul r0.y, r0.z, r0.y  // closeSand<0:NaN:Inf>

#line 224
mov r0.z, -r2.x
add r0.y, r0.z, r0.y
mul r0.y, r0.y, r0.w
add r0.y, r0.y, r2.x  // outColor<3:NaN:Inf>

#line 225
mul r0.x, r0.x, l(0.500000)
max r0.z, r1.w, l(0.000000)
min r0.z, r0.z, l(1.000000)
mul r0.x, r0.z, r0.x
mul r0.x, r0.x, r0.y  // outColor<3:NaN:Inf>

#line 228
add r0.y, r5.w, l(-1.000000)
mul r0.y, r0.y, l(0.500000)
max r0.y, r0.y, l(0.000000)
min r0.y, r0.y, l(1.000000)
mul r0.w, r0.y, r0.x  // outColor<3:NaN:Inf>

#line 231
nop 
mov r5.xyz, r5.xyzx  // params<0,1,2>
mov r1.xyz, r1.xyzx  // x<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 11
mov r2.xyz, r5.yyyy
ge r2.xzw, r2.xxyz, r1.xxyz
movc r2.xzw, r2.xxzw, l(1.000000,0,1.000000,1.000000), l(0,0,0,0)  // mask<0:[-0f,1f],1:[-0f,1f],2:[-0f,1f]>

#line 12
mul r3.xyz, r1.xyzx, r2.xzwx
mov r2.xzw, -r2.xxzw
add r2.xzw, r2.xxzw, l(1.000000, 0.000000, 1.000000, 1.000000)
add r1.xyz, r5.zzzz, r1.xyzx
mov r4.xyz, -r2.yyyy
add r1.xyz, r1.xyzx, r4.xyzx
mul r1.xyz, r1.xyzx, r5.xxxx
div r1.xyz, l(-1.000000, -1.000000, -1.000000, 0.000000), r1.xyzx
add r1.xyz, r5.zzzz, r1.xyzx
add r1.xyz, r2.yyyy, r1.xyzx
mul r1.xyz, r1.xyzx, r2.xzwx
add r1.xyz, r1.xyzx, r3.xyzx  // TppTonemap<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 231
mov r1.xyz, r1.xyzx  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 232
nop 
mov r1.xyz, r1.xyzx  // linearRGB<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 24
ge r2.xyz, l(0.003131, 0.003131, 0.003131, 0.000000), r1.xyzx
movc r2.xyz, r2.xyzx, l(1.000000,1.000000,1.000000,0), l(0,0,0,0)  // mask<0:[-0f,1f],1:[-0f,1f],2:[-0f,1f]>

#line 25
mul r3.xyz, r1.xyzx, l(12.920000, 12.920000, 12.920000, 0.000000)
mul r3.xyz, r2.xyzx, r3.xyzx
mov r2.xyz, -r2.xyzx
add r2.xyz, r2.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
max r1.xyz, r1.xyzx, l(0.000010, 0.000010, 0.000010, 0.000000)
log r1.xyz, r1.xyzx
mul r1.xyz, r1.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
exp r1.xyz, r1.xyzx
mul r1.xyz, r1.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000)
add r1.xyz, r1.xyzx, l(-0.055000, -0.055000, -0.055000, 0.000000)
mul r1.xyz, r1.xyzx, r2.xyzx
add r1.xyz, r1.xyzx, r3.xyzx  // GammaCorrection<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 232
mov r1.xyz, r1.xyzx  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 235
mul r0.xyz, r0.wwww, r1.xyzx  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 280
mov r0.xyz, r0.xyzx  // NComputePrimitiveColor2_computePrimitiveColor_outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
mov r0.w, r0.w  // NComputePrimitiveColor2_computePrimitiveColor_outColor<3:NaN:Inf>

#line 286
mov o0.xyzw, r0.xyzw  // outColor0<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 288
mov o1.xyzw, r0.xyzw  // outColor1<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 248
ret 
// Approximately 370 instruction slots used
