Microsoft (R) Direct3D Shader Compiler 10.1
Copyright (C) 2013 Microsoft. All rights reserved.

//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer cPSScene
// {
//
//   struct PSScene
//   {
//       
//       float4x4 m_projectionView;     // Offset:    0
//       float4x4 m_projection;         // Offset:   64
//       float4x4 m_view;               // Offset:  128
//       float4x4 m_shadowProjection;   // Offset:  192
//       float4x4 m_shadowProjection2;  // Offset:  256
//       float4 m_eyepos;               // Offset:  320
//       float4 m_projectionParam;      // Offset:  336
//       float4 m_viewportSize;         // Offset:  352
//       float4 m_exposure;             // Offset:  368
//       float4 m_fogParam[3];          // Offset:  384
//       float4 m_fogColor;             // Offset:  432
//       float4 m_cameraCenterOffset;   // Offset:  448
//       float4 m_shadowMapResolutions; // Offset:  464
//
//   } g_psScene;                       // Offset:    0 Size:   480
//
// }
//
// cbuffer cPSObject
// {
//
//   struct PSObject
//   {
//       
//       float4x4 m_viewWorld;          // Offset:    0
//       float4x4 m_world;              // Offset:   64
//       float4 m_useWeightCount;       // Offset:  128
//       float4 m_localParam[4];        // Offset:  144
//
//   } g_psObject;                      // Offset:    0 Size:   208
//
// }
//
// cbuffer cPSMaterial
// {
//
//   struct PSMaterial
//   {
//       
//       float4 m_materials[8];         // Offset:    0
//
//   } g_psMaterial;                    // Offset:    0 Size:   128
//
// }
//
// cbuffer cPSSystem
// {
//
//   struct PSSystem
//   {
//       
//       float4 m_param;                // Offset:    0
//       float4 m_renderInfo;           // Offset:   16
//       float4 m_renderBuffer;         // Offset:   32
//       float4 m_dominantLightDir;     // Offset:   48
//
//   } g_psSystem;                      // Offset:    0 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// g_samplerPoint_Clamp              sampler      NA          NA             s9      1 
// g_samplerLinear_Wrap              sampler      NA          NA            s10      1 
// g_samplerLinear_Clamp             sampler      NA          NA            s11      1 
// g_samplerAnisotropic_Wrap         sampler      NA          NA            s12      1 
// inGradientTexture                 texture  float4          2d             t1      1 
// inWhitecapTexture1                texture  float4          2d             t2      1 
// inFoamTexture                     texture  float4          2d             t3      1 
// inNormalDetailTexture             texture  float4          2d             t4      1 
// inFoamTexture2                    texture  float4          2d             t5      1 
// g_tex_fog                         texture  float4          2d            t12      1 
// inDepthTexture                    texture  float4          2d            t13      1 
// cPSSystem                         cbuffer      NA          NA            cb0      1 
// cPSScene                          cbuffer      NA          NA            cb2      1 
// cPSMaterial                       cbuffer      NA          NA            cb4      1 
// cPSObject                         cbuffer      NA          NA            cb5      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xy  
// TEXCOORD                 0   xyz         1     NONE   float   xyz 
// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xyzw        1   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB2[26], immediateIndexed
dcl_constantbuffer CB5[10], immediateIndexed
dcl_constantbuffer CB4[8], immediateIndexed
dcl_constantbuffer CB0[3], immediateIndexed
dcl_sampler s9, mode_default
dcl_sampler s10, mode_default
dcl_sampler s11, mode_default
dcl_sampler s12, mode_default
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t4
dcl_resource_texture2d (float,float,float,float) t5
dcl_resource_texture2d (float,float,float,float) t12
dcl_resource_texture2d (float,float,float,float) t13
dcl_input_ps_siv linear noperspective v0.xy, position
dcl_input_ps linear v1.xyz
dcl_input_ps linear v2.xyzw
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_temps 19

#line 536 "d:\work\master\git_clone\_intermediate\win64\TppShaders_dx11_win64\Release\Primitive_TppFourierOceanLQ_ps.hlsl"
add r0.zw, v0.xxxy, l(0.000000, 0.000000, -0.500000, -0.500000)  // inVPos<0,1>

#line 575
mov r0.xyzw, r0.zwzw  // NScreenToClipCoordinate_screenToClipcoord_inPixelPosition<0,1,0,1>

#line 576
nop 
mov r1.xyzw, r0.xyzw  // inPixelPosition<0,1,0,1>

#line 72
div r1.xyzw, r1.xyzw, cb0[1].xyxy  // outClipPosition<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>

#line 73
mul r1.xyzw, r1.xyzw, l(2.000000, -2.000000, 2.000000, -2.000000)
add r1.xyzw, r1.xyzw, l(-1.000000, 1.000000, -1.000000, 1.000000)  // outClipPosition<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>

#line 576
mov r1.xyzw, r1.xyzw  // NScreenToClipCoordinate_screenToClipcoord_outClipPosition<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>
mov r1.xyzw, r1.xyzw  // NFetchVolFog_fetchFog_inClipPos<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>

#line 577
mov r0.z, v1.z  // NFetchVolFog_fetchFog_inViewZ<0>

#line 578
nop 
mov r1.xyzw, r1.xyzw  // inClipPos<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>
mov r0.z, r0.z  // inViewZ<0>

#line 18
nop 
mov r1.xyzw, r1.xyzw  // inClipPos<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>
mov r0.z, r0.z  // inViewZ<0>

#line 142
nop 
mov r1.xyzw, r1.xyzw  // inClipPos<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>
mov r0.w, r0.z  // inViewZ<0>

#line 50
nop 
mov r0.w, r0.w  // inViewZ<0>

#line 27
mov r2.x, cb2[25].x  // invLogFarDistance<0>

#line 30
log r0.w, r0.w
mul r0.w, r0.w, r2.x  // EncodeFogCameraZ<0:NaN:Inf>

#line 50
mov r0.w, r0.w  // zEncoded<0:NaN:Inf>

#line 51
max r0.w, r0.w, l(0.000000)
min r0.w, r0.w, l(1.000000)  // zEncoded<0:[0f,1f]>

#line 52
mul r0.w, r0.w, l(127.000000)  // zEncoded<0:[0f,127f]>

#line 56
mul r1.xyzw, r1.xyzw, l(0.014648, 0.123047, 0.014648, 0.123047)
add r1.xyzw, r1.xyzw, l(0.015625, 0.125000, 0.015625, 0.125000)  // uv<0:NaN:Inf,1:NaN:Inf,0:NaN:Inf,1:NaN:Inf>

#line 57
add r2.x, r0.w, l(1.000000)
max r2.x, r2.x, l(0.000000)
min r2.w, r2.x, l(127.000000)
mov r2.y, r0.w
round_ni r2.xy, r2.ywyy  // zInt<0:[0f,127f],1:[1f,127f]>

#line 59
div r2.xy, r2.xyxx, l(32.000000, 32.000000, 0.000000, 0.000000)
frc r2.zw, r2.xxxy
mul r3.xz, r2.zzwz, l(32.000000, 0.000000, 32.000000, 0.000000)  // layerOffset<0:[0f,32f],2:[0f,32f]>

#line 60
round_ni r3.yw, r2.xxxy  // layerOffset<1:[0f,3f],3:[0f,3f]>

#line 61
mul r2.xyzw, r3.xyzw, l(0.031250, 0.250000, 0.031250, 0.250000)
add r1.xyzw, r1.xyzw, r2.xyzw  // uv_lerp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 62
frc r2.xyzw, r0.wwww  // zBlend<0:[0f,1f],1:[0f,1f],2:[0f,1f],3:[0f,1f]>

#line 63
sample_indexable(texture2d)(float,float,float,float) r3.xyzw, r1.xyxx, t12.xyzw, s11  // c0<0:Inf,1:Inf,2:Inf,3:Inf>

#line 64
sample_indexable(texture2d)(float,float,float,float) r1.xyzw, r1.zwzz, t12.xyzw, s11  // c1<0:Inf,1:Inf,2:Inf,3:Inf>

#line 65
mov r4.xyzw, -r2.xyzw
add r4.xyzw, r4.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
mul r3.xyzw, r3.xyzw, r4.xyzw
mul r1.xyzw, r1.xyzw, r2.xyzw
add r1.xyzw, r1.xyzw, r3.xyzw  // fogColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 69
mov r0.w, cb2[25].y  // normalizeFactor<0>

#line 70
mul r1.xyz, r0.wwww, r1.xyzx  // fogColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 71
mov r1.xyz, r1.xyzx  // GetVolumetricFog2D<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
mov r1.w, r1.w  // GetVolumetricFog2D<3:NaN:Inf>

#line 142
mov r1.xyzw, r1.xyzw  // GetVolumetricFog<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 18
mov r1.xyzw, r1.xyzw  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 578
mov r1.xyzw, r1.xyzw  // NFetchVolFog_fetchFog_outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 15
nop 

#line 19
nop 

#line 155
mov r2.xyz, cb5[9].xzyx  // GetSunLightDirection<0,2,1>

#line 19
mov r2.xyz, r2.xyzx  // outLightDir<0,2,1>

#line 20
nop 

#line 173
nop 

#line 15
mov r2.xyz, r2.xyzx  // NGetSunLightParam_sun_outLightDir<0,2,1>

#line 564
mov r0.xy, r0.xyxx  // NScreenToTextureCoordinate_textureCoordinate_inPixelPosition<0,1>

#line 565
nop 
mov r0.xy, r0.xyxx  // inPixelPosition<0,1>

#line 56
add r0.xy, r0.xyxx, l(0.496094, 0.496094, 0.000000, 0.000000)
mul r0.xy, r0.xyxx, cb0[2].zwzz  // outTexcoord<0:Inf,1:Inf>

#line 565
mov r0.xy, r0.xyxx  // NScreenToTextureCoordinate_textureCoordinate_outTexcoord<0:Inf,1:Inf>

#line 573
nop 

#line 273
nop 

#line 472
nop 

#line 480
nop 

#line 582
mov r3.xy, v1.xyxx  // NCalculate_computePrimitiveColor_inUv<0,1>

#line 580
mov r4.xyz, v2.xyzx  // NCalculate_computePrimitiveColor_inWorldPosition<0,1,2>

#line 581
mov r0.w, v2.w  // NCalculate_computePrimitiveColor_inWindDirectionAttenuation<0>

#line 587
mov r2.xyz, r2.xyzx  // NCalculate_computePrimitiveColor_inSunDirection<0,2,1>

#line 588
mov r1.xyzw, r1.xyzw  // NCalculate_computePrimitiveColor_inFogColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 584
mov r0.xy, r0.xyxx  // NCalculate_computePrimitiveColor_inScreenUV<0:Inf,1:Inf>

#line 600
nop 
mov r3.xy, r3.xyxx  // inUv<0,1>
mov r4.xyz, r4.xyzx  // inWorldPosition<0,1,2>
mov r0.w, r0.w  // inWindDirectionAttenuation<0>
mov r2.xyz, r2.xyzx  // inSunDirection<0,2,1>
mov r1.xyzw, r1.xyzw  // inFogColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mov r0.xy, r0.xyxx  // inScreenUV<0:Inf,1:Inf>

#line 264
mov r5.w, l(78.125000)  // texelLength_x2<0: 78.125f>

#line 266
mov r3.zw, cb4[0].xxxy  // perlinMovement<0,1>

#line 267
mov r2.w, cb4[0].w  // screen<0>

#line 268
mov r4.w, cb4[1].z  // foamVelocity<0>

#line 269
mul r6.xy, cb4[2].yyyy, l(0.620000, 0.890000, 0.000000, 0.000000)  // farProjectionScale<0:[-2.10975e+038f,2.10975e+038f],1:[-3.02851e+038f,3.02851e+038f]>

#line 270
mov r7.xyz, cb4[3].xyzx  // inSunDirectionFromAtmosphere<0,1,2>

#line 271
mov r8.xyz, cb4[4].xyzx  // tonemapParam<0,1,2>

#line 272
mov r6.z, cb4[4].w  // foamAmount<0>

#line 273
mov r6.w, cb4[5].x  // patchBlendBegin<0>

#line 274
mov r7.w, cb4[5].y  // patchBlendEnd<0>

#line 275
mov r9.x, cb4[5].z  // reflectionPower<0>

#line 276
mov r8.w, cb4[5].w  // specularIntensityModifier<0>

#line 277
mov r9.w, cb4[6].x  // sunsetSunriseStrenght<0>

#line 278
mov r9.y, cb4[6].y  // normalizationFactor<0>

#line 279
mov r9.z, cb4[6].z  // normalizationFactor2<0>

#line 280
mov r10.x, cb4[6].w  // cameraVelocity<0>

#line 281
mul r10.yzw, cb2[23].zzzz, cb4[7].xxyz  // inSunColor<0:Inf,1:Inf,2:Inf>

#line 284
nop 

#line 78
mov r11.xyz, cb2[20].xyzx  // GetEyePosition<0,1,2>

#line 284
mov r11.xyz, -r11.xyzx
add r4.xyz, r4.xyzx, r11.xyzx  // inEyeDirection<0:Inf,1:Inf,2:Inf>

#line 285
dp3 r11.x, r4.xyzx, r4.xyzx
rsq r11.x, r11.x
mul r4.xyz, r4.xyzx, r11.xxxx  // inEyeDirection<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 288
mov r6.w, -r6.w
add r6.w, r0.z, r6.w
div r6.w, r6.w, r7.w  // blendFactor<0:NaN:Inf>

#line 289
mov r6.w, -r6.w
add r6.w, r6.w, l(1.000000)
max r6.w, r6.w, l(0.000000)
min r6.w, r6.w, l(1.000000)  // blendFactor<0:[0f,1f]>

#line 291
mul r0.w, r0.w, l(0.650000)
add r0.w, r0.w, l(0.350000)
mul r0.w, r0.w, r6.w  // blendFactor<0:[-2.21184e+038f,2.21184e+038f]>

#line 293
div r6.w, r0.z, l(5000.000000)
mov r6.w, -r6.w
add r6.w, r6.w, l(1.000000)  // invertedCompletRange<0:[-6.80565e+034f,6.80565e+034f]>

#line 296
mul r11.xy, r3.xyxx, r6.xxxx  // uv0<0:Inf,1:Inf>

#line 297
mul r6.xy, r3.yxyy, r6.yyyy  // uv1<0:Inf,1:Inf>

#line 298
sample_indexable(texture2d)(float,float,float,float) r11.zw, r11.xyxx, t1.zwxy, s10
mov r11.zw, r11.zzzw  // grad0<0:Inf,1:Inf>

#line 299
sample_indexable(texture2d)(float,float,float,float) r6.xy, r6.xyxx, t1.xyzw, s10
mov r6.xy, r6.xyxx  // grad1<0:Inf,1:Inf>

#line 300
mul r11.zw, r11.zzzw, l(0.000000, 0.000000, 0.650000, 0.650000)
mul r6.xy, r6.xyxx, l(0.350000, 0.350000, 0.000000, 0.000000)
add r6.xy, r6.xyxx, r11.zwzz  // gradFar<0:NaN:Inf,1:NaN:Inf>

#line 303
sample_indexable(texture2d)(float,float,float,float) r12.xyzw, v1.xyxx, t1.wxyz, s10  // grad<3:Inf,0:Inf,1:Inf,2:Inf>

#line 307
mul r11.zw, r6.xxxy, cb4[2].zzzz
mov r13.xy, -r11.zwzz
add r13.xy, r12.yzyy, r13.xyxx
mul r13.xy, r0.wwww, r13.xyxx
add r13.xz, r11.zzwz, r13.xxyx  // specularGrad<0:NaN:Inf,1:NaN:Inf>

#line 308
mul r6.xy, r6.xyxx, l(0.100000, 0.100000, 0.000000, 0.000000)
mul r14.xy, r6.wwww, r6.xyxx
mov r14.z, l(0)
mov r15.xyz, -r14.xyzx
add r12.yzw, r12.yyzw, r15.xxyz
mul r12.yzw, r0.wwww, r12.yyzw
add r5.xyz, r12.yzwy, r14.xyzx  // grad<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 318
dp3 r0.w, r5.xywx, r5.xywx
rsq r0.w, r0.w
mul r12.yzw, r0.wwww, r5.xxwy  // normal<0:NaN:Inf,1:NaN,2:NaN:Inf>

#line 320
mov r13.y, l(78.125000)
dp3 r0.w, r13.xyzx, r13.xyzx
rsq r0.w, r0.w
mul r13.xyz, r0.wwww, r13.xyzx  // specularNormal<0:NaN:Inf,1:NaN,2:NaN:Inf>

#line 325
nop 
add r6.xy, r3.zwzz, r11.xyxx
mul r6.xy, r6.xyxx, l(0.400000, 0.400000, 0.000000, 0.000000)
sample_indexable(texture2d)(float,float,float,float) r6.xy, r6.xyxx, t4.ywxz, s12
mov r6.xy, r6.xyxx  // color<1:Inf,3:Inf>

#line 201
mul r6.xy, r6.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000)
add r11.xz, r6.xxyx, l(-1.000000, 0.000000, -1.000000, 0.000000)  // normal<1:Inf,0:Inf>

#line 207
mul r0.w, r11.z, r11.z
mov r0.w, -r0.w
add r0.w, r0.w, l(1.000000)
mul r5.w, r11.x, r11.x
mov r5.w, -r5.w
add r0.w, r0.w, r5.w
max r0.w, r0.w, l(0.000000)
min r0.w, r0.w, l(1.000000)
add r0.w, r0.w, l(0.000100)  // tmp<0:[0.0001f,1.0001f]>

#line 213
rsq r5.w, r0.w
mul r11.y, r0.w, r5.w  // normal<2:[9.9995e-005f,100.01f]>

#line 216
mov r11.xz, r11.xxzx  // DecodeNormalTexture<1:Inf,0:Inf>
mov r11.y, r11.y  // DecodeNormalTexture<2:[9.9995e-005f,100.01f]>

#line 325
mov r11.xyz, r11.xyzx  // normalFar<0:Inf,1:[9.9995e-005f,100.01f],2:Inf>

#line 326
mul r0.w, r6.w, l(0.650000)
max r0.w, r0.w, l(0.000000)
min r0.w, r0.w, l(1.000000)
mov r14.xyz, -r11.xyzx
add r13.xyz, r13.xyzx, r14.xyzx
mul r13.xyz, r0.wwww, r13.xyzx
add r11.xyz, r11.xyzx, r13.xyzx  // specularNormal<0:NaN:Inf,1:NaN,2:NaN:Inf>

#line 337
add r0.w, r0.z, l(-100.000000)
div r5.w, r0.w, l(100.000000)
max r5.w, r5.w, l(0.000000)
min r13.w, r5.w, l(1.000000)  // closeRange<0:[0f,1f]>

#line 339
mov r14.xyz, -r4.xyzx
dp3 r5.w, r12.yzwy, r14.xyzx  // NV<0:NaN:Inf>

#line 340
dp3 r6.x, r4.xyzx, r11.xyzx
add r6.x, r6.x, r6.x
mov r6.x, -r6.x
mul r15.xyz, r6.xxxx, r11.xyzx
add r15.xyz, r4.xyzx, r15.xyzx  // R<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 343
mul r6.xy, r3.xyxx, l(0.200000, 0.200000, 0.000000, 0.000000)
add r6.xy, r3.zwzz, r6.xyxx
sample_indexable(texture2d)(float,float,float,float) r16.xyz, r6.xyxx, t3.xyzw, s12
mov r16.xyz, r16.xyzx  // noise<0:Inf,1:Inf,2:Inf>

#line 347
mov r6.x, -r5.w
max r5.w, r5.w, r6.x
mul r5.w, r5.w, r6.w  // fNdotE<0:NaN:Inf>

#line 348
mov r5.w, -r5.w
add r5.w, r5.w, l(1.000100)  // facing<0:NaN:Inf>

#line 350
mul r6.x, r6.w, l(8.000000)  // fresnelPower<0:[-5.44452e+035f,5.44452e+035f]>

#line 351
log r5.w, r5.w
mul r5.w, r5.w, r6.x
exp r5.w, r5.w
mul r5.w, r5.w, l(0.950000)
add r5.w, r5.w, l(0.050000)
max r5.w, r5.w, l(0.000000)
min r17.xyz, r5.wwww, l(1.000000, 1.000000, 1.000000, 0.000000)  // fresnel<0:[0f,1f],0:[0f,1f],0:[0f,1f]>

#line 354
dp3 r5.w, r2.xzyx, r15.xyzx
max r5.w, r5.w, l(0.000000)
min r5.w, r5.w, l(1.000000)  // LdotR<0:[0f,1f]>

#line 357
mul r6.x, r9.x, l(2.000000)  // glossinessK<1:Inf>
mov r9.xyz, r9.xyzx  // glossinessK<0,2,3>

#line 358
log r5.w, r5.w
mul r6.y, r5.w, r9.x
exp r15.x, r6.y
mul r5.w, r5.w, r6.x
exp r15.y, r5.w
dp2 r5.w, r9.yzyy, r15.xyxx  // specularIntensity<0:NaN:Inf>

#line 359
div r6.x, r0.w, l(500.000000)
max r6.x, r6.x, l(0.000000)
min r6.x, r6.x, l(1.000000)  // depthLessThanMiddleDistanceBlend<0:[0f,1f]>

#line 360
mov r6.y, -r10.x
max r6.y, r6.y, r10.x
mul r6.y, r6.y, l(1000.000000)
mov r6.y, -r6.y
add r6.y, r6.y, l(1.000000)
max r6.y, r6.y, l(0.500000)  // cameraVelocity<0:[0.5f,1f]>

#line 361
mul r7.w, r16.z, l(0.500000)
mul r6.x, r6.x, r7.w
mul r6.x, r6.y, r6.x
mul r5.w, r5.w, r6.x  // specularIntensity<0:NaN:Inf>

#line 364
div r6.x, r0.z, l(2500.000000)
mov r6.x, -r6.x
add r6.x, r6.x, l(1.000000)
max r6.x, r6.x, l(0.000000)
min r6.x, r6.x, l(1.000000)  // depthMiddleDistanceInvertedBlend<0:[0f,1f]>

#line 365
mul r6.y, r6.x, l(0.200000)
mov r9.xyz, -r7.xyzx
add r9.xyz, r2.xzyx, r9.xyzx
mul r9.xyz, r6.yyyy, r9.xyzx
add r7.xzw, r7.xxyz, r9.xxyz
dp3 r6.y, r7.xzwx, r7.xzwx
rsq r6.y, r6.y
mul r7.xzw, r6.yyyy, r7.xxzw  // sunDirectionExtendedToHorizon<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 367
mul r6.y, r6.w, l(0.150000)
add r6.y, r6.y, l(0.025000)
add r9.xyz, r11.xyzx, l(-0.000000, -1.000000, -0.000000, 0.000000)
mul r9.xyz, r6.yyyy, r9.xyzx
add r9.xyz, r9.xyzx, l(0.000000, 1.000000, 0.000000, 0.000000)
dp3 r6.y, r9.xyzx, r9.xyzx
rsq r6.y, r6.y
mul r9.xyz, r6.yyyy, r9.xyzx
dp3 r6.y, r4.xyzx, r9.xyzx
add r6.y, r6.y, r6.y
mov r6.y, -r6.y
mul r9.xyz, r6.yyyy, r9.xyzx
add r9.xyz, r4.xyzx, r9.xyzx  // R<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 368
dp3 r6.y, r7.xzwx, r9.xyzx
max r6.y, r6.y, l(0.000000)
min r6.y, r6.y, l(1.000000)  // LdotR<0:[0f,1f]>

#line 370
mul r6.w, r6.y, r6.y
mul r7.x, r6.w, l(1.000000)
mul r6.w, r6.w, r6.w
mul r6.w, r6.w, r7.x
mul r6.w, r6.w, l(1.273240)
mul r6.w, r9.w, r6.w
add r5.w, r5.w, r6.w  // specularIntensity<0:NaN:Inf>

#line 372
log r6.y, r6.y
mul r6.y, r6.y, l(5000.000000)
exp r6.y, r6.y
mul r6.y, r6.y, l(796.093323)
mul r6.y, r9.w, r6.y
mul r6.y, r6.y, l(0.250000)
add r5.w, r5.w, r6.y  // specularIntensity<0:NaN:Inf>

#line 374
mul r7.xzw, r5.wwww, r10.yyzw  // specularContribution<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 377
dp3 r5.w, r7.xzwx, l(0.333000, 0.333000, 0.333000, 0.000000)  // temp<0:NaN:Inf>

#line 378
mul r5.w, r5.w, r5.w
max r5.w, r5.w, l(0.000000)
min r5.w, r5.w, l(1.000000)
mul r7.xzw, r5.wwww, r7.xxzw  // specularContribution<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 381
mov r11.xyz, r17.zzzz
mul r7.xzw, r7.xxzw, r11.xxyz  // specularContribution<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 383
mul r7.xzw, r8.wwww, r7.xxzw  // specularContribution<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 385
mul r7.xzw, r7.xxzw, l(1.050000, 0.000000, 1.050000, 1.050000)  // specularContribution<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 389
add r5.w, r7.y, l(-0.040000)
mul r5.w, r5.w, l(14.000000)
add r5.w, r5.w, l(1.000000)
max r5.w, r5.w, l(0.000000)
min r5.w, r5.w, l(1.000000)
add r6.y, r7.y, l(0.240000)
mul r6.y, r6.y, l(14.000000)
mov r6.y, -r6.y
add r6.y, r6.y, l(1.000000)
max r6.y, r6.y, l(0.000000)
min r6.y, r6.y, l(1.000000)
mul r6.y, r6.y, l(0.500000)
add r5.w, r5.w, r6.y  // dayAndNightTransition<0:[0f,1.5f]>

#line 390
mul r5.w, r5.w, r5.w  // dayAndNightTransition<0:[0f,2.25f]>

#line 391
mul r7.xyz, r5.wwww, r7.xzwx  // specularContribution<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 397
mul r5.w, r16.x, l(0.500000)
max r5.w, r5.w, l(0.000000)
min r5.w, r5.w, l(1.000000)  // rate<0:[0f,1f]>

#line 398
mul r11.xyz, r5.wwww, l(-0.075000, -0.090000, -0.060000, 0.000000)
add r11.xyz, r11.xyzx, l(0.135000, 0.195000, 0.255000, 0.000000)  // compositedColor<0:[0.06f,0.135f],1:[0.105f,0.195f],2:[0.195f,0.255f]>

#line 401
div r5.w, l(0.000100), cb2[23].z
max r5.w, r5.w, l(0.000000)
min r5.w, r5.w, l(1.000000)
max r5.w, r5.w, l(0.350000)  // exposureAdaptation<0:[0.35f,1f]>

#line 402
mul r11.xyz, r5.wwww, r11.xyzx  // compositedColor<0:[0.021f,0.135f],1:[0.03675f,0.195f],2:[0.06825f,0.255f]>

#line 404
mov r15.xz, r4.xxzx
mov r15.y, r2.z
dp3 r4.x, r15.xyzx, r15.xyzx
rsq r4.x, r4.x
mul r15.xyz, r4.xxxx, r15.xyzx  // eyeDir<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 405
dp3 r4.x, r15.xzyx, r2.xyzx
max r4.x, r4.x, l(0.000000)
min r15.xyz, r4.xxxx, l(1.000000, 1.000000, 1.000000, 0.000000)  // colorBlendRate<0:[0f,1f],0:[0f,1f],0:[0f,1f]>

#line 406
dp3 r4.x, r10.yzwy, r10.yzwy
rsq r4.x, r4.x
mul r18.xyz, r4.xxxx, r10.yzwy
add r18.xyz, r18.xyzx, l(-0.350000, -0.350000, -0.350000, 0.000000)
mul r15.xyz, r15.xyzx, r18.xyzx
add r15.xyz, r15.xyzx, l(0.350000, 0.350000, 0.350000, 0.000000)  // sunFactor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 407
mul r11.xyz, r11.xyzx, r15.xyzx  // compositedColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 409
mul r11.xyz, r11.xyzx, l(0.096000, 0.200000, 0.380000, 0.000000)  // ambientColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 412
mul r18.xyz, r13.wwww, l(-0.075000, 0.025000, 0.025000, 0.000000)
add r18.xyz, r18.xyzx, l(0.135000, 0.195000, 0.255000, 0.000000)  // skyReflectionColor1<0:[0.06f,0.135f],1:[0.195f,0.22f],2:[0.255f,0.28f]>

#line 413
div r4.xz, r3.xxyx, l(10.000000, 0.000000, 10.000000, 0.000000)
mul r6.yw, r0.zzzz, r12.yyyw
div r6.yw, r6.yyyw, l(0.000000, 75.000000, 0.000000, 75.000000)
add r4.xz, r4.xxzx, r6.yywy  // waterDepthUv<0:NaN:Inf,1:NaN:Inf>

#line 414
sample_indexable(texture2d)(float,float,float,float) r4.x, r4.xzxx, t2.zxyw, s10
mul r4.x, r6.x, r4.x  // waterDepthTexColor<2:NaN:Inf>

#line 415
mul r4.x, r4.x, r4.x
mul r4.x, r4.x, l(400.000000)
max r4.x, r4.x, l(0.000000)
min r4.x, r4.x, l(1.000000)  // rate<0:[0f,1f]>

#line 416
add r18.xyz, r18.xyzx, l(-0.060000, -0.105000, -0.195000, 0.000000)
mul r18.xyz, r4.xxxx, r18.xyzx
add r18.xyz, r18.xyzx, l(0.060000, 0.105000, 0.195000, 0.000000)  // skyReflectionColor<0:[0.06f,0.135f],1:[0.105f,0.22f],2:[0.195f,0.28f]>

#line 417
mul r18.xyz, r5.wwww, r18.xyzx  // skyReflectionColor<0:[0.021f,0.135f],1:[0.03675f,0.22f],2:[0.06825f,0.28f]>

#line 418
mul r15.xyz, r15.xyzx, r18.xyzx  // skyReflectionColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 419
dp3 r4.x, l(0.000000, 1.000000, 0.000000, 0.000000), r14.xyzx
mul r4.x, r4.x, l(5.000000)
add r4.x, r4.x, l(3.000000)  // skyReflectionIntensity<0:NaN:Inf>

#line 425
mul r4.z, r0.z, l(2.000000)
div r2.w, r4.z, r2.w  // screenAdjustedViewZ<0:NaN:Inf>

#line 426
div r2.w, r2.w, l(600.000000)
max r2.w, r2.w, l(0.000000)
min r2.w, r2.w, l(1.000000)
mov r2.w, -r2.w
add r2.w, r2.w, l(1.000000)
mul r2.w, r2.w, l(0.950000)
add r6.yw, r2.wwww, l(0.000000, 0.050000, 0.000000, 0.050000)  // bendRate<0:[0.05f,1f],0:[0.05f,1f]>

#line 427
mul r2.w, r6.x, l(0.040000)
mov r2.w, -r2.w
add r2.w, r2.w, l(0.040500)
mul r5.xy, r2.wwww, r5.xyxx
add r5.xy, r5.xyxx, l(0.000000, 0.040000, 0.000000, 0.000000)
mul r5.xy, r5.xyxx, r6.ywyy
mov r5.xy, -r5.xyxx
add r0.xy, r0.xyxx, r5.xyxx
max r0.xy, r0.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
min r0.xy, r0.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)  // distortionUV<0:[0f,1f],1:[0f,1f]>

#line 429
nop 
mov r0.xy, r0.xyxx  // inTexCoord<0:[0f,1f],1:[0f,1f]>
mov r5.xy, cb2[21].zwzz  // projectionParameter<2,3>

#line 467
sample_indexable(texture2d)(float,float,float,float) r0.x, r0.xyxx, t13.xyzw, s9
mov r0.x, r0.x  // fetchDepth<0:Inf>

#line 472
nop 
mov r0.x, r0.x  // zOverW<0:Inf>
mov r5.xy, r5.xyxx  // proj<2,3>

#line 397
mov r0.y, -r5.y
add r0.x, r0.y, r0.x
div r0.x, r5.x, r0.x  // ReconstructViewZ<0:NaN:Inf>

#line 472
mov r0.x, r0.x  // depth<0:NaN:Inf>

#line 480
nop 

#line 429
mov r0.x, r0.x  // depthFactor<0:NaN:Inf>

#line 430
mov r0.x, r0.x  // distortionDepth<0:NaN:Inf>

#line 434
lt r0.y, r0.x, r0.z
mov r2.w, -r0.x
add r2.w, r0.z, r2.w
div r2.w, r2.w, l(50.000000)
max r2.w, r2.w, l(0.000000)
min r2.w, r2.w, l(1.000000)
mov r2.w, -r2.w
add r2.w, r2.w, l(1.000000)
mov r4.z, -r0.z
add r0.x, r0.x, r4.z
mul r4.y, r4.y, l(650.000000)
mov r4.y, -r4.y
add r4.y, r4.y, l(700.000000)
div r0.x, r0.x, r4.y
max r0.x, r0.x, l(0.000000)
min r0.x, r0.x, l(1.000000)
mov r0.x, -r0.x
add r0.x, r0.x, l(1.000000)
movc r0.x, r0.y, r2.w, r0.x  // distortionColorBlendRate<0:[0f,1f]>

#line 435
div r0.y, r0.z, l(250.000000)
max r0.y, r0.y, l(0.000000)
min r0.y, r0.y, l(1.000000)
mul r0.x, r0.y, r0.x  // distortionColorBlendRate<0:[0f,1f]>

#line 443
mov r0.y, -r6.z
add r0.y, r0.y, l(1.000000)
max r0.y, r0.y, l(0.000000)
min r0.y, r0.y, l(1.000000)
mul r0.y, r0.y, l(10.000000)
add r0.y, r0.y, l(1.000000)  // foamIntensity<0:[1f,11f]>

#line 445
mul r3.zw, r3.zzzw, r4.wwww
mul r3.zw, r3.zzzw, l(0.000000, 0.000000, 2.000000, 2.000000)
add r3.xy, r3.zwzz, r3.xyxx
sample_indexable(texture2d)(float,float,float,float) r0.z, r3.xyxx, t5.xzyw, s10
mov r0.z, r0.z  // foamSample<1:Inf>

#line 447
div r0.w, r0.w, l(1500.000000)
max r0.w, r0.w, l(0.000000)
min r0.w, r0.w, l(1.000000)  // depthLessThanMiddleDistanceBlend<0:[0f,1f]>

#line 448
add r2.w, r0.w, r6.z
add r2.w, r2.w, l(0.100000)
max r2.w, r2.w, l(0.000000)
min r2.w, r2.w, l(1.000000)
add r3.x, r16.y, l(-1.000000)
mul r2.w, r2.w, r3.x
add r2.w, r2.w, l(1.000000)  // foamAmount<0:NaN:Inf>

#line 450
mov r12.x, r12.x  // foamXMask<0:Inf>

#line 451
mul r3.x, r5.z, r5.z  // gradzPowered<0:NaN:Inf>

#line 452
mul r3.x, r3.x, r3.x  // gradzPowered<0:NaN:Inf>

#line 454
mul r2.w, r16.x, r2.w
mul r0.z, r0.z, r2.w
mul r0.z, r12.x, r0.z
mul r0.z, r0.z, l(2.000000)  // farFoamIntensity<0:NaN:Inf>

#line 455
mul r0.w, r0.w, r0.z
mov r0.w, -r0.w
add r0.z, r0.w, r0.z  // farFoamIntensity<0:NaN:Inf>

#line 468
mul r0.y, r0.z, r0.y  // foamIntensity<0:NaN:Inf>

#line 470
mul r0.y, r0.y, l(0.500000)  // foamIntensity<0:NaN:Inf>

#line 471
mul r3.yzw, r10.yyzw, l(0.000000, 0.150000, 0.150000, 0.150000)
add r3.yzw, r11.xxyz, r3.yyzw
add r3.yzw, r3.yyzw, l(0.000000, 0.050000, 0.050000, 0.050000)  // foamColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 475
dp3 r0.z, r12.ywzy, r2.xyzx  // NL<0:NaN:Inf>

#line 476
mov r0.w, -r0.z
max r0.z, r0.w, r0.z  // sssIntensity<0:NaN:Inf>

#line 477
dp2 r0.w, r2.xyxx, r9.xzxx
mov r2.x, -r0.w
max r0.w, r0.w, r2.x
add r0.z, r0.w, r0.z  // sssIntensity<0:NaN:Inf>

#line 478
mul r0.z, r0.z, l(0.500000)  // sssIntensity<0:NaN:Inf>

#line 482
mul r0.w, r3.x, l(0.250000)
mul r0.z, r0.w, r0.z  // sssIntensity<0:NaN:Inf>

#line 487
mul r2.xyz, r10.yzwy, r0.zzzz
mul r2.xyz, r2.xyzx, l(0.008750, 0.031500, 0.015750, 0.000000)  // sssContribution<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 501
mul r0.z, r0.y, l(12.000000)
mov r0.z, -r0.z
add r0.z, r0.z, l(1.000000)
max r0.z, r0.z, l(0.000000)
min r0.z, r0.z, l(1.000000)
mul r4.yzw, r0.zzzz, r7.xxyz
mul r5.xyz, r11.xyzx, l(1.850000, 1.850000, 1.850000, 0.000000)
mul r6.xyz, r4.xxxx, r15.xyzx
mov r7.xyz, -r5.xyzx
add r6.xyz, r6.xyzx, r7.xyzx
mul r6.xyz, r6.xyzx, r17.xyzx
add r5.xyz, r5.xyzx, r6.xyzx
add r0.x, r0.x, l(-0.500000)
max r0.x, r0.x, l(0.000000)
min r0.x, r0.x, l(1.000000)
mov r6.xyz, -r5.xyzx
add r6.xyz, r6.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
mul r0.xzw, r0.xxxx, r6.xxyz
add r0.xzw, r0.xxzw, r5.xxyz
add r0.xzw, r0.xxzw, r2.xxyz
mul r2.xyz, r0.yyyy, r3.yzwy
add r0.xyz, r0.xzwx, r2.xyzx
mul r0.xyz, r0.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
add r0.xyz, r0.xyzx, r4.yzwy  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 505
mul r0.xyz, r1.wwww, r0.xyzx
add r0.xyz, r1.xyzx, r0.xyzx  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 508
nop 
mov r8.xyz, r8.xyzx  // params<0,1,2>
mov r0.xyz, r0.xyzx  // x<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 11
mov r1.xyz, r8.yyyy
ge r1.xzw, r1.xxyz, r0.xxyz
movc r1.xzw, r1.xxzw, l(1.000000,0,1.000000,1.000000), l(0,0,0,0)  // mask<0:[-0f,1f],1:[-0f,1f],2:[-0f,1f]>

#line 12
mul r2.xyz, r0.xyzx, r1.xzwx
mov r1.xzw, -r1.xxzw
add r1.xzw, r1.xxzw, l(1.000000, 0.000000, 1.000000, 1.000000)
add r0.xyz, r8.zzzz, r0.xyzx
mov r3.xyz, -r1.yyyy
add r0.xyz, r0.xyzx, r3.xyzx
mul r0.xyz, r0.xyzx, r8.xxxx
div r0.xyz, l(-1.000000, -1.000000, -1.000000, 0.000000), r0.xyzx
add r0.xyz, r8.zzzz, r0.xyzx
add r0.xyz, r1.yyyy, r0.xyzx
mul r0.xyz, r0.xyzx, r1.xzwx
add r0.xyz, r0.xyzx, r2.xyzx  // TppTonemap<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 508
mov r0.xyz, r0.xyzx  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 511
nop 
mov r0.xyz, r0.xyzx  // linearRGB<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 24
ge r1.xyz, l(0.003131, 0.003131, 0.003131, 0.000000), r0.xyzx
movc r1.xyz, r1.xyzx, l(1.000000,1.000000,1.000000,0), l(0,0,0,0)  // mask<0:[-0f,1f],1:[-0f,1f],2:[-0f,1f]>

#line 25
mul r2.xyz, r0.xyzx, l(12.920000, 12.920000, 12.920000, 0.000000)
mul r2.xyz, r1.xyzx, r2.xyzx
mov r1.xyz, -r1.xyzx
add r1.xyz, r1.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
max r0.xyz, r0.xyzx, l(0.000010, 0.000010, 0.000010, 0.000000)
log r0.xyz, r0.xyzx
mul r0.xyz, r0.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
exp r0.xyz, r0.xyzx
mul r0.xyz, r0.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000)
add r0.xyz, r0.xyzx, l(-0.055000, -0.055000, -0.055000, 0.000000)
mul r0.xyz, r0.xyzx, r1.xyzx
add r0.xyz, r0.xyzx, r2.xyzx  // GammaCorrection<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 511
mov r0.xyz, r0.xyzx  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 517
mov r13.w, r13.w  // outColor<3:[0f,1f]>

#line 521
mul r13.xyz, r0.xyzx, r13.wwww  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 600
mov r13.xyz, r13.xyzx  // NCalculate_computePrimitiveColor_outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
mov r13.w, r13.w  // NCalculate_computePrimitiveColor_outColor<3:[0f,1f]>

#line 602
mov o0.xyzw, r13.xyzw  // outColor0<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:[0f,1f]>

#line 604
mov o1.xyzw, r13.xyzw  // outColor1<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:[0f,1f]>

#line 527
ret 
// Approximately 520 instruction slots used
