Microsoft (R) Direct3D Shader Compiler 10.1
Copyright (C) 2013 Microsoft. All rights reserved.

//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer cPSScene
// {
//
//   struct PSScene
//   {
//       
//       float4x4 m_projectionView;     // Offset:    0
//       float4x4 m_projection;         // Offset:   64
//       float4x4 m_view;               // Offset:  128
//       float4x4 m_shadowProjection;   // Offset:  192
//       float4x4 m_shadowProjection2;  // Offset:  256
//       float4 m_eyepos;               // Offset:  320
//       float4 m_projectionParam;      // Offset:  336
//       float4 m_viewportSize;         // Offset:  352
//       float4 m_exposure;             // Offset:  368
//       float4 m_fogParam[3];          // Offset:  384
//       float4 m_fogColor;             // Offset:  432
//       float4 m_cameraCenterOffset;   // Offset:  448
//       float4 m_shadowMapResolutions; // Offset:  464
//
//   } g_psScene;                       // Offset:    0 Size:   480
//
// }
//
// cbuffer cPSMaterial
// {
//
//   struct PSMaterial
//   {
//       
//       float4 m_materials[8];         // Offset:    0
//
//   } g_psMaterial;                    // Offset:    0 Size:   128
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// inDiffuseSampler                  sampler      NA          NA             s0      1 
// inNormalSampler                   sampler      NA          NA             s1      1 
// g_samplerLinear_Wrap              sampler      NA          NA            s10      1 
// inDiffuseTexture                  texture  float4          2d             t0      1 
// inNormalTexture                   texture  float4          2d             t1      1 
// inSpecularTexture                 texture  float4          2d             t2      1 
// inFireTexture                     texture  float4          2d             t5      1 
// cPSScene                          cbuffer      NA          NA            cb2      1 
// cPSMaterial                       cbuffer      NA          NA            cb4      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// COLOR                    0   xyzw        0     NONE   float      w
// TEXCOORD                 0   xy          1     NONE   float   xy  
// TEXCOORD                 1     zw        1     NONE   float       
// TEXCOORD                 3   xyzw        2     NONE   float   xyz 
// TEXCOORD                 4   xyzw        3     NONE   float       
// TEXCOORD                 5   xyz         4     NONE   float   xyz 
// TEXCOORD                 6   xyz         5     NONE   float   xyz 
// TEXCOORD                 7   xyz         6     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB2[24], immediateIndexed
dcl_constantbuffer CB4[8], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s10, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t5
dcl_input_ps linear v0.w
dcl_input_ps linear v1.xy
dcl_input_ps linear v2.xyz
dcl_input_ps linear v4.xyz
dcl_input_ps linear v5.xyz
dcl_input_ps linear v6.xyz
dcl_output o0.xyzw
dcl_temps 11

#line 242 "d:\work\master\git_clone\_intermediate\win64\TppShaders_dx11_win64\Release\tpp3dfw_WormholeForBigThings_ps.hlsl"
nop 

#line 223
sample_indexable(texture2d)(float,float,float,float) r0.xyzw, v1.xyxx, t0.xyzw, s0  // outColorSRGB<0:Inf,1:Inf,2:Inf,3:Inf>

#line 224
nop 
mov r0.xyz, r0.xyzx  // inSRGB<0:Inf,1:Inf,2:Inf>

#line 48
ge r1.xyz, l(0.039280, 0.039280, 0.039280, 0.000000), r0.xyzx
movc r1.xyz, r1.xyzx, l(1.000000,1.000000,1.000000,0), l(0,0,0,0)  // mask<0:[-0f,1f],1:[-0f,1f],2:[-0f,1f]>

#line 49
div r2.xyz, r0.xyzx, l(12.920000, 12.920000, 12.920000, 0.000000)
mul r2.xyz, r1.xyzx, r2.xyzx
mov r1.xyz, -r1.xyzx
add r1.xyz, r1.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
add r3.xyz, r0.xyzx, l(0.055000, 0.055000, 0.055000, 0.000000)
div r3.xyz, r3.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000)
max r3.xyz, r3.xyzx, l(0.000010, 0.000010, 0.000010, 0.000000)
log r3.xyz, r3.xyzx
mul r3.xyz, r3.xyzx, l(2.400000, 2.400000, 2.400000, 0.000000)
exp r3.xyz, r3.xyzx
mul r1.xyz, r1.xyzx, r3.xyzx
add r0.xyz, r1.xyzx, r2.xyzx  // GammaDecode<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 224
mov r0.xyz, r0.xyzx  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 225
mov r0.w, r0.w  // outColor<3:Inf>

#line 242
mov r0.xyz, r0.xyzx  // NFetchAlbedoMap_fetchAlbedoMap_outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
mov r0.w, r0.w  // NFetchAlbedoMap_fetchAlbedoMap_outColor<3:Inf>

#line 248
nop 

#line 40
sample_indexable(texture2d)(float,float,float,float) r1.xy, v1.xyxx, t2.yzxw, s10  // outSpecular<0:Inf,1:Inf>

#line 248
mov r1.xy, r1.xyxx  // NGetSpecularInformation_getSpecularInformation_outSpecular<0:Inf,1:Inf>

#line 250
mov r2.xyz, v2.xyzx  // NGetEyeDir_getEyeDir_inWorldPosition<0,1,2>

#line 251
nop 
mov r2.xyz, r2.xyzx  // inWorldPosition<0,1,2>

#line 421
nop 

#line 78
mov r3.xyz, cb2[20].xyzx  // GetEyePosition<0,1,2>

#line 421
mov r3.xyz, -r3.xyzx
add r2.xyz, r2.xyzx, r3.xyzx  // diff<0:Inf,1:Inf,2:Inf>

#line 422
dp3 r1.z, r2.xyzx, r2.xyzx
rsq r1.z, r1.z
mul r2.xyz, r1.zzzz, r2.xyzx  // outEyeDir<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 251
mov r2.xyz, r2.xyzx  // NGetEyeDir_getEyeDir_outEyeDir<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 245
nop 

#line 26
nop 

#line 230
nop 
sample_indexable(texture2d)(float,float,float,float) r1.zw, v1.xyxx, t1.xzwy, s1
mov r1.zw, r1.zzzw  // color<3:Inf,1:Inf>

#line 201
mul r1.zw, r1.zzzw, l(0.000000, 0.000000, 2.000000, 2.000000)
add r3.xy, r1.zwzz, l(-1.000000, -1.000000, 0.000000, 0.000000)  // normal<0:Inf,1:Inf>

#line 207
mul r1.z, r3.x, r3.x
mov r1.z, -r1.z
add r1.z, r1.z, l(1.000000)
mul r1.w, r3.y, r3.y
mov r1.w, -r1.w
add r1.z, r1.w, r1.z
max r1.z, r1.z, l(0.000000)
min r1.z, r1.z, l(1.000000)
add r1.z, r1.z, l(0.000100)  // tmp<0:[0.0001f,1.0001f]>

#line 213
rsq r1.w, r1.z
mul r3.z, r1.w, r1.z  // normal<2:[9.9995e-005f,100.01f]>

#line 216
mov r3.xy, r3.xyxx  // DecodeNormalTexture<0:Inf,1:Inf>
mov r3.z, r3.z  // DecodeNormalTexture<2:[9.9995e-005f,100.01f]>

#line 230
mov r3.xyz, r3.xyzx  // GetNormalFromTextureWithSampler<0:Inf,1:Inf,2:[9.9995e-005f,100.01f]>

#line 26
mov r3.xyz, r3.xyzx  // outNormal<0:Inf,1:Inf,2:[9.9995e-005f,100.01f]>

#line 245
mov r3.xyz, r3.xyzx  // NFetchNormalMap2_fetchNormalMap_outNormal<0:Inf,1:Inf,2:[9.9995e-005f,100.01f]>

#line 252
mov r1.zw, v1.xxxy  // NWormhole_wormhole_inUv<0,1>

#line 253
mov r2.w, v2.y  // NWormhole_wormhole_inWorldPosition<1>

#line 254
mov r4.xyz, v6.xyzx  // NWormhole_wormhole_inVertexNormal<0,1,2>

#line 255
mov r3.xyz, r3.xyzx  // NWormhole_wormhole_inSurfaceNormal<0:Inf,1:Inf,2:[9.9995e-005f,100.01f]>

#line 256
mov r2.xyz, r2.xyzx  // NWormhole_wormhole_inEyeDirection<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 257
mov r3.w, v0.w  // NWormhole_wormhole_inColor<3>

#line 258
mov r5.xyz, -cb4[4].xyzx  // NWormhole_wormhole_inLightDir<0,1,2>

#line 259
mov r6.xyz, cb4[3].xyzx  // NWormhole_wormhole_inLightColor<0,1,2>

#line 261
mov r0.xyzw, r0.xyzw  // NWormhole_wormhole_inAlbedo<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:Inf>

#line 260
mov r1.xy, r1.xyxx  // NWormhole_wormhole_inSpecular<0:Inf,1:Inf>

#line 261
nop 
mov r1.zw, r1.zzzw  // inUv<0,1>
mov r2.w, r2.w  // inWorldPosition<1>
mov r4.xyz, r4.xyzx  // inVertexNormal<0,1,2>
mov r3.xyz, r3.xyzx  // inSurfaceNormal<0:Inf,1:Inf,2:[9.9995e-005f,100.01f]>
mov r2.xyz, r2.xyzx  // inEyeDirection<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
mov r3.w, r3.w  // inColor<3>
mov r5.xyz, r5.xyzx  // inLightDir<0,1,2>
mov r6.xyz, r6.xyzx  // inLightColor<0,1,2>
mov r0.xyzw, r0.xyzw  // inAlbedo<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:Inf>
mov r1.xy, r1.xyxx  // inSpecular<0:Inf,1:Inf>

#line 63
mov r4.w, cb4[5].w  // time<0>

#line 64
mov r5.w, cb4[6].x  // height<0>

#line 65
mov r6.w, cb4[6].y  // footYPosition<0>

#line 66
mov r7.x, cb4[7].x  // distortionVelocity<0>

#line 67
mov r7.y, cb4[7].z  // effectCompletionPercentageGamma<0>

#line 69
mul r4.w, r4.w, r7.x  // timeWithVelocity<0:Inf>

#line 70
mov r6.w, -r6.w
add r2.w, r2.w, r6.w  // vertexYPosition<0:Inf>

#line 71
mul r1.zw, r1.zzzw, l(0.000000, 0.000000, 1.500000, 1.500000)  // inUv<0:Inf,1:Inf>

#line 72
sample_indexable(texture2d)(float,float,float,float) r6.w, r1.zwzz, t5.yzwx, s10
mov r6.w, r6.w  // distortionSample<0:Inf>

#line 88
mul r7.x, r6.w, l(0.350000)
add r7.x, r7.x, l(1.000000)  // burnLayerMask<0:Inf>

#line 89
mul r7.x, r5.w, r7.x
mul r7.x, r7.y, r7.x
mov r7.x, -r7.x
add r5.w, r5.w, r7.x  // fireLineYPosition<0:NaN:Inf>

#line 90
mov r5.w, -r5.w
add r2.w, r2.w, r5.w  // vertexFireLineDifference<0:NaN:Inf>

#line 91
mul r5.w, r2.w, l(85.000000)
add r5.w, r5.w, l(-21.000000)
max r5.w, r5.w, l(0.000000)
min r5.w, r5.w, l(1.000000)  // transparencyRange<0:[0f,1f]>

#line 94
mul r4.w, r4.w, l(0.028753)
add r1.zw, r1.zzzw, r4.wwww  // movingUvs<0:NaN:Inf,1:NaN:Inf>

#line 95
sample_indexable(texture2d)(float,float,float,float) r1.z, r1.zwzz, t5.yzxw, s10
mov r1.z, r1.z  // movingHighFrequencyDetail<0:Inf>

#line 96
mul r1.z, r1.z, r1.z  // movingHighFrequencyDetail<0:NaN:Inf>

#line 104
mov r1.w, -r5.w
add r1.w, r1.w, l(1.000000)  // outColor<3:[0f,1f]>

#line 107
mul r0.w, r3.w, r0.w
mul r0.w, r0.w, r1.w  // outColor<3:NaN:Inf>

#line 112
lt r1.w, r0.w, l(0.100000)
if_nz r1.w

#line 114
  discard_nz l(-1)
  mov r3.xyzw, l(0,0,0,0)  // outColor<0: 0f,1: 0f,2: 0f,3: 0f>

#line 112
else 

#line 120
  mov r1.w, cb4[7].y  // effectCompletionPercentage<0>

#line 121
  mov r7.xzw, cb4[1].xxyz  // c0<0,1,2>

#line 122
  mov r8.xyz, cb4[2].xyzx  // c1<0,1,2>

#line 125
  dp3 r3.w, r3.xyzx, r3.xyzx
  rsq r3.w, r3.w
  mul r3.xyz, r3.wwww, r3.xyzx  // inSurfaceNormal<0:NaN:Inf,1:NaN:Inf,2:NaN>

#line 130
  mov r9.xyz, v4.xyzx
  mul r9.xyz, r3.xxxx, r9.xyzx
  mov r10.xyz, v5.xyzx
  mul r3.xyw, r3.yyyy, r10.xyxz
  mul r10.xyz, r3.zzzz, r4.xyzx
  add r3.xyz, r3.xywx, r10.xyzx
  add r3.xyz, r3.xyzx, r9.xyzx  // inSurfaceNormal<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 131
  dp3 r3.w, r3.xyzx, r3.xyzx
  rsq r3.w, r3.w
  mul r3.xyz, r3.wwww, r3.xyzx  // inSurfaceNormal<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 134
  mov r1.x, r1.x  // inRoughness<0:Inf>

#line 135
  mul r1.x, r1.x, l(-11.000000)
  add r1.x, r1.x, l(12.000000)
  exp r1.x, r1.x  // specularPower<0:Inf:[0f,1.#INFf]>

#line 136
  mov r1.y, r1.y  // specularIntensity<0:Inf>

#line 139
  dp3 r3.w, r3.yxzy, l(1.000000, 0.000000, 0.000000, 0.000000)  // fT<0:NaN:Inf>

#line 140
  mul r7.xzw, r3.wwww, r7.xxzw
  add r7.xzw, r8.xxyz, r7.xxzw  // ambientContribution<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 144
  dp3 r3.w, r5.xyzx, r3.xyzx
  max r3.w, r3.w, l(0.000000)
  min r3.w, r3.w, l(1.000000)  // LN<0:[0f,1f]>

#line 146
  mov r8.xyz, -r2.xyzx
  add r5.xyz, r5.xyzx, r8.xyzx
  dp3 r4.w, r5.xyzx, r5.xyzx
  rsq r4.w, r4.w
  mul r5.xyz, r4.wwww, r5.xyzx
  dp3 r3.x, r5.xyzx, r3.xyzx
  max r3.x, r3.x, l(0.000100)  // HN<0:Inf:[0.0001f,1.#INFf]>

#line 147
  mul r3.yzw, r3.wwww, r6.xxyz  // diffuseContribution<0,1,2>

#line 148
  log r3.x, r3.x
  mul r1.x, r1.x, r3.x
  exp r1.x, r1.x
  mul r1.x, r1.x, r1.y
  mul r5.xyz, r1.xxxx, r6.xyzx  // specularContribution<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 151
  mul r0.xyz, r0.xyzx, l(0.040000, 0.040000, 0.040000, 0.000000)  // inAlbedo<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 156
  add r3.xyz, r7.xzwx, r3.yzwy
  mul r0.xyz, r0.xyzx, r3.xyzx
  add r0.xyz, r5.xyzx, r0.xyzx  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 159
  mov r1.x, cb2[23].z
  mul r0.xyz, r0.xyzx, r1.xxxx  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 162
  mov r0.w, r0.w  // inAlpha<0:NaN:Inf>

#line 181
  mul r1.x, r7.y, l(0.150000)
  add r1.x, r2.w, r1.x
  mul r1.y, r6.w, l(0.100000)
  mov r1.y, -r1.y
  add r1.x, r1.y, r1.x
  mul r1.x, r1.x, l(0.050000)
  max r1.x, r1.x, l(0.000000)
  min r1.x, r1.x, l(1.000000)  // fireIlluminationRange<0:[0f,1f]>

#line 182
  mul r1.x, r1.x, r1.z
  mul r1.xyz, r1.xxxx, l(50.000000, 10.000000, 0.200000, 0.000000)
  add r0.xyz, r0.xyzx, r1.xyzx  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 184
  mul r1.x, r6.w, r6.w
  mul r1.xyz, r1.xxxx, l(5.000000, 2.500000, 1.000000, 0.000000)  // fireColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 185
  mul r2.w, r2.w, l(270.000000)
  add r2.w, r2.w, l(-67.500000)
  max r2.w, r2.w, l(0.000000)
  min r2.w, r2.w, l(1.000000)  // fireLineRange<0:[0f,1f]>

#line 186
  mul r3.xyz, r1.xyzx, r2.wwww
  add r0.xyz, r0.xyzx, r3.xyzx  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 190
  mov r3.xyz, cb4[5].xyzx  // tonemapParam<0,1,2>

#line 191
  nop 
  mov r3.xyz, r3.xyzx  // params<0,1,2>
  mov r0.xyz, r0.xyzx  // x<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 11
  mov r5.xyz, r3.yyyy
  ge r5.xzw, r5.xxyz, r0.xxyz
  movc r5.xzw, r5.xxzw, l(1.000000,0,1.000000,1.000000), l(0,0,0,0)  // mask<0:[-0f,1f],1:[-0f,1f],2:[-0f,1f]>

#line 12
  mul r6.xyz, r0.xyzx, r5.xzwx
  mov r5.xzw, -r5.xxzw
  add r5.xzw, r5.xxzw, l(1.000000, 0.000000, 1.000000, 1.000000)
  add r0.xyz, r3.zzzz, r0.xyzx
  mov r7.xyz, -r5.yyyy
  add r0.xyz, r0.xyzx, r7.xyzx
  mul r0.xyz, r0.xyzx, r3.xxxx
  div r0.xyz, l(-1.000000, -1.000000, -1.000000, 0.000000), r0.xyzx
  add r0.xyz, r3.zzzz, r0.xyzx
  add r0.xyz, r5.yyyy, r0.xyzx
  mul r0.xyz, r0.xyzx, r5.xzwx
  add r0.xyz, r0.xyzx, r6.xyzx  // TppTonemap<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 191
  mov r0.xyz, r0.xyzx  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 192
  nop 
  mov r0.xyz, r0.xyzx  // linearRGB<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 24
  ge r3.xyz, l(0.003131, 0.003131, 0.003131, 0.000000), r0.xyzx
  movc r3.xyz, r3.xyzx, l(1.000000,1.000000,1.000000,0), l(0,0,0,0)  // mask<0:[-0f,1f],1:[-0f,1f],2:[-0f,1f]>

#line 25
  mul r5.xyz, r0.xyzx, l(12.920000, 12.920000, 12.920000, 0.000000)
  mul r5.xyz, r3.xyzx, r5.xyzx
  mov r3.xyz, -r3.xyzx
  add r3.xyz, r3.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  max r0.xyz, r0.xyzx, l(0.000010, 0.000010, 0.000010, 0.000000)
  log r0.xyz, r0.xyzx
  mul r0.xyz, r0.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
  exp r0.xyz, r0.xyzx
  mul r0.xyz, r0.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000)
  add r0.xyz, r0.xyzx, l(-0.055000, -0.055000, -0.055000, 0.000000)
  mul r0.xyz, r0.xyzx, r3.xyzx
  add r0.xyz, r0.xyzx, r5.xyzx  // GammaCorrection<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 192
  mov r0.xyz, r0.xyzx  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 195
  mul r1.w, r1.w, l(1.650000)
  max r1.w, r1.w, l(0.000000)
  min r1.w, r1.w, l(1.000000)  // fadeOut<0:[0f,1f]>

#line 196
  mul r1.w, r1.w, r1.w
  mul r1.w, r1.w, r1.w
  mul r1.w, r1.w, r1.w
  mul r1.w, r1.w, l(1.000000)
  mul r3.w, r1.w, l(1.000000)  // outColor<3:[0f,1f]>

#line 199
  dp3 r1.w, r4.xyzx, r2.xyzx  // NV<0:NaN:Inf>

#line 200
  lt r0.w, l(0.950000), r0.w
  lt r1.w, l(0.250000), r1.w
  and r0.w, r0.w, r1.w
  mul r1.xyz, r1.xyzx, l(3.000000, 3.000000, 3.000000, 0.000000)
  movc r0.xyz, r0.wwww, r1.xyzx, r0.xyzx  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 203
  mul r3.xyz, r3.wwww, r0.xyzx  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 112
endif 

#line 261
mov r3.xyzw, r3.xyzw  // NWormhole_wormhole_outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:[-0f,1f]>

#line 265
mov r3.xyzw, r3.xyzw  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:[-0f,1f]>

#line 212
mov o0.xyzw, r3.xyzw  // outColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:[-0f,1f]>
ret 
// Approximately 240 instruction slots used
