// FidelityFX FSR3 Upscaler 3.1.5 D3D11/SM5 fixed permutation.
// FP32, no wave operations, HDR linear input, render-resolution motion, reverse-Z.

#define FFX_GPU            1
#define FFX_HLSL           1
#define FFX_HLSL_5_0       1
#define FFX_HLSL_SM        50
#define FFX_HALF           0
#define FFX_NO_16_BIT_CAST 1

#define FFX_IMPLICIT_SHADER_REGISTER_BINDING_HLSL 0
#define FFX_FSR3UPSCALER_EMBED_ROOTSIG            0
#define FFX_SPD_NO_WAVE_OPERATIONS                 1

#define FFX_FSR3UPSCALER_OPTION_UPSAMPLE_SAMPLERS_USE_DATA_HALF          0
#define FFX_FSR3UPSCALER_OPTION_ACCUMULATE_SAMPLERS_USE_DATA_HALF        0
#define FFX_FSR3UPSCALER_OPTION_REPROJECT_SAMPLERS_USE_DATA_HALF         0
#define FFX_FSR3UPSCALER_OPTION_POSTPROCESSLOCKSTATUS_SAMPLERS_USE_DATA_HALF 0

#define FFX_FSR3UPSCALER_OPTION_UPSAMPLE_USE_LANCZOS_TYPE     2
#define FFX_FSR3UPSCALER_OPTION_REPROJECT_USE_LANCZOS_TYPE    0
#define FFX_FSR3UPSCALER_OPTION_HDR_COLOR_INPUT               1
#define FFX_FSR3UPSCALER_OPTION_LOW_RESOLUTION_MOTION_VECTORS 1
#define FFX_FSR3UPSCALER_OPTION_JITTERED_MOTION_VECTORS       0
#define FFX_FSR3UPSCALER_OPTION_INVERTED_DEPTH                1

#ifndef FFX_FSR3UPSCALER_OPTION_APPLY_SHARPENING
#define FFX_FSR3UPSCALER_OPTION_APPLY_SHARPENING 0
#endif